// Forge-Change
using System.Linq;
using System.Numerics;
using Content.Client._Wega.Stylesheets;
using Content.Client.GameTicking.Managers;
using Content.Client.Resources;
using Content.Shared.Roles;
using Content.Shared.SecApartment;
using Content.Shared.StatusIcon;
using Robust.Shared.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Wega.Security.SecApartment;

[Virtual]
[GenerateTypedNameReferences]
public partial class SecApartmentWindow : BaseWindow
{
    private static readonly (string Title, string Department)[] DebugSquadDepartments =
    {
        ("ТСФ", "TSF"),
        ("НаноТразен", "NanoTrasen"),
        ("СИВ", "Empire"),
        ("СССП", "UnionOfSovietSocialistPlanets"),
        ("Ренегаты", "Renegates")
    };

    [Dependency] private readonly IUserInterfaceManager _ui = default!;
    [Dependency] private readonly IResourceCache _resCache = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IGameTiming _gameTiming = default!;
    private readonly ClientGameTicker _gameTicker;
    private readonly SpriteSystem _sprite;

    private readonly SecApartmentStyles _styles;
    private string _factionLabel = Loc.GetString("sec-apartment-unknown");
    private ProtoId<SecApUiThemePrototype>? _activeUiTheme;
    private bool _showAliveUnassigned = true;
    private bool _showDeadUnassigned = true;
    private readonly Dictionary<string, bool> _showDebugSquadCategories = new()
    {
        ["TSF"] = false,
        ["NanoTrasen"] = false,
        ["CIV"] = false,
        ["USSP"] = false,
        ["Renegates"] = false
    };
    private List<CrewMemberInfo> _lastUnassignedCrew = new();
    private List<Squad> _lastSquads = new();
    private Dictionary<string, SquadEntry> _squadEntries = new();
    private Dictionary<string, CrewMemberInfo> _lastCrewData = new();
    private Dictionary<string, string> _nameDrafts = new();
    private Dictionary<string, string> _descriptionDrafts = new();
    private Dictionary<NetEntity, TimerEntryControl> _timerControls = new();
    private readonly Dictionary<int, string> _debugDepartmentIds = new();
    private string _selectedDebugDepartment = DebugSquadDepartments[0].Department;
    private Stylesheet? _previousStylesheet;

    public Action<string, string>? OnCreateSquad;
    public Action<string, string>? OnRenameSquad;
    public Action<string>? OnDeleteSquad;
    public Action<string, string>? OnUpdateSquadDescription;
    public Action<string, SquadStatus>? OnChangeSquadStatus;
    public Action<string, string>? OnAddMemberToSquad;
    public Action<string, string>? OnRemoveMemberFromSquad;
    public Action<string, SquadIconNum>? OnChangeSquadIcon;
    public Action<NetEntity>? OnRemoveTimer;

    public SecApartmentWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entitySystem.GetEntitySystem<SpriteSystem>();
        _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
        _styles = new SecApartmentStyles(_resCache);
        _previousStylesheet = _ui.Stylesheet;

        SetupAllStyles();

        OnClose += RestorePreviousStylesheet;
        CloseButton.OnPressed += _ => Close();

        NewSquadName.OnTextChanged += OnSquadNameTextChanged;
        SetupDebugDepartmentDropdown();

        CreateSquadButton.Disabled = string.IsNullOrWhiteSpace(NewSquadName.Text);
        CreateSquadButton.OnPressed += _ =>
        {
            if (!string.IsNullOrWhiteSpace(NewSquadName.Text))
            {
                var squadName = FormattedMessage.RemoveMarkupPermissive(NewSquadName.Text);
                if (squadName.Length > 16) squadName = squadName[..16];

                OnCreateSquad?.Invoke(squadName, DebugSquadDepartmentDropdown.Visible ? _selectedDebugDepartment : string.Empty);
                NewSquadName.Text = string.Empty;
                CreateSquadButton.Disabled = true;
            }
        };
    }

    private void SetupDebugDepartmentDropdown()
    {
        DebugSquadDepartmentDropdown.Clear();
        _debugDepartmentIds.Clear();

        foreach (var (title, department) in DebugSquadDepartments)
        {
            var index = DebugSquadDepartmentDropdown.ItemCount;
            DebugSquadDepartmentDropdown.AddItem(title);
            _debugDepartmentIds[index] = department;
        }

        DebugSquadDepartmentDropdown.Select(0);
        DebugSquadDepartmentDropdown.OnItemSelected += args =>
        {
            DebugSquadDepartmentDropdown.SelectId(args.Id);
            if (_debugDepartmentIds.TryGetValue(args.Id, out var department))
                _selectedDebugDepartment = department;
        };
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos) => DragMode.Move;

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
        StationLabel.Text = Loc.GetString("sec-apartment-ui-mark", ("time", stationTime.ToString("hh\\:mm\\:ss")));
    }

    private void SetupAllStyles()
    {
        SetupBasicStyles();
        SetupTabContainer();
        ApplyThemeChrome();
    }

    private void SetupBasicStyles()
    {
        var theme = _styles.Theme;

        FactionLabel.FontColorOverride = theme.SubText;
        StationLabel.FontColorOverride = theme.Heading;
        StationLabel.FontOverride = _styles.GetBoldFont(16);

        UnassignedCountLabel.FontColorOverride = theme.Text;
        UnassignedCountLabel.FontOverride = _styles.GetRegularFont(13);

        SquadsCountLabel.FontColorOverride = theme.Text;
        SquadsCountLabel.FontOverride = _styles.GetRegularFont(13);

        TimersCountLabel.FontColorOverride = theme.Text;
        TimersCountLabel.FontOverride = _styles.GetRegularFont(13);

        Footer.FontColorOverride = theme.SubText;
        Footer.FontOverride = _styles.GetRegularFont(11);

        StationLabel.AddStyleClass(SecApartmentStyles.StyleClassConsoleHeading);
        NewSquadName.AddStyleClass(SecApartmentStyles.StyleClassConsoleLineEdit);
        CreateSquadButton.AddStyleClass(SecApartmentStyles.StyleClassButtonRed);

        ApplyStylesheetRules();
    }

    // Forge-Change-start
    private void ApplyStylesheetRules()
    {
        var theme = _styles.Theme;

        var buttonStyleRule = _styles.CreateButtonRedRule(
            _styles.GetButtonRedStyle(),
            _styles.GetBoldFont(11),
            theme.TabActive,
            theme.TabInactive
        );

        var lineEditRule = _styles.CreateLineEditRule(
            _styles.GetLineEditStyle(),
            _styles.GetRegularFont(11),
            theme.Text,
            theme.Placeholder
        );

        var optionRule = _styles.CreateOptionButtonRule(
            _styles.GetOptionButtonStyle(),
            _styles.GetRegularFont(11),
            theme.Text,
            theme.TabInactive
        );

        UserInterfaceManager.Stylesheet = CreateCombinedStylesheet(new[] { buttonStyleRule, lineEditRule, optionRule });
    }
    // Forge-Change-end

    private void RestorePreviousStylesheet()
    {
        UserInterfaceManager.Stylesheet = _previousStylesheet;
    }

    private void SetupTabContainer()
    {
        Tabs.SetTabTitle(0, Loc.GetString("sec-apartment-tab-squads"));
        Tabs.SetTabTitle(1, Loc.GetString("sec-apartment-tab-timers"));

        var theme = _styles.Theme;

        Tabs.TabFontColorOverride = theme.TabActive;
        Tabs.TabFontColorInactiveOverride = theme.TabInactive;

        var tabRule = _styles.CreateTabContainerRule(
            _styles.GetTabActiveStyle(),
            _styles.GetTabInactiveStyle(),
            _styles.GetPanelStyle(),
            _styles.GetBoldFont(),
            theme.TabActive,
            theme.TabInactive
        );

        Tabs.Stylesheet = CreateCombinedStylesheet(new[] { tabRule });
    }

    private Stylesheet CreateCombinedStylesheet(StyleRule[] additionalRules)
    {
        var existingStyles = _previousStylesheet ?? _ui.Stylesheet;
        var combinedRules = new List<StyleRule>();

        if (existingStyles?.Rules != null)
            combinedRules.AddRange(existingStyles.Rules);

        combinedRules.AddRange(additionalRules);

        return new Stylesheet(combinedRules);
    }

    private void OnSquadNameTextChanged(LineEdit.LineEditEventArgs args)
    {
        CreateSquadButton.Disabled = string.IsNullOrWhiteSpace(NewSquadName.Text);
    }

    private string GetFactionLabel(string departmentId)
    {
        if (_prototypeManager.TryIndex<DepartmentPrototype>(departmentId, out var department))
            return Loc.GetString(department.Name);

        return Loc.GetString("sec-apartment-unknown");
    }

    public void UpdateState(SecApartmentUpdateState state)
    {
        _factionLabel = GetFactionLabel(state.Department);
        FactionLabel.Text = _factionLabel;
        DebugSquadDepartmentDropdown.Visible = state.Debug;

        UpdateUnassignedList(state.UnassignedSecurity, state.Squads);
        UpdateSquadsList(state.Squads, state.Debug);
    }

    // Forge-Change-start
    public void ApplyUiTheme(ProtoId<SecApUiThemePrototype> uiThemeId)
    {
        if (_activeUiTheme == uiThemeId)
            return;

        if (!_prototypeManager.TryIndex(uiThemeId, out var theme))
            theme = _prototypeManager.Index<SecApUiThemePrototype>(SecApartmentComponent.DefaultUiTheme);

        _activeUiTheme = uiThemeId;
        _styles.SetTheme(theme);

        ApplyLogo(theme);
        Footer.Visible = theme.ShowFooter;

        SetupAllStyles();
    }

    private void ApplyLogo(SecApUiThemePrototype theme)
    {
        if (theme.ShowLogo && !string.IsNullOrEmpty(theme.LogoTexture))
        {
            Logo.Texture = _resCache.GetTexture(theme.LogoTexture);
            Logo.Visible = true;
        }
        else
        {
            Logo.Visible = false;
        }
    }

    private void ApplyThemeChrome()
    {
        var theme = _styles.Theme;

        Background.ModulateSelfOverride = theme.WindowBackground;
        Border.ModulateSelfOverride = theme.WindowBorder;
        CloseButton.ModulateSelfOverride = theme.CloseButton;
        ContentBorder.ModulateSelfOverride = theme.ContentBorder;
        ContentBackground.ModulateSelfOverride = theme.ContentBackground;

        SetThemedPanel(MainDivider, theme.Divider, theme.Divider, 0);
        SetThemedPanel(UnassignedListPanel, theme.ListPanelBackground, theme.ListPanelBorder);
        SetThemedPanel(CreateSquadPanel, theme.CreateSquadPanelBackground, theme.CreateSquadPanelBorder);
        SetThemedPanel(SquadsListPanel, theme.ListPanelBackground, theme.ListPanelBorder);
        SetThemedPanel(TimersListPanel, theme.ListPanelBackground, theme.ListPanelBorder);

        OsStripeSection.Visible = theme.ShowOsStripe;
        ApplyThemeToLabels(this);
    }

    private void SetThemedPanel(PanelContainer panel, Color background, Color border, int borderThickness = 2)
    {
        panel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new Thickness(borderThickness)
        };

        // AngleRect stylesheet modulates panels to #292929 — washes out light palettes.
        if (_styles.Theme.ID == "SecApUiThemeUSSP")
            panel.ModulateSelfOverride = Color.White;
    }

    private void ApplyThemeToLabels(Control parent)
    {
        var theme = _styles.Theme;

        foreach (var child in parent.Children)
        {
            if (child is Label label && label != FactionLabel && label != StationLabel && label != UnassignedCountLabel
                && label != SquadsCountLabel && label != TimersCountLabel && label != Footer)
            {
                if (label.StyleClasses.Contains("ConsoleSubHeading") || label.StyleClasses.Contains("LabelSubText")
                    || label.StyleClasses.Contains("ConsoleSubText"))
                {
                    label.FontColorOverride = theme.SubText;
                }
                else if (label.StyleClasses.Contains("ConsoleHeading")
                         || label.StyleClasses.Contains("ConsoleHeadingBig"))
                {
                    label.FontColorOverride = theme.Heading;
                }
                else if (label.StyleClasses.Contains("ConsoleText"))
                {
                    label.FontColorOverride = theme.Text;
                }
                else
                {
                    label.FontColorOverride = theme.SubText;
                }
            }

            ApplyThemeToLabels(child);
        }
    }
    // Forge-Change-end

    public void UpdateSensorStatuses(SensorStatusUpdateState sensorState)
    {
        foreach (var squadEntry in _squadEntries.Values)
        {
            squadEntry.UpdateSensorStatuses(sensorState.MemberStatuses, sensorState.SquadLocations);
        }

    }

    public void UpdateTimerState(TimerUpdateState state)
    {
        UpdateTimersList(state.Timers);

    }

    private void UpdateUnassignedList(List<CrewMemberInfo> unassigned, List<Squad> squads)
    {
        _lastUnassignedCrew = unassigned;
        _lastSquads = squads;
        UnassignedCountLabel.Text = unassigned.Count.ToString();
        UnassignedContainer.Children.Clear();

        var alive = unassigned
            .Where(member => member.SensorStatus?.IsAlive == true)
            .ToList();
        var dead = unassigned
            .Where(member => member.SensorStatus?.IsAlive != true)
            .ToList();

        AddUnassignedCategory(
            Loc.GetString("sec-apartment-ui-unassigned-alive"),
            alive,
            squads,
            _showAliveUnassigned,
            expanded => _showAliveUnassigned = expanded);

        AddUnassignedCategory(
            Loc.GetString("sec-apartment-ui-unassigned-dead"),
            dead,
            squads,
            _showDeadUnassigned,
            expanded => _showDeadUnassigned = expanded);

    }

    private void AddUnassignedCategory(
        string title,
        List<CrewMemberInfo> members,
        List<Squad> squads,
        bool expanded,
        Action<bool> setExpanded)
    {
        var categoryContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 5)
        };

        var header = new Button
        {
            Text = $"{(expanded ? "[-]" : "[+]")} {title} ({members.Count})",
            HorizontalExpand = true,
            TextAlign = Label.AlignMode.Left
        };
        header.AddStyleClass(SecApartmentStyles.StyleClassButtonRed);
        header.OnPressed += _ =>
        {
            setExpanded(!expanded);
            UpdateUnassignedList(_lastUnassignedCrew, _lastSquads);
        };

        categoryContainer.AddChild(header);

        if (expanded)
        {
            foreach (var member in members)
                categoryContainer.AddChild(CreateUnassignedCrewEntry(member, squads));
        }

        UnassignedContainer.AddChild(categoryContainer);
    }

    private CrewMemberEntry CreateUnassignedCrewEntry(CrewMemberInfo member, List<Squad> squads)
    {
        SpriteSpecifier? iconSpecifier = null;
        if (_prototypeManager.HasIndex<JobIconPrototype>(member.JobIcon))
            iconSpecifier = _prototypeManager.Index<JobIconPrototype>(member.JobIcon).Icon;
        else if (_prototypeManager.HasIndex<StatusIconPrototype>(member.JobIcon))
            iconSpecifier = _prototypeManager.Index<StatusIconPrototype>(member.JobIcon).Icon;

        var entry = new CrewMemberEntry(member, squads, iconSpecifier, _sprite, _styles);
        entry.OnAssignPressed += squadId =>
            OnAddMemberToSquad?.Invoke(squadId, member.MemberId);
        return entry;
    }

    private void UpdateSquadsList(List<Squad> squads, bool debug)
    {
        _nameDrafts = _squadEntries
            .Where(pair => pair.Value.IsEditingName)
            .ToDictionary(pair => pair.Key, pair => pair.Value.NameDraft);
        _descriptionDrafts = _squadEntries
            .Where(pair => pair.Value.IsEditingDescription)
            .ToDictionary(pair => pair.Key, pair => pair.Value.DescriptionDraft);

        SquadsCountLabel.Text = squads.Count.ToString();
        SquadsContainer.Children.Clear();
        _squadEntries.Clear();

        if (debug)
        {
            AddSquadCategory("TSF", "ТСФ", squads.Where(squad => squad.Department == "TSF").ToList(), debug);
            AddSquadCategory("NanoTrasen", "НаноТразен", squads.Where(IsNanoTrasenSquad).ToList(), debug);
            AddSquadCategory("CIV", "СИВ", squads.Where(IsCivilianSquad).ToList(), debug);
            AddSquadCategory("USSP", "СССП", squads.Where(IsUsspSquad).ToList(), debug);
            AddSquadCategory("Renegates", "Ренегаты", squads.Where(squad => squad.Department == "Renegates").ToList(), debug);
            return;
        }

        foreach (var squad in squads)
            AddSquadEntry(squad);
    }

    private void AddSquadCategory(string key, string title, List<Squad> squads, bool debug)
    {
        var expanded = _showDebugSquadCategories.GetValueOrDefault(key, false);
        var categoryContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 5)
        };

        var header = new Button
        {
            Text = $"{(expanded ? "[-]" : "[+]")} {title} ({squads.Count})",
            HorizontalExpand = true,
            TextAlign = Label.AlignMode.Left
        };
        header.AddStyleClass(SecApartmentStyles.StyleClassButtonRed);
        header.OnPressed += _ =>
        {
            _showDebugSquadCategories[key] = !expanded;
            UpdateSquadsList(_lastSquads, debug);
        };

        categoryContainer.AddChild(header);

        if (expanded)
        {
            foreach (var squad in squads)
                categoryContainer.AddChild(CreateSquadEntry(squad));
        }

        SquadsContainer.AddChild(categoryContainer);
    }

    private void AddSquadEntry(Squad squad)
    {
        SquadsContainer.AddChild(CreateSquadEntry(squad));
    }

    private SquadEntry CreateSquadEntry(Squad squad)
    {
        var entry = new SquadEntry(squad, _styles, _prototypeManager, _sprite);
        entry.OnIconChanged += iconId =>
            OnChangeSquadIcon?.Invoke(squad.SquadId, iconId);
        entry.OnRenamePressed += newName =>
        {
            var cleanName = FormattedMessage.RemoveMarkupPermissive(newName);
            if (cleanName.Length > 16) cleanName = cleanName[..16];

            OnRenameSquad?.Invoke(squad.SquadId, cleanName);
        };
        entry.OnDeletePressed += () =>
            OnDeleteSquad?.Invoke(squad.SquadId);
        entry.OnUpdateDescriptionPressed += description =>
            OnUpdateSquadDescription?.Invoke(squad.SquadId, description);
        entry.OnStatusChanged += status =>
            OnChangeSquadStatus?.Invoke(squad.SquadId, status);
        entry.OnRemoveMemberPressed += memberId =>
            OnRemoveMemberFromSquad?.Invoke(squad.SquadId, memberId);

        _squadEntries[squad.SquadId] = entry;

        foreach (var member in squad.Members)
            _lastCrewData[member.MemberId] = member;

        if (_nameDrafts.TryGetValue(squad.SquadId, out var nameDraft))
            entry.RestoreNameEdit(nameDraft);

        if (_descriptionDrafts.TryGetValue(squad.SquadId, out var draft))
            entry.RestoreDescriptionEdit(draft);

        return entry;
    }

    private static bool IsNanoTrasenSquad(Squad squad)
    {
        return squad.Department is "Security" or "NanoTrasen" or "Command";
    }

    private static bool IsCivilianSquad(Squad squad)
    {
        return squad.Department is "CIV" or "Empire";
    }

    private static bool IsUsspSquad(Squad squad)
    {
        return squad.Department is "USSP" or "СССП" or "UnionOfSovietSocialistPlanets";
    }

    private void UpdateTimersList(List<TimerEntry> timers)
    {
        TimersCountLabel.Text = timers.Count.ToString();

        var toRemove = new List<NetEntity>();
        foreach (var (timerUid, control) in _timerControls)
        {
            if (!timers.Any(t => t.TimerUid == timerUid))
                toRemove.Add(timerUid);
        }

        foreach (var timerUid in toRemove)
        {
            if (_timerControls.TryGetValue(timerUid, out var control))
            {
                TimersContainer.Children.Remove(control);
                _timerControls.Remove(timerUid);
            }
        }

        foreach (var timer in timers)
        {
            if (!_timerControls.TryGetValue(timer.TimerUid, out var control))
            {
                control = new TimerEntryControl(timer, _styles);
                control.OnRemovePressed += () =>
                    OnRemoveTimer?.Invoke(timer.TimerUid);
                TimersContainer.AddChild(control);
                _timerControls[timer.TimerUid] = control;
            }
            else
            {
                control.UpdateTimer(timer);
            }
        }

        var sortedChildren = TimersContainer.Children
            .OfType<TimerEntryControl>()
            .OrderBy(t => t.RemainingTime.TotalSeconds)
            .ToList();

        TimersContainer.Children.Clear();
        foreach (var child in sortedChildren)
        {
            TimersContainer.AddChild(child);
        }
    }
}
