using Content.Client._Forge.Trade.Theme;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._Forge.Trade.Controls;


[GenerateTypedNameReferences]
public sealed partial class NcCategoryButtonControl : Button
{
    private static readonly Color IdleText = NcStoreUiTheme.ResolveColor("#B6B0A4", "#B6B0A4");
    private static readonly Color HoverText = NcStoreUiTheme.ResolveColor("#D3CDC0", "#D3CDC0");
    private bool _hovered;
    private Color _idleColor = new(0x7C, 0x66, 0x24);

    private Color _selectedColor = new(0xD9, 0xA4, 0x41);
    private Color _surfaceBase = NcStoreUiTheme.ResolveColor("#161A20", "#161A20");

    public NcCategoryButtonControl()
    {
        RobustXamlLoader.Load(this);

        OnMouseEntered += _ =>
        {
            _hovered = true;
            ApplyVisualState();
        };

        OnMouseExited += _ =>
        {
            _hovered = false;
            ApplyVisualState();
        };

        OnPressed += _ =>
        {
            OnCategoryPressed?.Invoke(CategoryId);
        };

        ApplyVisualState();
    }

    public string CategoryId { get; private set; } = string.Empty;

    public event Action<string>? OnCategoryPressed;

    public void Bind(string categoryId, string text, string? tooltip)
    {
        CategoryId = categoryId;
        TitleLabel.Text = text;
        ToolTip = tooltip;
        Text = string.Empty;
    }

    public void SetSelected(bool selected)
    {
        if (Pressed != selected)
            Pressed = selected;

        ApplyVisualState();
    }

    public void SetThemeColors(Color idleColor, Color selectedColor, Color surfaceBase)
    {
        _idleColor = idleColor;
        _selectedColor = selectedColor;
        _surfaceBase = surfaceBase;
        ApplyVisualState();
    }

    private void ApplyVisualState()
    {
        var background = GetBackgroundColor();
        var accent = GetAccentColor();
        var text = GetTextColor();

        var style = NcStoreUiTheme.Fill(background);

        style.SetContentMarginOverride(StyleBox.Margin.Left, 0);
        style.SetContentMarginOverride(StyleBox.Margin.Right, 0);
        style.SetContentMarginOverride(StyleBox.Margin.Top, 0);
        style.SetContentMarginOverride(StyleBox.Margin.Bottom, 0);

        StyleBoxOverride = style;
        ModulateSelfOverride = Color.White;

        AccentBar.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = accent,
            BorderThickness = new(0)
        };

        TitleLabel.ModulateSelfOverride = text;
    }

    private Color GetBackgroundColor()
    {
        var baseSurface = GetBaseSurface();
        var hoverSurface = GetHoverSurface();
        var selectedSurface = GetSelectedSurface();

        if (Pressed)
            return NcStoreUiTheme.Blend(selectedSurface, _selectedColor, 0.18f);

        if (_hovered)
            return NcStoreUiTheme.Blend(hoverSurface, _idleColor, 0.11f);

        return NcStoreUiTheme.Blend(baseSurface, _idleColor, 0.08f);
    }


    private Color GetAccentColor()
    {
        var baseSurface = GetBaseSurface();

        if (Pressed)
            return _selectedColor;

        if (_hovered)
            return NcStoreUiTheme.Blend(_idleColor, Color.White, 0.12f);

        return NcStoreUiTheme.WithAlpha(NcStoreUiTheme.Blend(_idleColor, baseSurface, 0.35f), 0.70f);
    }

    private Color GetTextColor()
    {
        if (Pressed)
            return NcStoreUiTheme.Blend(NcStoreUiTheme.ResolveColor("#ECE4D4", "#ECE4D4"), _selectedColor, 0.10f);

        if (_hovered)
            return HoverText;

        return IdleText;
    }

    private Color GetBaseSurface() => NcStoreUiTheme.Blend(_surfaceBase, _idleColor, 0.18f);

    private Color GetHoverSurface() =>
        NcStoreUiTheme.Blend(NcStoreUiTheme.Blend(_surfaceBase, Color.White, 0.03f), _idleColor, 0.26f);

    private Color GetSelectedSurface() =>
        NcStoreUiTheme.Blend(NcStoreUiTheme.Blend(_surfaceBase, _selectedColor, 0.18f), _selectedColor, 0.24f);
}
