using Content.Client._Forge.Trade.Theme;
using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.Trade;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._Forge.Trade.Controls;


[GenerateTypedNameReferences]
public sealed partial class NcContractConfirmWindow : FancyWindow
{
    public event Action? Confirmed;

    public NcContractConfirmWindow(
        string title,
        string message,
        string confirmText,
        StoreUiColorsData colors,
        Color confirmBackground,
        Color confirmBorder
    )
    {
        RobustXamlLoader.Load(this);

        Title = title;
        Resizable = false;
        YesButton.Text = confirmText;
        MessageLabel.MaxWidth = 420;
        MessageLabel.SetMessage(message, null, NcStoreUiTheme.ResolveColor(colors.ListingTitleColor, "#DDD6C7"));

        ApplyTheme(colors, confirmBackground, confirmBorder);

        YesButton.OnPressed += _ => Confirmed?.Invoke();
        NoButton.OnPressed += _ => Close();
    }

    private void ApplyTheme(StoreUiColorsData colors, Color confirmBackground, Color confirmBorder)
    {
        var background = NcStoreUiTheme.ResolveColor(colors.ListingCardBackground, "#141A22");
        var border = NcStoreUiTheme.ResolveColor(colors.ListingCardBorder, "#314052");
        var actionBorder = NcStoreUiTheme.Blend(border, confirmBorder, 0.35f);

        Frame.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = actionBorder,
            BorderThickness = new(1),
            ContentMarginLeftOverride = 8,
            ContentMarginRightOverride = 8,
            ContentMarginTopOverride = 8,
            ContentMarginBottomOverride = 8
        };

        Divider.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = actionBorder,
            BorderThickness = new(0)
        };

        YesButton.StyleBoxOverride = BuildButtonStyle(confirmBackground, confirmBorder);
        YesButton.ModulateSelfOverride = Color.FromHex("#E5EEF8");
        YesButton.ToolTip = YesButton.Text;

        NoButton.StyleBoxOverride = BuildButtonStyle(Color.FromHex("#23272D"), Color.FromHex("#475363"));
        NoButton.ModulateSelfOverride = Color.FromHex("#D7DDEA");
        NoButton.ToolTip = Loc.GetString("nc-store-contract-confirm-no");
    }

    private static StyleBoxFlat BuildButtonStyle(Color background, Color border) =>
        new()
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new(1),
            ContentMarginLeftOverride = 8,
            ContentMarginRightOverride = 8,
            ContentMarginTopOverride = 4,
            ContentMarginBottomOverride = 4
        };
}
