using System.Numerics;
using Content.Client._Forge.Trade.Theme;
using Content.Shared._Forge.Trade;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;


namespace Content.Client._Forge.Trade.Controls;


[GenerateTypedNameReferences]
public sealed partial class NcContractCard : PanelContainer
{
    private const float DescriptionHorizontalBudget = 40f;
    private const int TargetIconPx = 56;
    private const int RewardIconPx = 26;
    private const float ProgressFillMinVisibleWidth = 8f;
    private readonly Action<NcContractConfirmWindow> _activateConfirmWindow;
    private readonly IPrototypeManager _proto;
    private readonly SpriteSystem _sprites;

    private ContractClientData _data;
    private float _lastDescriptionMaxWidth = -1f;
    private float _progressRatio;
    private int _skipBalance;
    private int _skipCost;
    private string _skipCurrency;
    private NcContractConfirmWindow? _confirmWindow;
    private StoreUiColorsData _uiColors = new();

    public NcContractCard(
        ContractClientData data,
        IPrototypeManager protoMan,
        SpriteSystem sprites,
        int skipCost = 0,
        string skipCurrency = "",
        int skipBalance = 0,
        Action<NcContractConfirmWindow>? activateConfirmWindow = null
    )
    {
        RobustXamlLoader.Load(this);

        _activateConfirmWindow = activateConfirmWindow ?? (_ => { });
        _data = data;
        _proto = protoMan;
        _sprites = sprites;
        _skipCost = skipCost;
        _skipCurrency = skipCurrency;
        _skipBalance = skipBalance;
        PrimaryActionButton.OnPressed += OnPrimaryActionPressed;

        PopulateUi();
    }

    public event Action<string>? OnClaim;
    public event Action<string>? OnTake;
    public event Action<string>? OnSkip;
    public event Action<string>? OnRequestPinpointer;

    public void ApplyUiTheme(StoreUiColorsData colors)
    {
        _uiColors = colors;
        ApplyOfferChrome();
        PopulateActionsSection();
    }


    private static Color Dim(Color color, float factor) =>
        new(
            color.R * factor,
            color.G * factor,
            color.B * factor,
            color.A);

    private Color ResolveOfferAccent()
    {
        var themed = NcStoreUiTheme.ResolveColor(_uiColors.CategoryButtonSelected, "#4F86B7");
        if (string.IsNullOrWhiteSpace(_data.OfferPoolColor))
            return themed;

        try
        {
            return Color.FromHex(_data.OfferPoolColor.Trim());
        }
        catch
        {
            return themed;
        }
    }

    private void PopulateUi()
    {
        ApplyOfferChrome();
        PopulateHeader();
        PopulateDescription();
        PopulateStatus();
        PopulateStage();
        PopulateGoals();
        PopulateTurnIn();
        PopulateProgress();
        PopulateRewardsSection();
        PopulateActionsSection();
        SyncDescriptionWidth(Size.X);
    }

    private void ApplyOfferChrome()
    {
        var baseAccent = ResolveOfferAccent();
        var accent = _data.Completed
            ? Dim(baseAccent, 0.55f)
            : baseAccent;

        var cardBackground = NcStoreUiTheme.ResolveColor(_uiColors.ListingCardBackground, "#141A22");
        var cardBorder = NcStoreUiTheme.ResolveColor(_uiColors.ListingCardBorder, "#314052");
        var sideBackground = NcStoreUiTheme.ResolveColor(_uiColors.TabsFrameBackground, "#18202A");
        var secondaryText = NcStoreUiTheme.ResolveColor(_uiColors.TabFontInactive, "#AEBBCC");
        var primaryText = NcStoreUiTheme.ResolveColor(_uiColors.ListingTitleColor, "#DDD6C7");
        var progressTrackBg = NcStoreUiTheme.ResolveColor(_uiColors.TabsShellBackground, "#0E1319");

        AccentStrip.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = accent
        };

        CardFrame.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = cardBackground,
            BorderColor = cardBorder,
            BorderThickness = new(1),
            ContentMarginLeftOverride = 6,
            ContentMarginRightOverride = 6,
            ContentMarginTopOverride = 5,
            ContentMarginBottomOverride = 5
        };

        SidePanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = sideBackground,
            BorderColor = cardBorder,
            BorderThickness = new(1),
            ContentMarginLeftOverride = 6,
            ContentMarginRightOverride = 6,
            ContentMarginTopOverride = 5,
            ContentMarginBottomOverride = 5
        };

        ProgressTrack.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = progressTrackBg,
            BorderColor = cardBorder,
            BorderThickness = new(1),
            ContentMarginLeftOverride = 1,
            ContentMarginRightOverride = 1,
            ContentMarginTopOverride = 1,
            ContentMarginBottomOverride = 1
        };

        ProgressFill.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = accent
        };

        TitleLabel.Modulate = _data.Completed
            ? Dim(primaryText, 0.85f)
            : primaryText;

        GoalsHeaderLabel.Modulate = secondaryText;
        TurnInHeaderLabel.Modulate = secondaryText;
        RewardsHeaderLabel.Modulate = secondaryText;
        ProgressLabel.Modulate = secondaryText;
        ProgressValueLabel.Modulate = NcStoreUiTheme.ResolveColor(_uiColors.TabFontActive, "#D7E1EC");
        TurnInNoteLabel.Modulate = NcStoreUiTheme.ResolveColor(_uiColors.HeaderBalanceText, "#C5D0DD");
        StageLabel.Modulate = NcStoreUiTheme.ResolveColor(_uiColors.TabFontActive, "#89B2E1");
    }

    private void PopulateHeader()
    {
        var title = BuildPrettyTitle(_data);
        TitleLabel.Text = title;
        TitleLabel.ToolTip = title;

        BadgesRow.RemoveAllChildren();

        if (!string.IsNullOrWhiteSpace(_data.OfferPoolName))
        {
            var poolName = _data.OfferPoolName.Trim();
            var accent = ResolveOfferAccent();
            BadgesRow.AddChild(
                BuildBadge(
                    poolName,
                    Loc.GetString("nc-store-contract-offer-pool-tooltip", ("pool", poolName)),
                    Dim(accent, 0.28f),
                    accent));
        }

        var objectiveTypeText = ObjectiveTypeName(_data.ExecutionKind);
        var objectiveTypeTip = ObjectiveTypeTooltip(_data.ExecutionKind);
        BadgesRow.AddChild(
            BuildBadge(
                objectiveTypeText,
                objectiveTypeTip,
                Color.FromHex("#232127"),
                Color.FromHex("#8A7442")));

        if (GetObjectiveType(_data) == ContractObjectiveType.Hunt)
        {
            var modeName = BuildHuntModeName(_data);
            var modeHint = BuildHuntModeHint(_data);
            BadgesRow.AddChild(
                BuildBadge(
                    modeName,
                    modeHint,
                    Color.FromHex("#2D241E"),
                    Color.FromHex("#B06B44")));
        }

        if (GetObjectiveType(_data) == ContractObjectiveType.GhostRole)
        {
            var modeName = BuildGhostRoleModeName(_data);
            var modeHint = BuildGhostRoleModeHint(_data);
            BadgesRow.AddChild(
                BuildBadge(
                    modeName,
                    modeHint,
                    Color.FromHex("#272331"),
                    Color.FromHex("#8E6FC2")));
        }

        if (!_data.Repeatable)
        {
            var tip = Loc.GetString("nc-store-contract-badge-single-tooltip");
            BadgesRow.AddChild(
                BuildBadge(
                    Loc.GetString("nc-store-contract-badge-single"),
                    tip,
                    Color.FromHex("#2A2627"),
                    Color.FromHex("#6B5A3A")));
        }

        if (_data.FlowStatus is ContractFlowStatus.AwaitingActivation or ContractFlowStatus.InProgress)
        {
            BadgesRow.AddChild(
                BuildBadge(
                    Loc.GetString("nc-store-contract-badge-taken"),
                    Loc.GetString("nc-store-contract-badge-taken-tooltip"),
                    Color.FromHex("#2A313B"),
                    Color.FromHex("#8A7442")));

            if (IsGhostRoleAwaitingAcceptance(_data))
            {
                BadgesRow.AddChild(
                    BuildBadge(
                        Loc.GetString("nc-store-contract-badge-awaiting-ghost-role"),
                        Loc.GetString("nc-store-contract-badge-awaiting-ghost-role-tooltip"),
                        Color.FromHex("#3A2E19"),
                        Color.FromHex("#C69A46")));
            }
            else if (IsGhostRoleActive(_data))
            {
                BadgesRow.AddChild(
                    BuildBadge(
                        Loc.GetString("nc-store-contract-badge-ghost-role-active"),
                        Loc.GetString("nc-store-contract-badge-ghost-role-active-tooltip"),
                        Color.FromHex("#243040"),
                        Color.FromHex("#8FA8C5")));
            }
        }

        if (_data.FlowStatus == ContractFlowStatus.ReadyToTurnIn)
        {
            BadgesRow.AddChild(
                BuildBadge(
                    Loc.GetString("nc-store-contract-badge-completed"),
                    Loc.GetString("nc-store-contract-badge-completed-tooltip"),
                    Color.FromHex("#243125"),
                    Color.FromHex("#8AA05D")));
        }
    }

    private void PopulateDescription()
    {
        var fullText = BuildPrettyDescription(_data);
        if (string.IsNullOrWhiteSpace(fullText))
        {
            DescriptionLabel.Visible = false;
            DescriptionLabel.ToolTip = null;
            DescriptionLabel.SetMessage(string.Empty, null, Color.FromHex("#D5CDC0"));
            return;
        }

        DescriptionLabel.Visible = true;
        DescriptionLabel.ToolTip = fullText;
        DescriptionLabel.SetMessage(fullText, null, Color.FromHex("#D5CDC0"));
    }

    private void PopulateStatus()
    {
        var statusText = BuildGhostRoleStatusText(_data);
        if (string.IsNullOrWhiteSpace(statusText))
            statusText = BuildHuntStatusText(_data);

        if (string.IsNullOrWhiteSpace(statusText))
            statusText = BuildArtifactStudyStatusText(_data);

        if (string.IsNullOrWhiteSpace(statusText))
            statusText = BuildRouteStatusText(_data);

        statusText = BuildActiveDeadlineStatusText(_data, statusText);

        if (string.IsNullOrWhiteSpace(statusText))
        {
            StatusLabel.Visible = false;
            StatusLabel.Text = string.Empty;
            StatusLabel.ToolTip = null;
            return;
        }

        StatusLabel.Visible = true;
        StatusLabel.Text = statusText;
        StatusLabel.ToolTip = statusText;
        StatusLabel.Modulate = IsGhostRoleAwaitingAcceptance(_data)
            ? Color.FromHex("#D3B06A")
            : _data.FlowStatus == ContractFlowStatus.Failed
                ? Color.FromHex("#D97575")
                : _data.FlowStatus == ContractFlowStatus.ReadyToTurnIn
                    ? Color.FromHex("#9FCB81")
                    : Color.FromHex("#8DB7E8");
    }

    private void PopulateStage()
    {
        var hasStageKind = ContractExecutionKinds.UsesStageProgress(_data.ExecutionKind);
        var hasStage = hasStageKind && _data.Runtime.StageGoal > 1;

        StageLabel.Visible = hasStage;
        if (!hasStage)
            return;

        var stage = Math.Clamp(_data.Runtime.Stage, 0, _data.Runtime.StageGoal);
        StageLabel.Text = Loc.GetString(
            "nc-store-contract-runtime-stage",
            ("stage", stage),
            ("goal", _data.Runtime.StageGoal));
    }

    private void PopulateGoals()
    {
        GoalsHost.RemoveAllChildren();

        if (_data.Targets is { Count: > 0, })
        {
            foreach (var target in _data.Targets)
                GoalsHost.AddChild(BuildTargetRow(
                    target.TargetItem,
                    target.Required,
                    target.MatchMode,
                    _data.Icon));
        }
        else if (!string.IsNullOrWhiteSpace(_data.TargetItem))
            GoalsHost.AddChild(BuildTargetRow(_data.TargetItem, _data.Required, PrototypeMatchMode.Exact, _data.Icon));
    }

    private void PopulateTurnIn()
    {
        var turnInNote = BuildTurnInNoteText(_data);
        TurnInNoteLabel.Visible = !string.IsNullOrWhiteSpace(turnInNote);
        TurnInNoteLabel.Text = turnInNote;
        TurnInNoteLabel.ToolTip = turnInNote;

        TurnInSection.Visible = ShouldShowTurnInItem(_data);
        TurnInHost.RemoveAllChildren();

        if (TurnInSection.Visible)
        {
            TurnInHeaderLabel.Text = BuildTurnInHeaderText(_data);
            TurnInHost.AddChild(BuildTargetRow(_data.TurnInItem, 1));
        }
    }

    private void PopulateProgress()
    {
        ProgressSection.Visible = !_data.Completed;
        if (!ProgressSection.Visible)
            return;

        var max = CalculateRequiredTotal(_data);
        var val = Math.Clamp(_data.Progress, 0, max);
        _progressRatio = max > 0 ? (float) val / max : 0f;

        ProgressLabel.Text = _data.IsRetrievalRoute
            ? Loc.GetString("nc-store-contract-progress-caption-delivered")
            : Loc.GetString("nc-store-contract-progress-caption");
        ProgressValueLabel.Text = Loc.GetString(
            "nc-store-contract-progress-value",
            ("progress", val),
            ("required", max));
        UpdateProgressFillWidth();
    }

    private void PopulateRewardsSection()
    {
        RewardsHost.RemoveAllChildren();
        PopulateRewards(RewardsHost, _data.Rewards);
    }

    private void PopulateActionsSection()
    {
        var canTake = _data.FlowStatus == ContractFlowStatus.Available;
        var requiredTotal = CalculateRequiredTotal(_data);
        var canClaim = _data.FlowStatus == ContractFlowStatus.ReadyToTurnIn;
        var canPartialTurnIn = CanPartialTurnIn(_data, requiredTotal);
        var canRequestPinpointer = CanRequestPinpointer(_data);

        var actionHint = BuildActionHintText(_data);
        ActionHintLabel.Text = actionHint;
        ActionHintLabel.ToolTip = actionHint;
        ActionHintLabel.Modulate = canClaim || canPartialTurnIn
            ? Color.FromHex("#D7E3EE")
            : Color.FromHex("#AAB7C8");

        PrimaryActionButton.Text = canTake
            ? Loc.GetString("nc-store-contract-action-take")
            : canClaim
                ? Loc.GetString("nc-store-contract-action-claim")
                : Loc.GetString(
                    "nc-store-contract-action-claim-progress",
                    ("progress", _data.Progress),
                    ("required", requiredTotal));

        PrimaryActionButton.ClipText = true;
        PrimaryActionButton.Disabled = !(canTake || canClaim || canPartialTurnIn);
        PrimaryActionButton.StyleBoxOverride = canTake
            ? BuildButtonStyle(Color.FromHex("#203248"), Color.FromHex("#4F86B7"))
            : canClaim || canPartialTurnIn
                ? BuildButtonStyle(Color.FromHex("#243729"), Color.FromHex("#7DA260"))
                : BuildButtonStyle(Color.FromHex("#23272D"), Color.FromHex("#475363"));

        PrimaryActionButton.ModulateSelfOverride = canTake
            ? Color.FromHex("#E5EEF8")
            : canClaim || canPartialTurnIn
                ? Color.FromHex("#E5EEDB")
                : Color.FromHex("#A6AFBA");

        PrimaryActionButton.ToolTip = canTake
            ? Loc.GetString("nc-store-contract-take-tooltip")
            : canClaim
                ? !_data.Repeatable
                    ? Loc.GetString("nc-store-contract-claim-tooltip-single")
                    : Loc.GetString("nc-store-contract-claim-tooltip-repeatable")
                : canPartialTurnIn
                    ? Loc.GetString("nc-store-contract-claim-tooltip-partial")
                    : Loc.GetString("nc-store-contract-claim-tooltip-not-done");

        SecondaryButtonsRow.RemoveAllChildren();

        if (canRequestPinpointer)
        {
            var pointerBtn = new Button
            {
                Text = Loc.GetString("nc-store-contract-action-pinpointer"),
                HorizontalExpand = true,
                MinSize = new(0, 24),
                ClipText = true,
                ToolTip = Loc.GetString("nc-store-contract-action-pinpointer-tooltip")
            };
            pointerBtn.StyleBoxOverride = BuildButtonStyle(Color.FromHex("#1F2833"), Color.FromHex("#4F86B7"));
            pointerBtn.ModulateSelfOverride = Color.FromHex("#D7E6F5");

            pointerBtn.OnPressed += _ => OnRequestPinpointer?.Invoke(_data.Id);
            SecondaryButtonsRow.AddChild(pointerBtn);
        }

        if (canTake && _skipCost > 0 && !string.IsNullOrWhiteSpace(_skipCurrency))
        {
            var skipCurrencyName = CurrencyName(_skipCurrency);
            var canSkip = _skipBalance >= _skipCost;
            var skipBtn = new Button
            {
                Text = Loc.GetString(
                    "nc-store-contract-action-skip",
                    ("cost", _skipCost),
                    ("currency", skipCurrencyName)),
                HorizontalExpand = true,
                MinSize = new(0, 24),
                ClipText = true,
                Disabled = !canSkip
            };

            skipBtn.StyleBoxOverride = canSkip
                ? BuildButtonStyle(Color.FromHex("#2A2C32"), Color.FromHex("#6E7E91"))
                : BuildButtonStyle(Color.FromHex("#222428"), Color.FromHex("#454C55"));
            skipBtn.ModulateSelfOverride = canSkip
                ? Color.FromHex("#D7DDEA")
                : Color.FromHex("#8A919A");

            var baseTip = Loc.GetString(
                "nc-store-contract-skip-tooltip",
                ("cost", _skipCost),
                ("currency", skipCurrencyName));
            skipBtn.ToolTip = canSkip
                ? baseTip
                : $"{baseTip}\n{Loc.GetString("nc-store-contract-skip-failed")}";

            skipBtn.OnPressed += _ =>
            {
                if (canSkip)
                {
                    var contractId = _data.Id;
                    ShowContractConfirmation(
                        Loc.GetString("nc-store-contract-confirm-skip-title"),
                        Loc.GetString("nc-store-contract-confirm-skip", ("contract", BuildPrettyTitle(_data))),
                        Loc.GetString("nc-store-contract-confirm-skip-action"),
                        Color.FromHex("#3A2A1F"),
                        Color.FromHex("#B06B44"),
                        skipBtn,
                        () => OnSkip?.Invoke(contractId));
                }
            };

            SecondaryButtonsRow.AddChild(skipBtn);
        }

        SecondaryButtonsRow.Visible = SecondaryButtonsRow.ChildCount > 0;
    }

    private void OnPrimaryActionPressed(BaseButton.ButtonEventArgs args)
    {
        var canTake = _data.FlowStatus == ContractFlowStatus.Available;
        var canClaim = _data.FlowStatus == ContractFlowStatus.ReadyToTurnIn;
        var canPartialTurnIn = CanPartialTurnIn(_data, CalculateRequiredTotal(_data));

        if (canTake)
        {
            var contractId = _data.Id;
            ShowContractConfirmation(
                Loc.GetString("nc-store-contract-confirm-take-title"),
                Loc.GetString("nc-store-contract-confirm-take", ("contract", BuildPrettyTitle(_data))),
                Loc.GetString("nc-store-contract-confirm-take-action"),
                Color.FromHex("#203248"),
                ResolveOfferAccent(),
                PrimaryActionButton,
                () => OnTake?.Invoke(contractId));
            return;
        }

        if (canClaim || canPartialTurnIn)
            OnClaim?.Invoke(_data.Id);
    }

    private void ShowContractConfirmation(
        string title,
        string message,
        string confirmText,
        Color confirmBackground,
        Color confirmBorder,
        Control anchor,
        Action onConfirmed
    )
    {
        _confirmWindow?.Close();

        var window = new NcContractConfirmWindow(
            title,
            message,
            confirmText,
            _uiColors,
            confirmBackground,
            confirmBorder);
        window.Confirmed += () =>
        {
            if (_confirmWindow != window)
                return;

            _confirmWindow = null;
            window.Close();
            onConfirmed();
        };

        window.OnClose += () =>
        {
            if (_confirmWindow == window)
                _confirmWindow = null;
        };

        _confirmWindow = window;
        _activateConfirmWindow(window);
        OpenConfirmationNear(window, anchor);
    }

    private void OpenConfirmationNear(NcContractConfirmWindow window, Control anchor)
    {
        var rootSize = Root?.Size;
        if (rootSize == null || rootSize.Value.X <= 0 || rootSize.Value.Y <= 0)
        {
            window.OpenCentered();
            return;
        }

        window.Measure(new Vector2(float.PositiveInfinity, float.PositiveInfinity));

        var desired = window.DesiredSize;
        var anchorPos = anchor.GlobalPosition;
        var gap = 8f;

        var pos = new Vector2(
            anchorPos.X + anchor.Width - desired.X,
            anchorPos.Y + anchor.Height + gap);

        if (pos.Y + desired.Y > rootSize.Value.Y)
            pos.Y = anchorPos.Y - desired.Y - gap;

        var maxPos = Vector2.Max(Vector2.Zero, rootSize.Value - desired);
        pos = Vector2.Clamp(pos, Vector2.Zero, maxPos);
        window.Open(pos);
    }

    private static bool CanPartialTurnIn(ContractClientData data, int requiredTotal) =>
        data.ExecutionKind == ContractExecutionKind.InventoryDelivery &&
        data.FlowStatus == ContractFlowStatus.InProgress &&
        data.PartialTurnInAvailable &&
        data.Progress > 0 &&
        data.Progress < requiredTotal;

    private static PanelContainer BuildBadge(string text, string? tooltip, Color bg, Color border)
    {
        var badge = new PanelContainer
        {
            VerticalAlignment = VAlignment.Center,
            Margin = new(0, 0, 4, 0),
            MouseFilter = MouseFilterMode.Stop,
            ToolTip = tooltip,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = bg,
                BorderColor = border,
                BorderThickness = new(1),
                ContentMarginLeftOverride = 5,
                ContentMarginRightOverride = 5,
                ContentMarginTopOverride = 1,
                ContentMarginBottomOverride = 1
            }
        };

        var badgeText = new Label
        {
            Text = text,
            VerticalAlignment = VAlignment.Center,
            MouseFilter = MouseFilterMode.Ignore,
            ToolTip = tooltip
        };
        badgeText.StyleClasses.Add("LabelSubText");
        badgeText.Modulate = Color.FromHex("#D7DDEA");

        badge.AddChild(badgeText);
        return badge;
    }

    private static StyleBoxFlat BuildButtonStyle(Color background, Color border) =>
        new()
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new(1),
            ContentMarginLeftOverride = 5,
            ContentMarginRightOverride = 5,
            ContentMarginTopOverride = 3,
            ContentMarginBottomOverride = 3
        };

    public void UpdateData(ContractClientData data, int skipCost, string skipCurrency, int skipBalance)
    {
        _data = data;
        _skipCost = skipCost;
        _skipCurrency = skipCurrency;
        _skipBalance = skipBalance;
        _lastDescriptionMaxWidth = -1f;

        PopulateUi();
    }

    protected override void Resized()
    {
        base.Resized();
        SyncDescriptionWidth(Size.X);
        UpdateProgressFillWidth();
    }

    private void SyncDescriptionWidth(float candidateWidth)
    {
        if (candidateWidth <= 0 || !float.IsFinite(candidateWidth))
            return;

        var maxWidth = MathF.Max(0, candidateWidth - DescriptionHorizontalBudget);
        if (MathF.Abs(_lastDescriptionMaxWidth - maxWidth) < 0.5f)
            return;

        _lastDescriptionMaxWidth = maxWidth;
        DescriptionLabel.MaxWidth = maxWidth;
    }

    private void UpdateProgressFillWidth()
    {
        var trackWidth = ProgressTrack.Width;
        if (trackWidth <= 0 || !float.IsFinite(trackWidth))
            return;

        var fillWidth = _progressRatio <= 0f
            ? 0f
            : MathF.Max(ProgressFillMinVisibleWidth, trackWidth * _progressRatio);

        ProgressFill.MinSize = new(fillWidth, ProgressFill.MinSize.Y);
        ProgressFill.Visible = fillWidth > 0f;
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            CloseConfirmation();

        base.Dispose(disposing);
    }

    public void CloseConfirmation()
    {
        var confirmWindow = _confirmWindow;
        _confirmWindow = null;
        confirmWindow?.Close();
    }
}
