using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._Forge.Trade.Controls;


[GenerateTypedNameReferences]
public sealed partial class NcListingsPane : PanelContainer
{
    private BoxContainer? _host;
    private string _key = string.Empty;

    private ScrollContainer? _scroll;

    public NcListingsPane()
    {
        RobustXamlLoader.Load(this);
        RectClipContent = true;

        RebuildScroll(false);
    }

    public bool RememberScrollPerKey { get; set; } = false;

    public void SetContent(Control content)
    {
        EnsureBuilt();

        _host!.RemoveAllChildren();
        _host.AddChild(content);
    }

    public void SetKey(string? key)
    {
        key ??= string.Empty;

        if (_key == key)
            return;

        _key = key;

        RebuildScroll(true);
    }

    public void ResetScroll() => RebuildScroll(true);

    private void EnsureBuilt()
    {
        if (_scroll != null && _host != null)
            return;

        RebuildScroll(false);
    }

    private void RebuildScroll(bool preserveContent)
    {
        List<Control>? preserved = null;

        if (preserveContent && _host != null)
        {
            preserved = new();
            foreach (var child in _host.Children)
                if (child is Control c)
                    preserved.Add(c);

            foreach (var c in preserved)
                _host.RemoveChild(c);
        }

        ScrollHost.RemoveAllChildren();

        _scroll = new()
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            HScrollEnabled = false,
            ReserveScrollbarSpace = true
        };

        _host = new()
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,

            Margin = new(0, 0, 0, 0)
        };

        _scroll.AddChild(_host);
        ScrollHost.AddChild(_scroll);

        if (preserved != null)
        {
            foreach (var c in preserved)
                _host.AddChild(c);
        }
    }
}
