using Content.Shared._Forge.Trade;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._Forge.Trade.Controls;


[GenerateTypedNameReferences]
public sealed partial class NcListingPriceButtonControl : Button
{
    private static readonly Color BuyBackground = Color.FromHex("#23170F");
    private static readonly Color BuyHoverBackground = Color.FromHex("#2B1D12");
    private static readonly Color BuyBorder = Color.FromHex("#8A6830");
    private static readonly Color BuyHoverBorder = Color.FromHex("#C1913D");

    private static readonly Color SellBackground = Color.FromHex("#132028");
    private static readonly Color SellHoverBackground = Color.FromHex("#172A34");
    private static readonly Color SellBorder = Color.FromHex("#3F7C91");
    private static readonly Color SellHoverBorder = Color.FromHex("#5CA6BF");

    private static readonly Color DisabledBackground = Color.FromHex("#1A1A1A");
    private static readonly Color DisabledBorder = Color.FromHex("#4A4A4A");

    private static readonly Color BuyText = Color.FromHex("#F0E0BE");
    private static readonly Color SellText = Color.FromHex("#D9F1F7");
    private static readonly Color DisabledText = Color.FromHex("#9B9B9B");

    private bool _hovered;
    private StoreMode _mode = StoreMode.Buy;

    public NcListingPriceButtonControl()
    {
        RobustXamlLoader.Load(this);

        Text = string.Empty;
        Label.Text = string.Empty;
        Label.Visible = false;

        PriceLabel.AddStyleClass("LabelHeading");
        UnitPriceLabel.Visible = false;

        OnMouseEntered += _ =>
        {
            _hovered = true;
            ApplyVisualState();
        };

        OnMouseExited += _ =>
        {
            _hovered = false;
            ApplyVisualState();
        };

        ApplyVisualState();
    }

    public void SetMode(StoreMode mode)
    {
        _mode = mode;
        ApplyVisualState();
    }

    public void SetCurrencyIcon(Texture? texture)
    {
        CurrencyIcon.Texture = texture;
        CurrencyIcon.Visible = texture != null;
    }

    public void SetPriceText(string text) => PriceLabel.Text = string.IsNullOrWhiteSpace(text) ? "0" : text;

    public void SetUnitPriceText(string text)
    {
        UnitPriceLabel.Visible = false;
        UnitPriceLabel.Text = string.Empty;
    }

    public void RefreshVisualState() => ApplyVisualState();

    private void ApplyVisualState()
    {
        var disabled = Disabled;

        Color background;
        Color border;
        Color textColor;

        if (disabled)
        {
            background = DisabledBackground;
            border = DisabledBorder;
            textColor = DisabledText;
        }
        else if (_mode == StoreMode.Sell)
        {
            background = _hovered ? SellHoverBackground : SellBackground;
            border = _hovered ? SellHoverBorder : SellBorder;
            textColor = SellText;
        }
        else if (_mode == StoreMode.Buy || _mode == StoreMode.Barter)
        {
            background = _hovered ? BuyHoverBackground : BuyBackground;
            border = _hovered ? BuyHoverBorder : BuyBorder;
            textColor = BuyText;
        }
        else
        {
            background = DisabledBackground;
            border = DisabledBorder;
            textColor = DisabledText;
        }

        var style = new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new(1)
        };

        style.SetContentMarginOverride(StyleBox.Margin.Left, 0);
        style.SetContentMarginOverride(StyleBox.Margin.Top, 0);
        style.SetContentMarginOverride(StyleBox.Margin.Right, 0);
        style.SetContentMarginOverride(StyleBox.Margin.Bottom, 0);

        StyleBoxOverride = style;
        ModulateSelfOverride = Color.White;

        Label.Visible = false;
        PriceLabel.FontColorOverride = textColor;
        CurrencyIcon.ModulateSelfOverride = disabled ? DisabledText : Color.White;
    }
}
