using Content.Shared._Forge.Trade;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._Forge.Trade.Controls;


[GenerateTypedNameReferences]
public sealed partial class NcListingStockInfoControl : BoxContainer
{
    public NcListingStockInfoControl()
    {
        RobustXamlLoader.Load(this);
    }

    public bool Update(StoreMode mode, int remaining, int owned)
    {
        if (mode == StoreMode.Buy)
        {
            var hasStock = remaining != 0;

            NoStockLabel.Visible = !hasStock;
            if (!hasStock)
                NoStockLabel.Text = Loc.GetString("nc-store-no-stock");

            if (hasStock && remaining >= 0)
            {
                RemainingLabel.Visible = true;
                RemainingLabel.Text = Loc.GetString("nc-store-in-stock", ("count", remaining));
            }
            else
                RemainingLabel.Visible = false;

            OwnedLabel.Visible = owned > 0;
            if (OwnedLabel.Visible)
                OwnedLabel.Text = Loc.GetString("nc-store-owned", ("count", owned));

            return hasStock;
        }

        if (mode == StoreMode.Barter)
        {
            var canBarter = owned > 0 && remaining != 0;
            NoStockLabel.Visible = !canBarter;
            if (!canBarter)
                NoStockLabel.Text = Loc.GetString("nc-store-barter-unavailable");

            RemainingLabel.Visible = canBarter && remaining >= 0;
            if (RemainingLabel.Visible)
                RemainingLabel.Text = Loc.GetString("nc-store-in-stock", ("count", remaining));

            OwnedLabel.Visible = owned > 0;
            if (OwnedLabel.Visible)
                OwnedLabel.Text = Loc.GetString("nc-store-barter-available", ("count", owned));

            return canBarter;
        }

        if (mode != StoreMode.Sell)
        {
            NoStockLabel.Visible = false;
            RemainingLabel.Visible = false;
            OwnedLabel.Visible = false;
            return false;
        }

        if (owned <= 0)
        {
            NoStockLabel.Visible = false;
            RemainingLabel.Visible = false;
            OwnedLabel.Visible = false;
            return false;
        }

        var hasDemand = remaining != 0;
        NoStockLabel.Visible = !hasDemand;
        if (!hasDemand)
            NoStockLabel.Text = Loc.GetString("nc-store-buying-finished");

        if (hasDemand && remaining >= 0)
        {
            RemainingLabel.Visible = true;
            RemainingLabel.Text = Loc.GetString("nc-store-will-buy", ("count", remaining));
        }
        else
            RemainingLabel.Visible = false;

        OwnedLabel.Visible = true;
        OwnedLabel.Text = Loc.GetString("nc-store-owned", ("count", owned));

        return hasDemand;
    }
}
