using System.Linq;
using Content.Shared._Forge.Trade;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._Forge.Trade.Controls;


[GenerateTypedNameReferences]
public sealed partial class NcListingQuantityControl : BoxContainer
{
    private const int QtyMaxDigits = 6;

    private static readonly Color ButtonBackground = Color.FromHex("#18130F");
    private static readonly Color ButtonDisabledBackground = Color.FromHex("#13110E");

    private static readonly Color BuyAccent = Color.FromHex("#6E5833");
    private static readonly Color SellAccent = Color.FromHex("#3F7C91");
    private static readonly Color DisabledAccent = Color.FromHex("#3E3429");

    private static readonly Color ValueFrameBackground = Color.FromHex("#17120E");
    private static readonly Color ValueFrameDisabledBackground = Color.FromHex("#12100D");

    private static readonly Color EditBackground = Color.FromHex("#0F1216");
    private static readonly Color EditDisabledBackground = Color.FromHex("#0D1013");

    private static readonly Color TextEnabled = Color.FromHex("#E3D6BF");
    private static readonly Color TextDisabled = Color.FromHex("#8F8578");

    private bool _enabled = true;
    private int _max;
    private int _min;
    private StoreMode _mode = StoreMode.Buy;
    private bool _suppressEditChange;

    public NcListingQuantityControl()
    {
        RobustXamlLoader.Load(this);

        MinusButton.OnPressed += _ =>
        {
            if (_enabled && Value > _min)
                SetValue(Value - 1);
        };

        PlusButton.OnPressed += _ =>
        {
            if (_enabled && Value < _max)
                SetValue(Value + 1);
        };

        QtyEdit.OnTextChanged += _ =>
        {
            if (!_enabled || _suppressEditChange)
                return;

            var digits = new string(QtyEdit.Text.Where(char.IsDigit).Take(QtyMaxDigits).ToArray());
            if (digits.Length == 0)
            {
                SetEditSafe(Value.ToString());
                return;
            }

            if (!int.TryParse(digits, out var v))
                v = Value;

            var clamped = Math.Clamp(v, _min, Math.Max(_min, _max));
            var newText = clamped.ToString();

            if (QtyEdit.Text != newText)
                SetEditSafe(newText);

            SetValue(clamped);
        };

        QtyEdit.OnTextEntered += _ =>
        {
            if (_enabled)
                OnEnter?.Invoke();
        };

        ApplyVisualState();
    }

    public LineEdit Edit => QtyEdit;
    public int Value { get; private set; }

    public event Action<int>? OnValueChanged;
    public event Action? OnEnter;

    public void SetMode(StoreMode mode)
    {
        _mode = mode;
        ApplyVisualState();
    }

    public void Configure(int minValue, int maxValue, int initialValue, bool enabled, string? disabledTooltip = null)
    {
        SetLimits(minValue, maxValue);
        SetEnabled(enabled, disabledTooltip);
        SetValue(initialValue, false);
    }

    public void SetLimits(int minValue, int maxValue)
    {
        _min = minValue;
        _max = Math.Max(minValue, maxValue);

        var clamped = Math.Clamp(Value, _min, _max);
        if (clamped != Value)
            SetValue(clamped);
        else
            UpdateButtonsState();
    }

    public void SetEnabled(bool enabled, string? disabledTooltip = null)
    {
        _enabled = enabled;
        MinusButton.Disabled = !enabled;
        PlusButton.Disabled = !enabled;
        QtyEdit.Editable = enabled;

        if (!enabled && disabledTooltip != null)
        {
            MinusButton.ToolTip = disabledTooltip;
            PlusButton.ToolTip = disabledTooltip;
            QtyEdit.ToolTip = disabledTooltip;
        }
        else
        {
            MinusButton.ToolTip = null;
            PlusButton.ToolTip = null;
            QtyEdit.ToolTip = null;
        }

        UpdateButtonsState();
        ApplyVisualState();
    }

    public void SetValue(int value, bool notify = true)
    {
        var clamped = Math.Clamp(value, _min, _max);

        if (clamped == Value && QtyEdit.Text == clamped.ToString())
        {
            UpdateButtonsState();
            ApplyVisualState();
            return;
        }

        Value = clamped;

        var text = Value.ToString();
        if (QtyEdit.Text != text)
            SetEditSafe(text);

        UpdateButtonsState();
        ApplyVisualState();

        if (notify)
            OnValueChanged?.Invoke(Value);
    }

    public bool IsEditing(IUserInterfaceManager ui) => ui.KeyboardFocused == QtyEdit;

    private void UpdateButtonsState()
    {
        var noQty = !_enabled || _max <= 0;
        MinusButton.Disabled = noQty || Value <= _min;
        PlusButton.Disabled = noQty || Value >= _max;
        QtyEdit.Editable = !noQty;
    }

    private void SetEditSafe(string text)
    {
        _suppressEditChange = true;
        QtyEdit.Text = text;
        QtyEdit.CursorPosition = QtyEdit.Text.Length;
        _suppressEditChange = false;
    }

    private void ApplyVisualState()
    {
        var accent = _mode == StoreMode.Sell ? SellAccent : BuyAccent;

        ApplyButtonStyle(MinusButton, accent);
        ApplyButtonStyle(PlusButton, accent);

        ValueFrame.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = QtyEdit.Editable ? ValueFrameBackground : ValueFrameDisabledBackground,
            BorderColor = QtyEdit.Editable ? accent : DisabledAccent,
            BorderThickness = new(1)
        };

        QtyEdit.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = QtyEdit.Editable ? EditBackground : EditDisabledBackground,
            BorderThickness = new(0)
        };

        QtyEdit.ModulateSelfOverride = QtyEdit.Editable ? TextEnabled : TextDisabled;
    }

    private static void ApplyButtonStyle(Button button, Color accent)
    {
        var disabled = button.Disabled;

        button.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = disabled ? ButtonDisabledBackground : ButtonBackground,
            BorderColor = disabled ? DisabledAccent : accent,
            BorderThickness = new(1)
        };

        button.ModulateSelfOverride = disabled ? TextDisabled : TextEnabled;
    }
}
