using Content.Client._Forge.Trade.Theme;
using Content.Client.Message;
using Content.Shared._Forge.Trade;
using Content.Shared.Stacks;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;


namespace Content.Client._Forge.Trade.Controls;


[GenerateTypedNameReferences]
public sealed partial class NcStoreHeaderBar : BoxContainer
{
    private const int DefaultSearchDebounceMs = 120;
    private const int CurrencyGroupSpacing = 14;
    private const int CurrencyIconSize = 24;

    private readonly List<CurrencyGroup> _balanceGroups = new();
    private readonly Dictionary<string, Texture> _currencyIconCache = new();
    private readonly List<(string Currency, int Amount)> _lastBalances = new();

    private int _activeGroupCount;
    private Color _balanceTextColor = Color.FromHex("#E4D8BC");

    private IPrototypeManager? _proto;
    private int _searchToken;
    private SpriteSystem? _sprites;

    public NcStoreHeaderBar()
    {
        RobustXamlLoader.Load(this);

        StoreTitle.AddStyleClass("LabelHeading");
        EmptyBalanceLabel.AddStyleClass("LabelHeading");

        SetStoreTitle(Loc.GetString("nc-store-window-title"));
        SearchIcon.Text = "\uD83D\uDD0D";
        SearchBar.PlaceHolder = Loc.GetString("nc-store-search-placeholder");

        SearchBar.MinWidth = 220;
        SearchBar.OnTextChanged += _ => HandleSearchTextChanged();

        ApplyUiTheme(new());
        ShowEmptyBalance();
    }

    public event Action<string>? OnSearchChanged;

    public void SetStoreTitle(string title) =>
        StoreTitle.Text = string.IsNullOrWhiteSpace(title)
            ? Loc.GetString("nc-store-window-title")
            : title;

    public void BindServices(IPrototypeManager proto, SpriteSystem sprites)
    {
        _proto = proto;
        _sprites = sprites;
        _currencyIconCache.Clear();
    }

    public void SetSearchText(string text) => SearchBar.Text = text;

    public string GetSearchText() => SearchBar.Text;

    public void SetBalances(IReadOnlyDictionary<string, int> balancesByCurrency)
    {
        _lastBalances.Clear();

        if (balancesByCurrency.Count == 0)
        {
            ShowEmptyBalance();
            return;
        }

        var ordered = new List<(string Currency, int Amount)>(balancesByCurrency.Count);

        foreach (var (cur, amt) in balancesByCurrency)
        {
            if (string.IsNullOrWhiteSpace(cur))
                continue;

            ordered.Add((cur, amt));
        }

        _lastBalances.AddRange(ordered);

        if (ordered.Count == 0)
        {
            ShowEmptyBalance();
            return;
        }

        EmptyBalanceLabel.Visible = false;
        ShowBalanceGroups(ordered);
    }

    public void ApplyUiTheme(StoreUiColorsData colors)
    {
        _balanceTextColor = NcStoreUiTheme.ResolveColor(colors.HeaderBalanceText, "#E4D8BC");
        EmptyBalanceLabel.FontColorOverride = _balanceTextColor;
        StoreTitle.FontColorOverride = NcStoreUiTheme.ResolveColor(colors.TabFontActive, "#E4D3AF");

        SearchShell.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = NcStoreUiTheme.ResolveColor(colors.SearchBoxBackground, "#232830"),
            BorderColor = NcStoreUiTheme.ResolveColor(colors.SearchBoxBorder, "#4C4438"),
            BorderThickness = new(1)
        };

        SearchBar.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = new(0f, 0f, 0f, 0f),
            BorderColor = new(0f, 0f, 0f, 0f),
            BorderThickness = new(0)
        };

        SearchBar.ModulateSelfOverride = NcStoreUiTheme.ResolveColor(colors.HeaderBalanceText, "#DDD5C7");
        SearchIcon.ModulateSelfOverride = NcStoreUiTheme.ResolveColor(colors.SearchIconColor, "#D6C9A9");

        if (_lastBalances.Count == 0)
            ShowEmptyBalance();
        else
            ShowBalanceGroups(_lastBalances);
    }

    private void ShowEmptyBalance()
    {
        HideAllBalanceGroups();
        EmptyBalanceLabel.Visible = true;
        EmptyBalanceLabel.Text = "0";
    }

    private void HideAllBalanceGroups()
    {
        for (var i = 0; i < _activeGroupCount; i++)
            _balanceGroups[i].Container.Visible = false;

        _activeGroupCount = 0;
    }

    private void ShowBalanceGroups(List<(string Currency, int Amount)> ordered)
    {
        EnsureBalanceGroupCount(ordered.Count);

        for (var i = 0; i < ordered.Count; i++)
        {
            var (cur, amt) = ordered[i];
            var group = _balanceGroups[i];

            group.Container.Visible = true;
            group.Container.Margin = i == ordered.Count - 1
                ? new(0, 0, 0, 0)
                : new Thickness(0, 0, CurrencyGroupSpacing, 0);

            group.Amount.SetMarkup($"[font size=14][color={ColorToHex(_balanceTextColor)}]{amt}[/color][/font]");
            SetCurrencyIconFor(group.Icon, cur);
        }

        for (var i = ordered.Count; i < _activeGroupCount; i++)
            _balanceGroups[i].Container.Visible = false;

        _activeGroupCount = ordered.Count;
    }

    private void EnsureBalanceGroupCount(int count)
    {
        while (_balanceGroups.Count < count)
        {
            var group = new CurrencyGroup();
            _balanceGroups.Add(group);
            BalancesHost.AddChild(group.Container);
        }
    }

    private void SetCurrencyIconFor(TextureRect target, string? currencyId)
    {
        if (string.IsNullOrWhiteSpace(currencyId) || _proto == null || _sprites == null)
        {
            target.Texture = null;
            return;
        }

        if (_currencyIconCache.TryGetValue(currencyId, out var cached))
        {
            target.Texture = cached;
            return;
        }

        if (_proto.TryIndex<StackPrototype>(currencyId, out var stackProto) &&
            _proto.TryIndex<EntityPrototype>(stackProto.Spawn, out var entProto))
        {
            var tex = _sprites.GetPrototypeIcon(entProto).Default;
            _currencyIconCache[currencyId] = tex;
            target.Texture = tex;
            return;
        }

        target.Texture = null;
    }

    private void HandleSearchTextChanged()
    {
        var token = ++_searchToken;
        var text = SearchBar.Text.Trim();

        Timer.Spawn(
            TimeSpan.FromMilliseconds(DefaultSearchDebounceMs),
            () =>
            {
                if (token != _searchToken)
                    return;

                OnSearchChanged?.Invoke(text);
            });
    }


    private static string ColorToHex(Color color)
    {
        var r = (byte) Math.Clamp((int) MathF.Round(color.R * 255f), 0, 255);
        var g = (byte) Math.Clamp((int) MathF.Round(color.G * 255f), 0, 255);
        var b = (byte) Math.Clamp((int) MathF.Round(color.B * 255f), 0, 255);
        return $"#{r:X2}{g:X2}{b:X2}";
    }

    private sealed class CurrencyGroup
    {
        public readonly RichTextLabel Amount;
        public readonly BoxContainer Container;
        public readonly TextureRect Icon;

        public CurrencyGroup()
        {
            Icon = new()
            {
                MinSize = new Vector2i(CurrencyIconSize, CurrencyIconSize),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                Margin = new(0, 0, 4, 0),
                VerticalAlignment = VAlignment.Center
            };

            Amount = new()
            {
                HorizontalExpand = false,
                VerticalAlignment = VAlignment.Center
            };
            Amount.AddStyleClass("LabelHeading");

            Container = new()
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = false,
                VerticalAlignment = VAlignment.Center,
                Margin = new(0, 0, CurrencyGroupSpacing, 0)
            };

            Container.AddChild(Icon);
            Container.AddChild(Amount);
        }
    }
}
