using Content.Client._Forge.Trade.Theme;
using Content.Shared._Forge.Trade;
using Content.Shared.Stacks;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;


namespace Content.Client._Forge.Trade.Controls;


[GenerateTypedNameReferences]
public sealed partial class NcStoreListingControl : PanelContainer
{
    private const int MaxTotalDisplay = 999_999;
    private const int DescMaxChars = 180;
    private const int MaxRewardPoolIconDepth = 6;

    private const float CompactSwitchFloor = 780f;
    private const float MinHorizontalDescriptionWidth = 360f;
    private const float HorizontalChromeWidth = 44f;
    private const float IconBlockWidth = 78f;
    private const float ActionColumnMinWidth = 160f;
    private const int ActionColumnRightPad = 6;

    private readonly bool _actionsEnabled;
    private readonly IPrototypeManager _prototypeManager;
    private readonly IUserInterfaceManager _ui = IoCManager.Resolve<IUserInterfaceManager>();

    private int _maxQty;
    private int _qty;
    private StoreListingData _staticData;

    public NcStoreListingControl(
        StoreListingData data,
        SpriteSystem sprites,
        IEntityManager entMan,
        int balanceHint = int.MaxValue,
        int initialQty = 1,
        bool actionsEnabled = true
    )
    {
        RobustXamlLoader.Load(this);
        ApplyUiTheme(new());

        _staticData = data;
        _actionsEnabled = actionsEnabled;

        _prototypeManager = IoCManager.Resolve<IPrototypeManager>();
        var pm = _prototypeManager;
        EntityPrototype? proto = null;
        if (data.MatchMode != PrototypeMatchMode.Tag)
            pm.TryIndex(data.ProductEntity, out proto);

        NcMatcherPrototype? matcher = null;
        EntityPrototype? matcherFallbackProto = null;
        NcTradeTagPrototype? tagTarget = null;
        EntityPrototype? tagIconProto = null;

        if (proto == null &&
            data.MatchMode == PrototypeMatchMode.Matcher &&
            pm.TryIndex<NcMatcherPrototype>(data.ProductEntity, out var foundMatcher))
        {
            matcher = foundMatcher;
            if (matcher.Items.Count > 0)
                pm.TryIndex(matcher.Items[0], out matcherFallbackProto);
        }
        else if (proto == null &&
            data.MatchMode == PrototypeMatchMode.Tag &&
            pm.TryIndex<NcTradeTagPrototype>(data.ProductEntity, out var foundTagTarget))
        {
            tagTarget = foundTagTarget;
            if (!string.IsNullOrWhiteSpace(tagTarget.Icon))
                pm.TryIndex(tagTarget.Icon, out tagIconProto);
        }

        var displayName = data.DisplayName;
        if (string.IsNullOrWhiteSpace(displayName))
            displayName = proto?.Name;
        if (string.IsNullOrWhiteSpace(displayName))
            displayName = matcher?.Name;
        if (string.IsNullOrWhiteSpace(displayName))
            displayName = tagTarget?.Name;
        if (string.IsNullOrWhiteSpace(displayName) && data.MatchMode == PrototypeMatchMode.Tag)
            displayName = data.ProductEntity;
        if (string.IsNullOrWhiteSpace(displayName))
            displayName = data.ProductEntity;
        if (string.IsNullOrWhiteSpace(displayName))
            displayName = data.ListingId;

        TitleLabel.Text = displayName;
        TitleLabel.ToolTip = displayName;

        if (data.Mode == StoreMode.Buy && data.UnitsPerPurchase > 1)
        {
            TitleLabel.Text = $"{TitleLabel.Text} x{data.UnitsPerPurchase}";
            TitleLabel.ToolTip = TitleLabel.Text;
        }


        if (proto != null)
        {
            MatcherIconView.Visible = false;
            MatcherIconView.Texture = null;
            IconView.Visible = true;
            IconView.SetPrototype(proto.ID);
            NcUiIconFit.Fit(IconView, sprites, proto.ID, 72, 6);
        }
        else if (matcher != null)
        {
            if (!TrySetMatcherIcon(matcher, matcherFallbackProto, sprites))
                IconSlotBackground.Visible = false;
        }
        else if (tagTarget != null)
        {
            if (!TrySetTradeTagIcon(tagTarget, tagIconProto, sprites))
                IconSlotBackground.Visible = false;
        }
        else
            IconSlotBackground.Visible = false;

        SetDescription(
            !string.IsNullOrWhiteSpace(data.Description)
                ? data.Description
                : proto?.Description ?? matcher?.Description ?? tagTarget?.Description);
        SetupBarterPreview(data, pm);

        SetupPriceButton(data, sprites, pm);

        SetupQtyLogic(data, balanceHint, initialQty);
        PriceButton.SetMode(data.Mode);
        QtyControl.SetMode(data.Mode);

        UpdateLabelsAndVisibility(data);

        QtyControl.HorizontalAlignment = HAlignment.Right;
        PriceButton.HorizontalAlignment = HAlignment.Right;
        StockInfo.HorizontalAlignment = HAlignment.Right;
        StockInfo.Margin = new(0, 0, 1, 0);

        ApplyResponsiveLayout();
    }

    public Action<int>? OnBarterPressed { get; set; }
    public Action<int>? OnBuyPressed { get; set; }
    public Action<int>? OnSellPressed { get; set; }
    public Action<int>? OnQtyChanged { get; set; }

    public string UiId => _staticData.Id;
    public string ListingId => _staticData.ListingId;
    public StoreListingFlavor Flavor => _staticData.Flavor;
    private int MinAllowed => _maxQty <= 0 ? 0 : 1;

    public void BindActions(
        Action<int>? onBarterPressed,
        Action<int>? onBuyPressed,
        Action<int>? onSellPressed,
        Action<int>? onQtyChanged
    )
    {
        OnBarterPressed = onBarterPressed;
        OnBuyPressed = onBuyPressed;
        OnSellPressed = onSellPressed;
        OnQtyChanged = onQtyChanged;
    }

    protected override void Resized()
    {
        base.Resized();
        ApplyResponsiveLayout();
    }

    private void ApplyResponsiveLayout()
    {
        var listingWidth = Size.X > 0 ? Size.X : DesiredSize.X;
        var actionWidth = CalculateActionColumnWidth();
        var iconWidth = IconSlotBackground.Visible ? IconBlockWidth : 0f;

        var minHorizontalWidth = MathF.Max(
            CompactSwitchFloor,
            iconWidth + actionWidth + MinHorizontalDescriptionWidth + HorizontalChromeWidth);

        var compact = listingWidth <= minHorizontalWidth;

        ContentRow.Orientation = compact
            ? BoxContainer.LayoutOrientation.Vertical
            : BoxContainer.LayoutOrientation.Horizontal;


        ActionColumn.RectClipContent = true;
        ActionColumn.HorizontalExpand = compact;
        ActionColumn.HorizontalAlignment = compact ? HAlignment.Stretch : HAlignment.Right;
        ActionColumn.Margin = compact ? new(0, 6, 2, 0) : new(6, 0, 2, 0);
        ActionColumn.MinWidth = compact ? 0f : actionWidth;
        ActionColumn.MaxWidth = compact ? float.PositiveInfinity : actionWidth;

        var descriptionMax = compact
            ? float.PositiveInfinity
            : MathF.Max(120f, listingWidth - iconWidth - actionWidth - HorizontalChromeWidth);

        BodyColumn.MaxWidth = descriptionMax;
        DescriptionBox.MaxWidth = descriptionMax;
        DescriptionBox.SetLayoutMaxWidth(descriptionMax);

        // Keep arrange/measure fresh after a fast drag-resize, so controls don't spill out.
        ActionColumn.InvalidateMeasure();
        DescriptionBox.InvalidateMeasure();
        ContentRow.InvalidateArrange();
    }

    private float CalculateActionColumnWidth()
    {
        var qtyWidth = QtyControl.DesiredSize.X;
        var priceWidth = PriceButton.DesiredSize.X;
        var stockWidth = StockInfo.DesiredSize.X;

        var desired = MathF.Max(ActionColumnMinWidth, MathF.Max(qtyWidth, MathF.Max(priceWidth, stockWidth)));
        return MathF.Ceiling(desired);
    }

    private bool TrySetMatcherIcon(NcMatcherPrototype matcher, EntityPrototype? fallbackProto, SpriteSystem sprites)
    {
        if (matcher.Sprite != null)
        {
            var texture = sprites.Frame0(matcher.Sprite);
            if (texture != null)
            {
                IconView.Visible = false;
                MatcherIconView.Texture = texture;
                MatcherIconView.Visible = true;
                return true;
            }
        }

        if (fallbackProto == null)
            return false;

        MatcherIconView.Visible = false;
        MatcherIconView.Texture = null;
        IconView.Visible = true;
        IconView.SetPrototype(fallbackProto.ID);
        NcUiIconFit.Fit(IconView, sprites, fallbackProto.ID, 72, 6);
        return true;
    }

    private bool TrySetTradeTagIcon(NcTradeTagPrototype tagTarget, EntityPrototype? fallbackProto, SpriteSystem sprites)
    {
        if (tagTarget.Sprite != null)
        {
            var texture = sprites.Frame0(tagTarget.Sprite);
            if (texture != null)
            {
                IconView.Visible = false;
                MatcherIconView.Texture = texture;
                MatcherIconView.Visible = true;
                return true;
            }
        }

        if (fallbackProto == null)
            return false;

        MatcherIconView.Visible = false;
        MatcherIconView.Texture = null;
        IconView.Visible = true;
        IconView.SetPrototype(fallbackProto.ID);
        NcUiIconFit.Fit(IconView, sprites, fallbackProto.ID, 72, 6);
        return true;
    }

    private void SetDescription(string? description) => DescriptionBox.SetDescription(description, DescMaxChars);


    private void SetupPriceButton(StoreListingData data, SpriteSystem sprites, IPrototypeManager pm)
    {
        if (data.Mode != StoreMode.Barter &&
            !string.IsNullOrEmpty(data.CurrencyId) &&
            pm.TryIndex<StackPrototype>(data.CurrencyId, out var stack) &&
            pm.TryIndex<EntityPrototype>(stack.Spawn, out var ent) &&
            sprites.GetPrototypeIcon(ent.ID).Default is { } currencyTex)
            PriceButton.SetCurrencyIcon(currencyTex);
        else
            PriceButton.SetCurrencyIcon(null);

        if (!_actionsEnabled)
            PriceButton.ToolTip = Loc.GetString("nc-store-only-mass-sell");
        else
            PriceButton.ToolTip = null;

        PriceButton.OnPressed += _ =>
        {
            if (!_actionsEnabled || _maxQty <= 0 || _qty <= 0)
                return;

            switch (data.Mode)
            {
                case StoreMode.Buy:
                    OnBuyPressed?.Invoke(_qty);
                    break;
                case StoreMode.Sell:
                    OnSellPressed?.Invoke(_qty);
                    break;
                case StoreMode.Barter:
                    OnBarterPressed?.Invoke(_qty);
                    break;
            }
        };
    }

    private void SetupQtyLogic(StoreListingData data, int balanceHint, int initialQty)
    {
        CalculateMaxQty(data, balanceHint);
        _qty = Math.Clamp(initialQty, MinAllowed, Math.Max(MinAllowed, _maxQty));

        var noQty = _maxQty <= 0 || !_actionsEnabled;
        var disabledTip = !_actionsEnabled ? Loc.GetString("nc-store-only-mass-sell") : null;

        QtyControl.Configure(MinAllowed, _maxQty, _qty, !noQty, disabledTip);

        QtyControl.OnValueChanged += v =>
        {
            _qty = v;
            UpdatePriceAndButtons();
            SetupBarterPreview(_staticData, _prototypeManager);
            OnQtyChanged?.Invoke(_qty);
        };

        QtyControl.OnEnter += () =>
        {
            if (!_actionsEnabled || _maxQty <= 0 || _qty <= 0)
                return;

            if (data.Mode == StoreMode.Buy)
                OnBuyPressed?.Invoke(_qty);
            else if (data.Mode == StoreMode.Sell)
                OnSellPressed?.Invoke(_qty);
            else if (data.Mode == StoreMode.Barter)
                OnBarterPressed?.Invoke(_qty);
        };
    }

    private void CalculateMaxQty(StoreListingData data, int balanceHint)
    {
        var remainingCap = data.Mode is StoreMode.Buy or StoreMode.Barter
            ? data.Remaining >= 0 ? data.Remaining : int.MaxValue
            : int.MaxValue;

        var ownedCap = data.Mode is StoreMode.Sell or StoreMode.Barter
            ? Math.Max(0, data.Owned)
            : int.MaxValue;

        var moneyCap = data.Mode == StoreMode.Buy && data.Price > 0
            ? balanceHint / data.Price
            : int.MaxValue;

        _maxQty = Math.Max(0, Math.Min(remainingCap, Math.Min(ownedCap, moneyCap)));
    }

    public void UpdateIdentity(StoreListingData newData) => _staticData = newData;

    public void UpdateDynamicData(int playerBalance, int remainingStock, int playerOwned)
    {
        _staticData.Remaining = remainingStock;
        _staticData.Owned = playerOwned;

        CalculateMaxQty(_staticData, playerBalance);

        var minAllowed = _maxQty <= 0 ? 0 : 1;
        var clamped = Math.Clamp(_qty, minAllowed, Math.Max(minAllowed, _maxQty));

        // Update limits first so the picker can clamp itself.
        var noQty = _maxQty <= 0 || !_actionsEnabled;
        var disabledTip = !_actionsEnabled ? Loc.GetString("nc-store-only-mass-sell") : null;
        QtyControl.SetLimits(minAllowed, _maxQty);
        QtyControl.SetEnabled(!noQty, disabledTip);

        if (clamped != _qty)
        {
            _qty = clamped;
            if (!QtyControl.IsEditing(_ui))
                QtyControl.SetValue(_qty, false);
            OnQtyChanged?.Invoke(_qty);
        }

        UpdatePriceAndButtons();
        SetupBarterPreview(_staticData, _prototypeManager);
        UpdateLabelsAndVisibility(_staticData);
        ApplyResponsiveLayout();
    }

    private void UpdatePriceAndButtons()
    {
        var noQty = _maxQty <= 0 || !_actionsEnabled;

        var disablePrice =
            !_actionsEnabled ||
            _staticData.Mode == StoreMode.Buy && (_staticData.Remaining == 0 || noQty) ||
            _staticData.Mode == StoreMode.Sell && _staticData.Owned <= 0 ||
            _staticData.Mode == StoreMode.Barter && (_staticData.Remaining == 0 || _staticData.Owned <= 0);

        PriceButton.Disabled = disablePrice;
        PriceButton.RefreshVisualState();

        UpdateTotalPrice(_staticData);
    }

    private void UpdateLabelsAndVisibility(StoreListingData data)
    {
        _ = StockInfo.Update(data.Mode, data.Remaining, data.Owned);

        PriceButton.Visible = true;
        UpdateTotalPrice(data);
    }

    private void UpdateTotalPrice(StoreListingData data)
    {
        if (data.Mode == StoreMode.Barter)
        {
            PriceButton.SetPriceText(Loc.GetString("nc-store-barter-button"));
            PriceButton.SetUnitPriceText(string.Empty);
            return;
        }

        var effectiveQty = _qty > 0 ? _qty : 1;
        var total = (long) data.Price * effectiveQty;

        PriceButton.SetPriceText(FormatCompactPrice(total));
        PriceButton.SetUnitPriceText(string.Empty);
    }


    private void SetupBarterPreview(StoreListingData data, IPrototypeManager pm)
    {
        if (data.Mode != StoreMode.Barter)
        {
            BarterPreview.Clear();
            return;
        }

        var multiplier = Math.Max(1, _qty);

        var costText = FormatBarterCost(data.BarterCost, pm, multiplier);
        var receiveText = FormatBarterReceive(data.BarterReceive, data.BarterReceivePools, pm, multiplier);

        BarterPreview.SetPreview(
            costText,
            receiveText,
            ResolveCostIconPrototype(data.BarterCost, pm),
            ResolveReceiveIconPrototype(data.BarterReceive, data.BarterReceivePools, pm));
    }

    private static string FormatBarterCost(List<NcBarterCostEntry> entries, IPrototypeManager pm, int multiplier)
    {
        if (entries.Count == 0)
            return string.Empty;

        var parts = new List<string>(entries.Count);
        for (var i = 0; i < entries.Count; i++)
        {
            var entry = entries[i];
            var name = ResolveCostName(entry, pm);
            if (string.IsNullOrWhiteSpace(name))
                continue;

            parts.Add(FormatAmountName(ScaleAmount(entry.Count, multiplier), name));
        }

        return string.Join(", ", parts);
    }

    private static string FormatBarterReceive(
        List<NcBarterReceiveEntry> entries,
        List<NcBarterReceivePoolEntry> pools,
        IPrototypeManager pm,
        int multiplier
    )
    {
        if (entries.Count == 0 && pools.Count == 0)
            return string.Empty;

        var parts = new List<string>(entries.Count + pools.Count);
        for (var i = 0; i < entries.Count; i++)
        {
            var entry = entries[i];
            var name = ResolveReceiveName(entry, pm);
            if (string.IsNullOrWhiteSpace(name))
                continue;

            parts.Add(FormatAmountName(ScaleAmount(entry.Count, multiplier), name));
        }

        for (var i = 0; i < pools.Count; i++)
        {
            var pool = pools[i];
            var rolls = ScaleAmount(Math.Max(1, pool.Rolls.Max), multiplier);
            var text = Loc.GetString("nc-store-barter-random-receive");
            parts.Add(FormatAmountName(rolls, text));
        }

        return string.Join(", ", parts);
    }

    private static int ScaleAmount(int count, int multiplier)
    {
        var amount = Math.Max(1, count);
        var qty = Math.Max(1, multiplier);
        var scaled = (long) amount * qty;

        return scaled > int.MaxValue
            ? int.MaxValue
            : (int) scaled;
    }

    private static string FormatAmountName(int count, string name)
    {
        var amount = Math.Max(1, count);
        return amount == 1 ? name : $"{amount}× {name}";
    }

    private static string ResolveCostName(NcBarterCostEntry entry, IPrototypeManager pm)
    {
        if (!string.IsNullOrWhiteSpace(entry.Prototype))
            return ResolveEntityName(entry.Prototype, pm);

        if (!string.IsNullOrWhiteSpace(entry.Group))
        {
            if (pm.TryIndex<NcItemGroupPrototype>(entry.Group, out var group))
                return !string.IsNullOrWhiteSpace(group.Name) ? group.Name : group.ID;

            return entry.Group;
        }

        if (!string.IsNullOrWhiteSpace(entry.TagTarget))
        {
            if (pm.TryIndex<NcTradeTagPrototype>(entry.TagTarget, out var tagTarget))
                return !string.IsNullOrWhiteSpace(tagTarget.Name) ? tagTarget.Name : tagTarget.ID;

            return entry.TagTarget;
        }

        if (!string.IsNullOrWhiteSpace(entry.Currency))
            return ResolveCurrencyName(entry.Currency, pm);

        return string.Empty;
    }

    private static string ResolveReceiveName(NcBarterReceiveEntry entry, IPrototypeManager pm)
    {
        if (!string.IsNullOrWhiteSpace(entry.Prototype))
            return ResolveEntityName(entry.Prototype, pm);

        if (!string.IsNullOrWhiteSpace(entry.Currency))
            return ResolveCurrencyName(entry.Currency, pm);

        return string.Empty;
    }

    private static string ResolveEntityName(string prototype, IPrototypeManager pm) =>
        pm.TryIndex<EntityPrototype>(prototype, out var entity)
            ? entity.Name
            : prototype;

    private static string ResolveCurrencyName(string currency, IPrototypeManager pm)
    {
        if (pm.TryIndex<StackPrototype>(currency, out var stack) &&
            pm.TryIndex<EntityPrototype>(stack.Spawn, out var entity))
            return entity.Name;

        return currency;
    }

    private static string? ResolveCostIconPrototype(List<NcBarterCostEntry> entries, IPrototypeManager pm)
    {
        for (var i = 0; i < entries.Count; i++)
        {
            var entry = entries[i];

            if (!string.IsNullOrWhiteSpace(entry.Prototype))
                return entry.Prototype;

            if (!string.IsNullOrWhiteSpace(entry.Group) &&
                pm.TryIndex<NcItemGroupPrototype>(entry.Group, out var group))
            {
                if (!string.IsNullOrWhiteSpace(group.Icon))
                    return group.Icon;

                if (group.Prototypes.Count > 0 && !string.IsNullOrWhiteSpace(group.Prototypes[0]))
                    return group.Prototypes[0];
            }

            if (!string.IsNullOrWhiteSpace(entry.TagTarget) &&
                pm.TryIndex<NcTradeTagPrototype>(entry.TagTarget, out var tagTarget) &&
                !string.IsNullOrWhiteSpace(tagTarget.Icon))
                return tagTarget.Icon;

            if (!string.IsNullOrWhiteSpace(entry.Currency) &&
                TryResolveCurrencyEntity(entry.Currency, pm, out var currencyEntity))
                return currencyEntity;
        }

        return null;
    }

    private static string? ResolveReceiveIconPrototype(
        List<NcBarterReceiveEntry> entries,
        List<NcBarterReceivePoolEntry> pools,
        IPrototypeManager pm
    )
    {
        for (var i = 0; i < entries.Count; i++)
        {
            var entry = entries[i];

            if (!string.IsNullOrWhiteSpace(entry.Prototype))
                return entry.Prototype;

            if (!string.IsNullOrWhiteSpace(entry.Currency) &&
                TryResolveCurrencyEntity(entry.Currency, pm, out var currencyEntity))
                return currencyEntity;
        }

        for (var i = 0; i < pools.Count; i++)
            if (TryResolveRewardPoolIcon(pools[i].Pool, pm, out var poolIcon))
                return poolIcon;

        return null;
    }

    private static bool TryResolveRewardPoolIcon(string poolId, IPrototypeManager pm, out string icon) =>
        TryResolveRewardPoolIcon(poolId, pm, out icon, new(StringComparer.Ordinal), 0);

    private static bool TryResolveRewardPoolIcon(
        string poolId,
        IPrototypeManager pm,
        out string icon,
        HashSet<string> visited,
        int depth
    )
    {
        icon = string.Empty;
        if (string.IsNullOrWhiteSpace(poolId) ||
            depth > MaxRewardPoolIconDepth ||
            !visited.Add(poolId))
            return false;

        if (pm.TryIndex<NcSupplyRewardPoolPrototype>(poolId, out var supplyPool))
        {
            for (var i = 0; i < supplyPool.Entries.Count; i++)
            {
                var reward = supplyPool.Entries[i];

                if (reward.Type == StoreRewardType.Item &&
                    !string.IsNullOrWhiteSpace(reward.Prototype) &&
                    pm.HasIndex<EntityPrototype>(reward.Prototype))
                {
                    icon = reward.Prototype;
                    visited.Remove(poolId);
                    return true;
                }

                if (reward.Type == StoreRewardType.Currency &&
                    !string.IsNullOrWhiteSpace(reward.Currency) &&
                    TryResolveCurrencyEntity(reward.Currency, pm, out icon))
                {
                    visited.Remove(poolId);
                    return true;
                }

                if (reward.Type == StoreRewardType.Pool &&
                    !string.IsNullOrWhiteSpace(reward.Pool) &&
                    TryResolveRewardPoolIcon(reward.Pool, pm, out icon, visited, depth + 1))
                {
                    visited.Remove(poolId);
                    return true;
                }
            }
        }

        visited.Remove(poolId);
        return false;
    }

    private static bool TryResolveCurrencyEntity(string currency, IPrototypeManager pm, out string entity)
    {
        entity = string.Empty;

        if (!pm.TryIndex<StackPrototype>(currency, out var stack) ||
            string.IsNullOrWhiteSpace(stack.Spawn))
            return false;

        entity = stack.Spawn;
        return true;
    }

    public void ApplyUiTheme(StoreUiColorsData colors)
    {
        var cardBackground = NcStoreUiTheme.ResolveColor(colors.ListingCardBackground, "#181C22");
        var rawCardBorder = NcStoreUiTheme.ResolveColor(colors.ListingCardBorder, "#3D4652");
        var dividerColor = NcStoreUiTheme.ResolveColor(colors.ListingDivider, "#323944");
        var titleColor = NcStoreUiTheme.ResolveColor(colors.ListingTitleColor, "#E2D4B5");

        // The listing border should support the card, not compete with the category/header lines.
        // Blend it toward the card background to keep one visual hierarchy instead of another hard frame.
        var cardBorder = NcStoreUiTheme.Blend(rawCardBorder, cardBackground, 0.35f);

        var frame = NcStoreUiTheme.Flat(cardBackground, cardBorder);
        frame.SetContentMarginOverride(StyleBox.Margin.Left, 9);
        frame.SetContentMarginOverride(StyleBox.Margin.Top, 7);
        frame.SetContentMarginOverride(StyleBox.Margin.Right, 9);
        frame.SetContentMarginOverride(StyleBox.Margin.Bottom, 7);
        PanelOverride = frame;

        IconSlotBackground.PanelOverride = NcStoreUiTheme.Fill(new(0f, 0f, 0f, 0f));

        TitleLabel.ModulateSelfOverride = titleColor;
    }

    private static string FormatCompactPrice(long value)
    {
        if (value >= 1_000_000_000)
            return $"{value / 1_000_000_000d:0.#}B";

        if (value >= 1_000_000)
            return $"{value / 1_000_000d:0.#}M";

        return value.ToString();
    }
}
