using System.Linq;
using System.Numerics;
using Content.Client.Shuttles.Systems;
using Content.Shared._Mono.Detection;
using Content.Shared._NF.Shuttles.Components;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Content.Shared.Shuttles.Systems;
using Content.Shared.Shuttles.UI.MapObjects;
using Content.Shared.Timing;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Audio.Systems;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Physics.Components;
using Robust.Shared.Player;
using Robust.Shared.Random;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class MapScreen : BoxContainer
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IMapManager _mapManager = default!;
    [Dependency] private IRobustRandom _random = default!;
    private readonly DetectionSystem _detection; // Mono
    private readonly SharedAudioSystem _audio;
    private readonly SharedMapSystem _maps;
    private readonly ShuttleSystem _shuttles;
    private readonly SharedTransformSystem _xformSystem;

    private EntityUid? _console;
    private EntityUid? _shuttleEntity;

    private FTLState _state;
    private StartEndTime _ftlTime;

    private List<ShuttleBeaconObject> _beacons = new();
    private List<ShuttleExclusionObject> _exclusions = new();

    private TimeSpan _nextPing;
    private TimeSpan _pingCooldown = TimeSpan.FromSeconds(3);
    private TimeSpan _nextMapDequeue;

    // Mono
    private bool _autopilotTargeting = false;
    private bool _bioScanTargeting = false; // Forge-Change - BioScan
    private StartEndTime _bioScanTime; // Forge-Change - BioScan
    private ShuttleBioScanStatus _bioScanStatus = ShuttleBioScanStatus.None; // Forge-Change - BioScan

    private float _minMapDequeue = 0.05f;
    private float _maxMapDequeue = 0.25f;

    // Forge-Change-Start
    private string _iffSearchFilter = "";
    private readonly Dictionary<MapId, Collapsible> _mapSectorCollapsibles = new();
    private readonly Dictionary<MapId, string> _mapSectorNames = new();
    // Forge-Change-End

    private StyleBoxFlat _ftlStyle;

    public event Action<MapCoordinates, Angle>? RequestFTL;
    public event Action<NetEntity, Angle>? RequestBeaconFTL;

    // Mono
    public event Action<MapCoordinates, Angle>? RequestAutopilot;
    public event Action<MapCoordinates>? RequestBioScan; // Forge-Change - BioScan

    private readonly Dictionary<MapId, BoxContainer> _mapHeadings = new();
    private readonly Dictionary<MapId, List<IMapObject>> _mapObjects = new();
    private readonly List<(MapId mapId, IMapObject mapobj)> _pendingMapObjects = new();

    /// <summary>
    /// Store the names of map object controls for re-sorting later.
    /// </summary>
    private Dictionary<Control, string> _mapObjectControls = new();

    private List<Control> _sortChildren = new();

    public MapScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _detection = _entManager.System<DetectionSystem>(); // Mono
        _audio = _entManager.System<SharedAudioSystem>();
        _maps = _entManager.System<SharedMapSystem>();
        _shuttles = _entManager.System<ShuttleSystem>();
        _xformSystem = _entManager.System<SharedTransformSystem>();

        MapRebuildButton.OnPressed += MapRebuildPressed;

        OnVisibilityChanged += OnVisChange;

        MapFTLButton.OnToggled += FtlPreviewToggled;
        MapAutopilotButton.OnToggled += AutopilotPreviewToggled; // Mono
        MapBioScanButton.OnToggled += BioScanPreviewToggled; // Forge-Change - BioScan

        _ftlStyle = new StyleBoxFlat(Color.LimeGreen);
        FTLBar.ForegroundStyleBoxOverride = _ftlStyle;

        // Just pass it on up.
        MapRadar.RequestFTL += (coords, angle) =>
        {
            if (_bioScanTargeting)
            {
                RequestBioScan?.Invoke(coords); // Forge-Change - BioScan
                SetTargeting(MapTargetingMode.None); // Forge-Change - BioScan
            }
            else if (_autopilotTargeting) // Mono
            {
                RequestAutopilot?.Invoke(coords, angle);
                SetTargeting(MapTargetingMode.None); // Forge-Change - BioScan
            }
            else
            {
                RequestFTL?.Invoke(coords, angle);
            }
        };

        MapRadar.RequestBeaconFTL += (ent, angle) =>
        {
            RequestBeaconFTL?.Invoke(ent, angle);
        };

        MapBeaconsButton.OnToggled += args =>
        {
            MapRadar.ShowBeacons = args.Pressed;
        };

        // Forge-Change-Start
        MapIffSearchCriteria.PlaceHolder = Loc.GetString("shuttle-console-map-search-placeholder");
        MapIffSearchCriteria.OnTextChanged += args => OnMapIffSearchChanged(args.Text);
        MapIffSearchCriteria.OnTextEntered += _ => GoToFirstSearchMatch();
        // Forge-Change-End
    }

    public void UpdateState(ShuttleMapInterfaceState state)
    {
        // Only network the accumulator due to ping making the thing fonky.
        // This should work better with predicting network states as they come in.
        if (state.IncludeBeaconExclusionLists)
        {
            _beacons = state.Destinations;
            _exclusions = state.Exclusions;
        }
        _state = state.FTLState;
        _ftlTime = state.FTLTime;
        _bioScanTime = state.BioScanTime; // Forge-Change - BioScan
        _bioScanStatus = state.BioScanStatus; // Forge-Change - BioScan
        MapRadar.InFtl = true;
        MapFTLState.Text = Loc.GetString($"shuttle-console-ftl-state-{_state.ToString()}");
        MapBioScanState.Text = Loc.GetString($"shuttle-console-bioscan-status-{_bioScanStatus.ToString()}"); // Forge-Change - BioScan
        MapBioScanButton.Disabled = _bioScanStatus == ShuttleBioScanStatus.InProgress || !state.BioScanAvailable; // Forge-Change - BioScan

        //frontier - we only allow pre-approved vessels to FTL
        if (!_entManager.HasComponent<ShuttleFTLComponent>(_shuttleEntity))
        {
            MapFTLButton.Visible = true;
        }
        else
        {
            MapFTLButton.Visible = true;
        }

        switch (_state)
        {
            case FTLState.Available:
                SetFTLAllowed(true);
                _ftlStyle.BackgroundColor = Color.FromHex("#80C71F");
                MapRadar.InFtl = false;
                break;
            case FTLState.Starting:
                SetFTLAllowed(false);
                _ftlStyle.BackgroundColor = Color.FromHex("#169C9C");
                break;
            case FTLState.Travelling:
                SetFTLAllowed(false);
                _ftlStyle.BackgroundColor = Color.FromHex("#8932B8");
                break;
            case FTLState.Arriving:
                SetFTLAllowed(false);
                _ftlStyle.BackgroundColor = Color.FromHex("#F9801D");
                break;
            case FTLState.Cooldown:
                SetFTLAllowed(false);
                // Scroll to the FTL spot
                if (_entManager.TryGetComponent(_shuttleEntity, out TransformComponent? shuttleXform))
                {
                    var targetOffset = _maps.GetGridPosition(_shuttleEntity.Value);
                    MapRadar.SetMap(shuttleXform.MapID, targetOffset, recentering: true);
                }

                _ftlStyle.BackgroundColor = Color.FromHex("#B02E26");
                MapRadar.InFtl = false;
                break;
            // Fallback in case no FTL state or the likes.
            default:
                SetFTLAllowed(false);
                _ftlStyle.BackgroundColor = Color.FromHex("#B02E26");
                MapRadar.InFtl = false;
                break;
        }

        if (IsFTLBlocked())
        {
            MapRebuildButton.Disabled = true;
            ClearMapObjects();
        }
    }

    private void SetFTLAllowed(bool value)
    {
        if (value)
        {
            MapFTLButton.Disabled = false;
        }
        else
        {
            // Unselect FTL
            MapFTLButton.Pressed = false;
            MapRadar.FtlMode = false;
            MapRadar.ShowFTLRangeOnly = false;
            MapFTLButton.Disabled = true;
        }
    }

    private void FtlPreviewToggled(BaseButton.ButtonToggledEventArgs obj)
    {
        SetTargeting(obj.Pressed ? MapTargetingMode.Ftl : MapTargetingMode.None); // Forge-Change - BioScan
    }

    // Mono
    private void AutopilotPreviewToggled(BaseButton.ButtonToggledEventArgs obj)
    {
        SetTargeting(obj.Pressed ? MapTargetingMode.Autopilot : MapTargetingMode.None); // Forge-Change
    }

    // Forge-Change-Start
    private void OnMapIffSearchChanged(string text)
    {
        _iffSearchFilter = text.Trim();
        ApplyMapIffFilter();
    }

    private static bool MapNameMatches(string name, string filter)
    {
        if (string.IsNullOrEmpty(filter))
            return true;

        if (name.Contains(filter, StringComparison.OrdinalIgnoreCase))
            return true;

        foreach (var line in name.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            if (line.Contains(filter, StringComparison.OrdinalIgnoreCase))
                return true;
        }

        return false;
    }

    private bool RowMatchesFilter(MapId mapId, string rowName)
    {
        if (string.IsNullOrEmpty(_iffSearchFilter))
            return true;

        if (MapNameMatches(rowName, _iffSearchFilter))
            return true;

        if (_mapSectorNames.TryGetValue(mapId, out var sectorName) && MapNameMatches(sectorName, _iffSearchFilter))
            return true;

        return false;
    }

    private void ApplyMapIffFilter()
    {
        foreach (var (mapId, gridContents) in _mapHeadings)
        {
            foreach (var child in gridContents.Children)
            {
                if (_mapObjectControls.TryGetValue(child, out var rowName))
                    child.Visible = RowMatchesFilter(mapId, rowName);
            }

            var anyChild = false;
            foreach (var child in gridContents.Children)
            {
                if (child.Visible)
                {
                    anyChild = true;
                    break;
                }
            }

            if (_mapSectorCollapsibles.TryGetValue(mapId, out var col))
                col.Visible = string.IsNullOrEmpty(_iffSearchFilter) || anyChild;
        }
    }

    private void GoToFirstSearchMatch()
    {
        var filter = _iffSearchFilter;
        if (string.IsNullOrEmpty(filter) || _shuttleEntity == null)
            return;

        var shuttlePos = _xformSystem.GetWorldPosition(_shuttleEntity.Value);
        IMapObject? best = null;
        MapId bestMap = default;
        var bestDist = float.MaxValue;

        foreach (var (mapId, list) in _mapObjects)
        {
            var sectorMatch = _mapSectorNames.TryGetValue(mapId, out var sectorName) && MapNameMatches(sectorName, filter);

            foreach (var obj in list)
            {
                if (!MapNameMatches(obj.Name, filter) && !sectorMatch)
                    continue;

                var pos = _shuttles.GetMapCoordinates(obj).Position;
                var d = (pos - shuttlePos).Length();
                if (d < bestDist)
                {
                    bestDist = d;
                    best = obj;
                    bestMap = mapId;
                }
            }
        }

        if (best == null)
            return;

        if (_mapSectorCollapsibles.TryGetValue(bestMap, out var sectorCol))
        {
            HideOtherCollapsibles(sectorCol);
            sectorCol.BodyVisible = true;
        }

        if (IsFTLBlocked())
            return;

        var coordinates = _shuttles.GetMapCoordinates(best);
        MapRadar.SetMap(coordinates.MapId, coordinates.Position, recentering: true);
    }
    // Forge-Change-End

    // Forge-Change-start - BioScan
    private void BioScanPreviewToggled(BaseButton.ButtonToggledEventArgs obj)
    {
        SetTargeting(obj.Pressed ? MapTargetingMode.BioScan : MapTargetingMode.None);
    }

    private enum MapTargetingMode : byte
    {
        None,
        Ftl,
        Autopilot,
        BioScan,
    }

    private void SetTargeting(MapTargetingMode mode)
    {
        if (mode != MapTargetingMode.None)
        {
            MapRadar.FtlMode = true;
            MapRadar.ShowFTLRangeOnly = false;
            MapRadar.ShowFTLRange = mode == MapTargetingMode.Ftl;
            MapRadar.NoFTLRange = mode != MapTargetingMode.Ftl;
            MapFTLButton.Pressed = mode == MapTargetingMode.Ftl;
            MapAutopilotButton.Pressed = mode == MapTargetingMode.Autopilot;
            MapBioScanButton.Pressed = mode == MapTargetingMode.BioScan;
            _autopilotTargeting = mode == MapTargetingMode.Autopilot;
            _bioScanTargeting = mode == MapTargetingMode.BioScan;
        }
        else
        {
            MapRadar.FtlMode = false;
            MapFTLButton.Pressed = false;
            MapAutopilotButton.Pressed = false;
            MapBioScanButton.Pressed = false;
            _autopilotTargeting = false;
            _bioScanTargeting = false;
        }
    }
    // Forge-Change-end - BioScan
    public void SetConsole(EntityUid? console)
    {
        _console = console;
        MapRadar.SetConsole(console); // Mono
    }

    public void SetShuttle(EntityUid? shuttle)
    {
        _shuttleEntity = shuttle;
        MapRadar.SetShuttle(shuttle);
    }

    private void OnVisChange(Control obj)
    {
        if (!obj.Visible)
            return;

        // Centre map screen to the shuttle.
        if (_shuttleEntity != null)
        {
            var mapPos = _xformSystem.GetMapCoordinates(_shuttleEntity.Value);
            MapRadar.SetMap(mapPos.MapId, mapPos.Position);
        }
    }

    /// <summary>
    /// Does a sonar-like effect on the map.
    /// </summary>
    public void PingMap()
    {
        if (_console != null)
        {
            _audio.PlayEntity(new SoundPathSpecifier("/Audio/Effects/Shuttle/radar_ping.ogg"), Filter.Local(), _console.Value, true);
        }

        RebuildMapObjects();

        // Immediately add all objects to the map instead of queueing them
        foreach (var mapObj in _pendingMapObjects)
        {
            AddMapObject(mapObj.mapId, mapObj.mapobj);
        }
        _pendingMapObjects.Clear();

        ApplyMapIffFilter();

        _nextPing = _timing.CurTime + _pingCooldown;
        MapRebuildButton.Disabled = true;
    }

    private void BumpMapDequeue()
    {
        _nextMapDequeue = _timing.CurTime + TimeSpan.FromSeconds(_random.NextFloat(_minMapDequeue, _maxMapDequeue));
    }

    private void MapRebuildPressed(BaseButton.ButtonEventArgs obj)
    {
        MapRadar.ShowFTLRangeOnly = true;
        PingMap();

        // Reset range back after map pinging is complete.
        MapRadar.ShowFTLRangeOnly = !MapFTLButton.Pressed;
    }

    /// <summary>
    /// Clears all sector objects across all maps (e.g. if we start FTLing or need to re-ping).
    /// </summary>
    private void ClearMapObjects()
    {
        _mapObjectControls.Clear();
        _mapSectorCollapsibles.Clear();
        _mapSectorNames.Clear();
        HyperspaceDestinations.DisposeAllChildren();
        _pendingMapObjects.Clear();
        _mapObjects.Clear();
        _mapHeadings.Clear();
    }

    /// <summary>
    /// Gets all map objects at time of ping and adds them to pending to be added over time.
    /// </summary>
    private void RebuildMapObjects()
    {
        ClearMapObjects();

        if (_shuttleEntity == null)
            return;

        var mapComps = _entManager.AllEntityQueryEnumerator<MapComponent, TransformComponent, MetaDataComponent>();
        MapId ourMap = MapId.Nullspace;

        if (_entManager.TryGetComponent(_shuttleEntity, out TransformComponent? shuttleXform))
        {
            ourMap = shuttleXform.MapID;
        }

        while (mapComps.MoveNext(out var mapUid, out var mapComp, out var mapXform, out var mapMetadata))
        {
            if (_console != null && !_shuttles.CanFTLTo(_shuttleEntity.Value, mapComp.MapId, _console.Value))
            {
                continue;
            }
            var mapName = mapMetadata.EntityName;

            if (string.IsNullOrEmpty(mapName))
            {
                mapName = Loc.GetString("shuttle-console-unknown");
            }

            var heading = new CollapsibleHeading(mapName);

            heading.MinHeight = 32f;
            heading.AddStyleClass(ContainerButton.StyleClassButton);
            heading.HorizontalAlignment = HAlignment.Stretch;
            heading.Label.HorizontalAlignment = HAlignment.Center;
            heading.Label.HorizontalExpand = true;
            heading.HorizontalExpand = true;

            var gridContents = new BoxContainer()
            {
                Orientation = LayoutOrientation.Vertical,
                VerticalExpand = true,
            };

            var body = new CollapsibleBody()
            {
                HorizontalAlignment = HAlignment.Stretch,
                VerticalAlignment = VAlignment.Top,
                HorizontalExpand = true,
                Children =
                {
                    gridContents
                }
            };

            var mapButton = new Collapsible(heading, body);

            heading.OnToggled += args =>
            {
                if (args.Pressed)
                {
                    HideOtherCollapsibles(mapButton);
                }
            };

            _mapSectorCollapsibles[mapComp.MapId] = mapButton;
            _mapSectorNames[mapComp.MapId] = mapName;
            _mapHeadings.Add(mapComp.MapId, gridContents);
            foreach (var grid in _mapManager.GetAllGrids(mapComp.MapId))
            {
                _entManager.TryGetComponent(grid.Owner, out IFFComponent? iffComp);

                // Mono
                var hideLabel = iffComp != null && (iffComp.Flags & IFFFlags.HideLabel) != 0x0 && grid.Owner != _shuttleEntity; // never hide our own label
                var detectionLevel = _console == null ? DetectionLevel.Detected : _detection.IsGridDetected(grid.Owner, _console.Value);
                var detected = detectionLevel != DetectionLevel.Undetected || !hideLabel;
                if (!detected || iffComp != null && (iffComp.Flags & IFFFlags.Hide) != 0x0)
                    continue;
                var name = hideLabel ?
                    detectionLevel == DetectionLevel.PartialDetected ?
                        Loc.GetString($"shuttle-console-signature-infrared")
                        : _detection.HandleUnknownMassLabel(grid.Owner)
                    : _entManager.GetComponent<MetaDataComponent>(grid.Owner).EntityName;

                var gridObj = new GridMapObject()
                {
                    Name = name, // Mono
                    Entity = grid.Owner,
                    HideButton = iffComp != null && (iffComp.Flags & IFFFlags.HideLabelAlways) != 0x0,
                };

                // Always show our shuttle immediately
                if (grid.Owner == _shuttleEntity)
                {
                    AddMapObject(mapComp.MapId, gridObj);
                }

                // If we can show it then add it to pending.
                else if (!_shuttles.IsBeaconMap(mapUid) && (iffComp == null ||
                         (iffComp.Flags & IFFFlags.Hide) == 0x0) &&
                         !gridObj.HideButton)
                {
                    _pendingMapObjects.Add((mapComp.MapId, gridObj));
                }
            }

            foreach (var (beacon, _) in _shuttles.GetExclusions(mapComp.MapId, _exclusions))
            {
                if (beacon.HideButton)
                    continue;

                _pendingMapObjects.Add((mapComp.MapId, beacon));
            }

            foreach (var (beacon, _) in _shuttles.GetBeacons(mapComp.MapId, _beacons))
            {
                if (beacon.HideButton)
                    continue;

                _pendingMapObjects.Add((mapComp.MapId, beacon));
            }

            HyperspaceDestinations.AddChild(mapButton);

            // Zoom in to our map
            if (mapComp.MapId == MapRadar.ViewingMap)
            {
                mapButton.BodyVisible = true;
            }
        }

        // Need to sort from furthest way to nearest (as we will pop from the end of the list first).
        // Also prioritise those on our map first.
        var shuttlePos = _xformSystem.GetWorldPosition(_shuttleEntity.Value);

        _pendingMapObjects.Sort((x, y) =>
        {
            if (x.mapId == ourMap && y.mapId != ourMap)
                return 1;

            if (y.mapId == ourMap && x.mapId != ourMap)
                return -1;

            var yMapPos = _shuttles.GetMapCoordinates(y.mapobj);
            var xMapPos = _shuttles.GetMapCoordinates(x.mapobj);

            return (yMapPos.Position - shuttlePos).Length().CompareTo((xMapPos.Position - shuttlePos).Length());
        });
    }

    /// <summary>
    /// Hides other maps upon the specified collapsible being selected (AKA hacky collapsible groups).
    /// </summary>
    private void HideOtherCollapsibles(Collapsible collapsible)
    {
        foreach (var child in HyperspaceDestinations.Children)
        {
            if (child is not Collapsible childCollapse || childCollapse == collapsible)
                continue;

            childCollapse.BodyVisible = false;
        }
    }

    /// <summary>
    /// Returns true if we shouldn't be able to select the FTL button.
    /// </summary>
    private bool IsFTLBlocked()
    {
        switch (_state)
        {
            case FTLState.Available:
                return false;
            default:
                return true;
        }
    }

    private void OnMapObjectPress(IMapObject mapObject)
    {
        if (IsFTLBlocked())
            return;

        var coordinates = _shuttles.GetMapCoordinates(mapObject);

        // If it's our map then scroll, otherwise just set position there.
        MapRadar.SetMap(coordinates.MapId, coordinates.Position, recentering: true);
    }

    public void SetMap(MapId mapId, Vector2 position)
    {
        MapRadar.SetMap(mapId, position);
        MapRadar.Offset = position;
    }

    /// <summary>
    /// Adds a map object to the specified sector map.
    /// </summary>
    private void AddMapObject(MapId mapId, IMapObject mapObj)
    {
        var existing = _mapObjects.GetOrNew(mapId);
        existing.Add(mapObj);

        var gridContents = _mapHeadings[mapId];

        var gridButton = new Button()
        {
            Text = mapObj.Name,
            HorizontalExpand = true,
        };

        var gridContainer = new BoxContainer()
        {
            Children =
            {
                new Control()
                {
                    MinWidth = 32f,
                },
                gridButton
            }
        };

        _mapObjectControls.Add(gridContainer, mapObj.Name);
        gridContents.AddChild(gridContainer);

        // Forge-Change-Start
        gridContainer.Visible = RowMatchesFilter(mapId, mapObj.Name);
        // Forge-Change-End

        gridButton.OnPressed += args =>
        {
            OnMapObjectPress(mapObj);
        };

        if (gridContents.ChildCount > 1)
        {
            // Re-sort the children
            _sortChildren.Clear();

            foreach (var child in gridContents.Children)
            {
                DebugTools.Assert(_mapObjectControls.ContainsKey(child));
                _sortChildren.Add(child);
            }

            foreach (var child in _sortChildren)
            {
                child.Orphan();
            }

            _sortChildren.Sort((x, y) =>
            {
                var xText = _mapObjectControls[x];
                var yText = _mapObjectControls[y];

                return string.Compare(xText, yText, StringComparison.CurrentCultureIgnoreCase);
            });

            foreach (var control in _sortChildren)
            {
                gridContents.AddChild(control);
            }
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var curTime = _timing.CurTime;

        // Skip the gradual reveal of map objects - they're already added in PingMap
        // if (_nextMapDequeue < curTime && _pendingMapObjects.Count > 0)
        // {
        //     var mapObj = _pendingMapObjects[^1];
        //     _pendingMapObjects.RemoveAt(_pendingMapObjects.Count - 1);
        //     AddMapObject(mapObj.mapId, mapObj.mapobj);
        //     BumpMapDequeue();
        // }

        if (!IsFTLBlocked() && _nextPing < curTime)
        {
            MapRebuildButton.Disabled = false;
        }

        var progress = _ftlTime.ProgressAt(curTime);
        FTLBar.Value = float.IsFinite(progress) ? progress : 1;

        // Forge-Change-start - BioScan
        if (_bioScanStatus == ShuttleBioScanStatus.InProgress)
        {
            var scanProgress = _bioScanTime.ProgressAt(curTime);
            BioScanBar.Value = float.IsFinite(scanProgress) ? scanProgress : 0;
        }
        else
        {
            BioScanBar.Value = _bioScanStatus == ShuttleBioScanStatus.Clean || _bioScanStatus == ShuttleBioScanStatus.ThreatDetected ? 1 : 0;
        }
        // Forge-Change-end - BioScan
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        MapRadar.SetMapObjects(_mapObjects);
        base.Draw(handle);
    }

    public void Startup()
    {
        if (_entManager.TryGetComponent(_shuttleEntity, out TransformComponent? shuttleXform))
        {
            SetMap(shuttleXform.MapID, _maps.GetGridPosition((_shuttleEntity.Value, null, shuttleXform)));
        }
    }
}
