using System.Numerics;
using Content.Client._Forge.UserInterface; // Forge-Change
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Actions.Widgets;

[GenerateTypedNameReferences]
public sealed partial class ActionsBar : UIWidget
{
    public ActionsBar()
    {
        RobustXamlLoader.Load(this);
        // Forge-Change-Start
        ForgeUiSizing.EnsureInitialized();
        ApplyHudScale();
        // Forge-Change-End
    }

    // Forge-Change-Start
    protected override void EnteredTree()
    {
        base.EnteredTree();
        ForgeUiSizing.HudScaleChanged += ApplyHudScale;
    }

    protected override void ExitedTree()
    {
        ForgeUiSizing.HudScaleChanged -= ApplyHudScale;
        base.ExitedTree();
    }

    private void ApplyHudScale()
    {
        ActionsContainer.MaxSize = new Vector2(ForgeUiSizing.ButtonSize, 9999);
    }
    // Forge-Change-End
}

