using System.Numerics;
using Content.Client._Forge.Mapping;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.Mapping;

[GenerateTypedNameReferences]
public sealed partial class MappingPrototypeList : Control
{
    private (int start, int end) _lastIndices;
    private readonly List<MappingPrototype> _prototypes = new();
    private readonly List<Texture> _insertTextures = new();
    private readonly List<MappingPrototype> _search = new();
    private readonly ButtonGroup _tabGroup = new();
    private Func<MappingPrototype, bool>? _isFavorite;

    public MappingSpawnButton? Selected;
    public MappingPaletteTab CurrentTab { get; private set; } = MappingPaletteTab.Entities;
    // Forge-Change: above this, folder children are virtualized instead of all inserted at once.
    public const int MaxInlineChildren = 32;
    private readonly List<NestedVirtualList> _nestedLists = new();
    public bool GridMode => GridButton.Pressed;
    public bool NestedChildren => CurrentTab == MappingPaletteTab.Hierarchy;
    public Action<IPrototype, List<Texture>>? GetPrototypeData;
    public event Action<MappingSpawnButton, IPrototype?>? SelectionChanged;
    public event Action<MappingSpawnButton, ButtonToggledEventArgs>? CollapseToggled;
    public event Action<MappingPaletteTab>? TabChanged;
    public event Action<MappingPrototype, bool>? FavoriteToggled;
    public event Action<MappingPrototype>? RecentClicked;

    public MappingPrototypeList()
    {
        RobustXamlLoader.Load(this);

        MeasureButton.Measure(Vector2Helpers.Infinity);

        ScrollContainer.OnScrolled += UpdateVirtualLists;
        OnResized += UpdateVirtualLists;

        // Forge-Change-Start
        EntitiesTab.Group = _tabGroup;
        TilesTab.Group = _tabGroup;
        DecalsTab.Group = _tabGroup;
        FavoritesTab.Group = _tabGroup;
        RecentsTab.Group = _tabGroup;
        HierarchyTab.Group = _tabGroup;
        EntitiesTab.Pressed = true;

        EntitiesTab.OnPressed += _ => SetTab(MappingPaletteTab.Entities);
        TilesTab.OnPressed += _ => SetTab(MappingPaletteTab.Tiles);
        DecalsTab.OnPressed += _ => SetTab(MappingPaletteTab.Decals);
        FavoritesTab.OnPressed += _ => SetTab(MappingPaletteTab.Favorites);
        RecentsTab.OnPressed += _ => SetTab(MappingPaletteTab.Recents);
        HierarchyTab.OnPressed += _ => SetTab(MappingPaletteTab.Hierarchy);
        GridButton.OnToggled += _ => TabChanged?.Invoke(CurrentTab);

        SearchBar.PlaceHolder = Loc.GetString("mapping-palette-search");
        // Forge-Change-End
    }

    public void SetTab(MappingPaletteTab tab, bool invoke = true)
    {
        CurrentTab = tab;
        EntitiesTab.Pressed = tab == MappingPaletteTab.Entities;
        TilesTab.Pressed = tab == MappingPaletteTab.Tiles;
        DecalsTab.Pressed = tab == MappingPaletteTab.Decals;
        FavoritesTab.Pressed = tab == MappingPaletteTab.Favorites;
        RecentsTab.Pressed = tab == MappingPaletteTab.Recents;
        HierarchyTab.Pressed = tab == MappingPaletteTab.Hierarchy;
        GridButton.Disabled = tab is not (MappingPaletteTab.Tiles or MappingPaletteTab.Decals);

        if (invoke)
            TabChanged?.Invoke(tab);
    }

    public void SetFavoritePredicate(Func<MappingPrototype, bool> predicate)
    {
        _isFavorite = predicate;
    }

    public void SetSelectionInfo(string? name, string? id)
    {
        SelectionLabel.Text = string.IsNullOrEmpty(name)
            ? Loc.GetString("mapping-palette-none-selected")
            : Loc.GetString("mapping-palette-selected", ("name", name));
        IdBox.Text = id ?? string.Empty;
        IdBox.ToolTip = id;
    }

    public void RefreshRecents(IReadOnlyList<MappingPrototype> recents)
    {
        RecentsBar.DisposeAllChildren();

        foreach (var mapping in recents)
        {
            if (mapping.Prototype == null)
                continue;

            _insertTextures.Clear();
            GetPrototypeData?.Invoke(mapping.Prototype, _insertTextures);
            var texture = _insertTextures.Count > 0 ? _insertTextures[0] : Texture.Transparent;

            var button = new TextureButton
            {
                TextureNormal = texture,
                SetSize = new Vector2(40, 40),
                ToolTip = string.Concat(mapping.Name, "\n", mapping.Prototype.ID),
                TooltipDelay = 0
            };

            var captured = mapping;
            button.OnPressed += _ => RecentClicked?.Invoke(captured);
            RecentsBar.AddChild(button);
        }
    }

    public void ShowTree()
    {
        PrototypeList.Visible = true;
        SearchList.Visible = false;
        PaletteGrid.Visible = false;
    }

    public void ShowSearchResults()
    {
        PrototypeList.Visible = false;
        SearchList.Visible = true;
        PaletteGrid.Visible = false;
    }

    public void PopulateGrid(List<MappingPrototype> prototypes)
    {
        PaletteGrid.DisposeAllChildren();
        PrototypeList.Visible = false;
        SearchList.Visible = false;
        PaletteGrid.Visible = true;
        ScrollContainer.SetScrollValue(new Vector2(0, 0));

        foreach (var mapping in prototypes)
        {
            if (mapping.Prototype == null)
                continue;

            _insertTextures.Clear();
            GetPrototypeData?.Invoke(mapping.Prototype, _insertTextures);
            var texture = _insertTextures.Count > 0 ? _insertTextures[0] : Texture.Transparent;

            var button = new TextureButton
            {
                TextureNormal = texture,
                SetSize = new Vector2(52, 52),
                ToolTip = string.Concat(mapping.Name, "\n", mapping.Prototype.ID),
                TooltipDelay = 0,
                ToggleMode = true,
                Pressed = Selected?.Prototype == mapping
            };

            var captured = mapping;
            button.OnPressed += _ =>
            {
                var spawn = new MappingSpawnButton { Prototype = captured };
                SelectionChanged?.Invoke(spawn, captured.Prototype);
            };
            PaletteGrid.AddChild(button);
        }
    }

    public void UpdateVisible(List<MappingPrototype> prototypes)
    {
        _prototypes.Clear();
        _nestedLists.Clear();

        PrototypeList.DisposeAllChildren();

        _prototypes.AddRange(prototypes);

        Selected = null;
        ScrollContainer.SetScrollValue(new Vector2(0, 0));
        ShowTree();

        foreach (var prototype in _prototypes)
        {
            Insert(PrototypeList, prototype, NestedChildren || prototype.Prototype == null);
        }
    }

    public MappingSpawnButton Insert(Container list, MappingPrototype mapping, bool includeChildren)
    {
        var prototype = mapping.Prototype;

        _insertTextures.Clear();

        if (prototype != null)
            GetPrototypeData?.Invoke(prototype, _insertTextures);

        var button = new MappingSpawnButton { Prototype = mapping };
        button.Label.Text = mapping.Name;

        // Forge-Change-Start: show prototype ID so duplicate names stay distinguishable while scrolling.
        if (prototype != null)
        {
            button.IdLabel.Visible = true;
            button.IdLabel.Text = prototype.ID;
            button.Button.ToolTip = string.Concat(mapping.Name, "\n", prototype.ID);
            button.Button.TooltipDelay = 0;
        }
        // Forge-Change-End

        if (_insertTextures.Count > 0)
        {
            button.Texture.Textures.AddRange(_insertTextures);
            button.Texture.InvalidateMeasure();
        }
        else
        {
            button.Texture.Visible = false;
        }

        if (prototype != null && button.Prototype == Selected?.Prototype)
        {
            Selected = button;
            button.Button.Pressed = true;
        }

        // Forge-Change-Start
        if (prototype != null)
        {
            button.FavoriteButton.Visible = true;
            button.FavoriteButton.Pressed = _isFavorite?.Invoke(mapping) == true;
            button.FavoriteButton.Text = button.FavoriteButton.Pressed ? "★" : "☆";
            button.FavoriteButton.OnToggled += args =>
            {
                button.FavoriteButton.Text = args.Pressed ? "★" : "☆";
                FavoriteToggled?.Invoke(mapping, args.Pressed);
            };
        }
        // Forge-Change-End

        list.AddChild(button);

        button.Button.OnToggled += _ => SelectionChanged?.Invoke(button, prototype);

        if (includeChildren && mapping.Children?.Count > 0)
        {
            button.CollapseButton.Visible = true;
            button.CollapseButton.OnToggled += args => CollapseToggled?.Invoke(button, args);
        }
        else
        {
            button.CollapseButtonWrapper.Visible = false;
            button.CollapseButton.Visible = false;
        }

        return button;
    }

    // Forge-Change-Start
    public bool IsLargeGroup(MappingPrototype mapping)
    {
        return mapping.Children != null && mapping.Children.Count > MaxInlineChildren;
    }

    /// <summary>
    ///     Inserts a folder's children. Large folders stay in the category tree and virtualize
    ///     their rows so expanding "Items" does not create thousands of buttons.
    /// </summary>
    public void InsertChildren(Container list, MappingPrototype mapping, bool includeChildren)
    {
        if (mapping.Children == null || mapping.Children.Count == 0)
            return;

        if (mapping.Children.Count > MaxInlineChildren)
        {
            InsertVirtualizedChildren(list, mapping.Children);
            return;
        }

        foreach (var child in mapping.Children)
            Insert(list, child, includeChildren);
    }

    private void InsertVirtualizedChildren(Container list, List<MappingPrototype> children)
    {
        var container = new PrototypeListContainer
        {
            HorizontalExpand = true,
            TotalItemCount = children.Count
        };
        list.AddChild(container);

        var nested = new NestedVirtualList(container, children);
        _nestedLists.Add(nested);
        SyncVirtualWindow(nested.Container, nested.Items, ref nested.LastIndices);
    }
    // Forge-Change-End

    public void Search(List<MappingPrototype> prototypes)
    {
        _search.Clear();
        SearchList.DisposeAllChildren();
        _lastIndices = (0, -1);

        _search.AddRange(prototypes);
        SearchList.TotalItemCount = _search.Count;
        ScrollContainer.SetScrollValue(new Vector2(0, 0));
        ShowSearchResults();

        UpdateVirtualLists();
    }

    /// <summary>
    ///     Constructs a virtual list where not all buttons exist at one time, since there may be thousands of them.
    /// </summary>
    private void UpdateVirtualLists()
    {
        if (SearchList.Visible)
        {
            SyncVirtualWindow(SearchList, _search, ref _lastIndices);
            return;
        }

        if (!PrototypeList.Visible)
            return;

        for (var i = _nestedLists.Count - 1; i >= 0; i--)
        {
            var nested = _nestedLists[i];
            if (nested.Container.Parent == null)
            {
                _nestedLists.RemoveAt(i);
                continue;
            }

            SyncVirtualWindow(nested.Container, nested.Items, ref nested.LastIndices);
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_nestedLists.Count > 0 && PrototypeList.Visible)
            UpdateVirtualLists();
    }

    private void SyncVirtualWindow(PrototypeListContainer list, List<MappingPrototype> items, ref (int start, int end) lastIndices)
    {
        if (items.Count == 0)
            return;

        var height = MeasureButton.DesiredSize.Y + PrototypeListContainer.Separation;
        if (height <= 1f)
            height = 42f;

        var listPosY = list.GlobalPosition.Y - ScrollContainer.GlobalPosition.Y;
        var startIndex = (int) Math.Floor(Math.Max(-listPosY, 0) / height);
        if (startIndex < 0)
            startIndex = 0;
        if (startIndex > items.Count - 1)
            startIndex = items.Count - 1;

        var viewport = ScrollContainer.Height;
        if (viewport <= 0)
            viewport = 480;

        var endIndex = startIndex + (int) Math.Ceiling(viewport / height) + 2;
        if (endIndex > items.Count - 1)
            endIndex = items.Count - 1;

        list.ItemOffset = startIndex;
        list.TotalItemCount = items.Count;

        var (prevStart, prevEnd) = lastIndices;
        var expected = prevEnd >= prevStart ? prevEnd - prevStart + 1 : 0;
        if (list.ChildCount != expected)
        {
            list.DisposeAllChildren();
            prevStart = 0;
            prevEnd = -1;
        }

        if (endIndex == prevEnd && startIndex == prevStart)
            return;

        lastIndices = (startIndex, endIndex);

        for (var i = prevStart; i < startIndex && i <= prevEnd; i++)
        {
            if (list.ChildCount == 0)
                break;

            list.RemoveChild(list.GetChild(0));
        }

        for (var i = prevEnd; i > endIndex && i >= prevStart; i--)
        {
            if (list.ChildCount == 0)
                break;

            list.RemoveChild(list.GetChild(list.ChildCount - 1));
        }

        for (var i = Math.Min(prevStart - 1, endIndex); i >= startIndex; i--)
        {
            if (i < 0 || i >= items.Count)
                continue;

            Insert(list, items[i], false).SetPositionInParent(0);
        }

        for (var i = Math.Max(prevEnd + 1, startIndex); i <= endIndex; i++)
        {
            if (i < 0 || i >= items.Count)
                continue;

            Insert(list, items[i], false);
        }
    }

    // Forge-Change-Start
    private sealed class NestedVirtualList
    {
        public readonly PrototypeListContainer Container;
        public readonly List<MappingPrototype> Items;
        public (int start, int end) LastIndices;

        public NestedVirtualList(PrototypeListContainer container, List<MappingPrototype> items)
        {
            Container = container;
            Items = items;
            LastIndices = (0, -1);
        }
    }
    // Forge-Change-End
}
