using System.Numerics;
using Content.Client._Forge.Contractors.UI;
using Content.Shared._Forge.Contractors;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._EE.Contractors.UI;

// Forge-Change-full
[GenerateTypedNameReferences]
public sealed partial class PassportWindow : BaseWindow
{
    public PassportWindow()
    {
        RobustXamlLoader.Load(this);
        CloseButton.OnPressed += _ => Close();
    }

    public void UpdateState(PassportBoundUserInterfaceState state)
    {
        var theme = PassportDocumentControl.GetTheme(state.Profile?.Nationality);
        CoverPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = theme.Leather,
            BorderColor = theme.Gold,
            BorderThickness = new Thickness(3),
        };

        Document.UpdateFromProfile(state.Profile, state.Pid);
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }
}
