- type: job
  id: EmpireApotek
  name: forge-job-name-apotek
  description: forge-job-desc-apotek
  supervisors: job-supervisors-praetorian
  playTimeTracker: JobEmpireApotek
  icon: JobIconEmpireApotek
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 21600 # 6 hrs
    - !type:SpeciesRequirement
      species:
        - Human
        - Dwarf
    - !type:SexRequirement
      sex:
      - Male
      - Female
  setPreference: false
  overrideConsoleVisibility: true
  startingGear: EmpireApotekGear
  alwaysUseSpawner: true
  weight: 170
  displayWeight: 38
  canBeAntag: false
  assignedCompany: Imperial
  assignedNationality: Imperial
  accessGroups:
  - GeneralEmpireAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - Empire
  - !type:AddImplantSpecial
    implants: [ ImplantGuard , EmpireTrackingImplant]

- type: startingGear
  id: EmpireApotekGear
