using System.Collections.Generic;
using System.Linq;
using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared._Mono.Company;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Forge.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class PoiCaptureConsoleWindow : FancyWindow,
    IComputerWindow<PoiCaptureConsoleBoundUserInterfaceState>
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private PoiCaptureConsoleBoundUserInterfaceState _state = new();
    private List<ForgeIffTransferListEntry> _lastTransferCompanies = new();

    public event Action? CaptureStart;
    public event Action? CaptureInterrupt;
    public event Action<string>? TransferOwnership;

    public PoiCaptureConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CaptureStartButton.OnPressed += _ => CaptureStart?.Invoke();
        CaptureInterruptButton.OnPressed += _ => CaptureInterrupt?.Invoke();
        TransferOwnershipButton.OnPressed += _ => TransferOwnership?.Invoke(GetOptionId(TransferCompanyOption));
        TransferCompanyOption.OnItemSelected += _ =>
            TransferOwnershipButton.Disabled = string.IsNullOrEmpty(GetOptionId(TransferCompanyOption));
    }

    private static string GetOptionId(OptionButton button)
    {
        if (button.ItemCount <= 0)
            return string.Empty;

        var selectedId = button.SelectedId;
        if (selectedId == 0)
            return string.Empty;

        for (var i = 0; i < button.ItemCount; i++)
        {
            if (button.GetItemId(i) != selectedId)
                continue;

            return button.GetItemMetadata(i) as string ?? string.Empty;
        }

        return string.Empty;
    }

    public void UpdateState(PoiCaptureConsoleBoundUserInterfaceState state)
    {
        _state = state;

        CaptureOwnerLabel.Text = BuildCompanyFactionMarkup(
            "iff-console-capture-owner-prefix",
            state.CurrentOwnerCompanyId,
            state.CurrentOwnerFactionId);
        CaptureAttackerLabel.Text = BuildCompanyFactionMarkup(
            "iff-console-capture-attacker-prefix",
            state.AttackerCompanyId,
            state.AttackerFactionId);
        CaptureByLabel.Text = Loc.GetString("iff-console-capture-by-label-value",
            ("name", string.IsNullOrWhiteSpace(state.LastCapturedByName) ? Loc.GetString("iff-console-capture-by-none") : state.LastCapturedByName));
        var recaptureLocked = IsRecaptureLocked(state);
        CaptureStartButton.Disabled = state.CaptureInProgress || recaptureLocked;
        CaptureInterruptButton.Disabled = !state.CaptureInProgress;

        var canTransfer = CanTransfer(state);
        TransferSection.Visible = canTransfer;

        RebuildTransferOptions(state);
        TransferOwnershipButton.Disabled = !canTransfer || string.IsNullOrEmpty(GetOptionId(TransferCompanyOption));
    }

    private bool CanTransfer(PoiCaptureConsoleBoundUserInterfaceState state)
    {
        if (state.CaptureInProgress)
            return false;

        if (state.CanTransfer)
            return true;

        var local = _player.LocalSession?.UserId;
        return local != null
            && state.CaptureLeaderUserId != null
            && state.CaptureLeaderUserId == local;
    }

    private void RebuildTransferOptions(PoiCaptureConsoleBoundUserInterfaceState state)
    {
        if (TransferCompaniesEqual(state.TransferCompanies, _lastTransferCompanies))
            return;

        var prevCompany = GetOptionId(TransferCompanyOption);

        TransferCompanyOption.Clear();
        TransferCompanyOption.AddItem(Loc.GetString("iff-console-transfer-pick-company"));
        TransferCompanyOption.SetItemMetadata(0, string.Empty);

        var idx = 1;
        foreach (var e in state.TransferCompanies)
        {
            TransferCompanyOption.AddItem(e.Label);
            TransferCompanyOption.SetItemMetadata(idx++, e.Id);
        }

        SelectOptionById(TransferCompanyOption, prevCompany);
        _lastTransferCompanies = state.TransferCompanies
            .Select(entry => new ForgeIffTransferListEntry { Id = entry.Id, Label = entry.Label })
            .ToList();
    }

    private static bool TransferCompaniesEqual(List<ForgeIffTransferListEntry> a, List<ForgeIffTransferListEntry> b)
    {
        if (a.Count != b.Count)
            return false;

        for (var i = 0; i < a.Count; i++)
        {
            if (a[i].Id != b[i].Id || a[i].Label != b[i].Label)
                return false;
        }

        return true;
    }

    private static void SelectOptionById(OptionButton button, string id)
    {
        if (string.IsNullOrEmpty(id))
        {
            button.SelectId(0);
            return;
        }

        for (var i = 1; i < button.ItemCount; i++)
        {
            if (button.GetItemMetadata(i) is string meta && meta == id)
            {
                button.SelectId(i);
                return;
            }
        }

        button.SelectId(0);
    }

    private string BuildCompanyFactionMarkup(string prefixLoc, string companyId, string factionId)
    {
        var prefix = Loc.GetString(prefixLoc);
        var factionEsc = FormattedMessage.EscapeText(factionId);
        string companyEsc;
        Color companyColor;
        if (companyId != "None" && _prototype.TryIndex<CompanyPrototype>(companyId, out var comp))
        {
            companyEsc = FormattedMessage.EscapeText(comp.Name);
            companyColor = comp.Color;
        }
        else
        {
            companyEsc = FormattedMessage.EscapeText(companyId);
            companyColor = Color.FromHex("#9a9a9a", Color.LightGray);
        }

        var hex = companyColor.ToHex();
        return
            $"[color=#b0b0b0]{FormattedMessage.EscapeText(prefix)}:[/color] " +
            $"[color={hex}]{companyEsc}[/color] " +
            $"[color=#7a7a7a]/ {factionEsc}[/color]";
    }

    private bool IsRecaptureLocked(PoiCaptureConsoleBoundUserInterfaceState state)
    {
        return state.RecaptureAvailableTime > TimeSpan.Zero
            && _timing.CurTime < state.RecaptureAvailableTime;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_state.CaptureInProgress)
        {
            var remaining = _state.CaptureEndTime - _timing.CurTime;
            if (remaining < TimeSpan.Zero)
                remaining = TimeSpan.Zero;

            CaptureTimerLabel.Text = Loc.GetString("iff-console-capture-timer-running",
                ("minutes", remaining.Minutes.ToString("00")),
                ("seconds", remaining.Seconds.ToString("00")));
            return;
        }

        if (IsRecaptureLocked(_state))
        {
            var remaining = _state.RecaptureAvailableTime - _timing.CurTime;
            if (remaining < TimeSpan.Zero)
                remaining = TimeSpan.Zero;

            CaptureStartButton.Disabled = true;
            CaptureTimerLabel.Text = Loc.GetString("iff-console-capture-recapture-timer",
                ("hours", (int) remaining.TotalHours),
                ("minutes", remaining.Minutes.ToString("00")));
            return;
        }

        CaptureTimerLabel.Text = Loc.GetString("iff-console-capture-timer-idle");
    }
}
