using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.Turrets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.Turrets;

[GenerateTypedNameReferences]
public sealed partial class TurretCommandWindow : FancyWindow
{
    public event Action<NetEntity, bool>? OnTurretToggled;
    public event Action<NetEntity, bool>? OnMagazineLockToggled;
    public event Action<NetEntity, TurretDoctrine>? OnTurretDoctrineSelected;
    public event Action<string, TurretIffSide>? OnNameAdded;
    public event Action<string>? OnPersonCleared;
    public event Action<TurretDoctrine>? OnDoctrineSelected;
    public event Action? OnRefreshRequested;

    [Dependency] private readonly IEntityManager _entities = default!;

    private readonly Color _stoodDown = Color.FromHex("#6e6e6e");
    private readonly Color _jammed = Color.FromHex("#d04040");
    private TurretMapActionPopup? _mapPopup;

    public TurretCommandWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Tabs.SetTabTitle(0, Loc.GetString("turret-command-tab-map"));
        Tabs.SetTabTitle(1, Loc.GetString("turret-command-tab-turrets"));
        Tabs.SetTabTitle(2, Loc.GetString("turret-command-tab-lists"));
        FriendlyButton.OnPressed += _ => SubmitName(TurretIffSide.Friendly);
        HostileButton.OnPressed += _ => SubmitName(TurretIffSide.Hostile);
        NeutralButton.OnPressed += _ => OnDoctrineSelected?.Invoke(TurretDoctrine.Neutral);
        HostileModeButton.OnPressed += _ => OnDoctrineSelected?.Invoke(TurretDoctrine.Hostile);
        FriendlyModeButton.OnPressed += _ => OnDoctrineSelected?.Invoke(TurretDoctrine.Friendly);
        RefreshButton.OnPressed += _ => OnRefreshRequested?.Invoke();
        NavMap.OnTurretSelected += OpenMapPopup;
        OnClose += () => _mapPopup?.Close();
        ApplyChrome(Color.FromHex("#c87820"), TurretDoctrine.Neutral);
    }

    private void SubmitName(TurretIffSide side)
    {
        var name = NameInput.Text.Trim();
        if (name.Length == 0)
            return;

        OnNameAdded?.Invoke(name, side);
        NameInput.Text = string.Empty;
    }

    public void UpdateState(TurretCommandConsoleState state)
    {
        NoServerLabel.Visible = !state.HasServer;
        Tabs.Visible = state.HasServer;
        var shared = SharedDoctrine(state.Turrets);
        ApplyChrome(state.Accent, shared);
        ModeHint.Text = Loc.GetString(shared switch
        {
            TurretDoctrine.Hostile => "turret-command-mode-hostile-hint",
            TurretDoctrine.Friendly => "turret-command-mode-friendly-hint",
            null => "turret-command-mode-mixed-hint",
            _ => "turret-command-mode-neutral-hint",
        });

        TurretList.DisposeAllChildren();
        FriendlyList.DisposeAllChildren();
        HostileList.DisposeAllChildren();
        PresentList.DisposeAllChildren();

        if (!state.HasServer)
            return;

        if (state.Turrets.Count == 0)
            TurretList.AddChild(new Label { Text = Loc.GetString("turret-command-window-no-turrets") });

        foreach (var turret in state.Turrets)
        {
            var entry = turret;
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 2),
            };
            row.AddChild(new Label
            {
                Text = entry.Jammed
                    ? Loc.GetString("turret-command-window-turret-jammed", ("name", entry.Name))
                    : entry.Name,
                FontColorOverride = entry.Jammed ? _jammed : null,
                HorizontalExpand = true,
                ClipText = true,
            });
            row.AddChild(new Label
            {
                Text = entry.AmmoCapacity > 0
                    ? Loc.GetString("turret-command-window-ammo", ("count", entry.Ammo), ("capacity", entry.AmmoCapacity))
                    : Loc.GetString("turret-command-window-ammo-none"),
                MinWidth = 72,
                Align = Label.AlignMode.Right,
                Margin = new Thickness(8, 0),
            });
            var mode = new Button
            {
                Text = DoctrineName(entry.Doctrine),
                MinWidth = 130,
            };
            mode.OnPressed += _ => OnTurretDoctrineSelected?.Invoke(entry.Entity, NextDoctrine(entry.Doctrine));
            row.AddChild(mode);
            var toggle = new Button
            {
                Text = Loc.GetString(entry.Enabled
                    ? "turret-command-window-stand-down"
                    : "turret-command-window-activate"),
                MinWidth = 110,
            };
            toggle.OnPressed += _ => OnTurretToggled?.Invoke(entry.Entity, !entry.Enabled);
            row.AddChild(toggle);
            var magazine = new Button
            {
                Text = Loc.GetString(entry.MagazineLocked
                    ? "turret-command-window-magazine-closed"
                    : "turret-command-window-magazine-open"),
                MinWidth = 100,
            };
            magazine.OnPressed += _ => OnMagazineLockToggled?.Invoke(entry.Entity, !entry.MagazineLocked);
            row.AddChild(magazine);
            TurretList.AddChild(row);
        }

        FillSideList(FriendlyList, state.Friendly);
        FillSideList(HostileList, state.Hostile);
        FillPresentList(state);
        UpdateMap(state);
        SyncMapPopup(state);
    }

    private void OpenMapPopup(TurretMapMarker marker, Vector2 screenPosition)
    {
        _mapPopup ??= new TurretMapActionPopup();
        if (_mapPopup.Turret != marker.Entity || !_mapPopup.Visible)
        {
            _mapPopup.OnToggled -= OnMapToggled;
            _mapPopup.OnDoctrineSelected -= OnMapDoctrine;
            _mapPopup.OnToggled += OnMapToggled;
            _mapPopup.OnDoctrineSelected += OnMapDoctrine;
        }

        _mapPopup.OpenFor(marker.Entity, marker.Name, marker.Enabled, marker.Doctrine, screenPosition);
    }

    private void OnMapToggled(bool enabled)
    {
        if (_mapPopup != null)
            OnTurretToggled?.Invoke(_mapPopup.Turret, enabled);
    }

    private void OnMapDoctrine(TurretDoctrine doctrine)
    {
        if (_mapPopup != null)
            OnTurretDoctrineSelected?.Invoke(_mapPopup.Turret, doctrine);
    }

    private void SyncMapPopup(TurretCommandConsoleState state)
    {
        if (_mapPopup is not { Visible: true } popup)
            return;

        foreach (var turret in state.Turrets)
        {
            if (turret.Entity != popup.Turret)
                continue;

            popup.Apply(turret.Name, turret.Enabled, turret.Doctrine);
            return;
        }

        popup.Close();
    }

    private void FillPresentList(TurretCommandConsoleState state)
    {
        if (!state.PlayersScanned)
        {
            PresentList.AddChild(new Label { Text = Loc.GetString("turret-command-window-scan-hint") });
            return;
        }

        if (state.Present.Count == 0)
        {
            PresentList.AddChild(new Label { Text = Loc.GetString("turret-command-window-scan-empty") });
            return;
        }

        foreach (var person in state.Present)
        {
            var name = person.Name;
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 2),
            };
            row.AddChild(new Label
            {
                Text = name,
                HorizontalExpand = true,
                ClipText = true,
            });
            var friendly = new Button
            {
                Text = Loc.GetString("turret-command-window-mark-friendly"),
                MinWidth = 88,
            };
            friendly.OnPressed += _ => OnNameAdded?.Invoke(name, TurretIffSide.Friendly);
            var hostile = new Button
            {
                Text = Loc.GetString("turret-command-window-mark-hostile"),
                MinWidth = 88,
            };
            hostile.OnPressed += _ => OnNameAdded?.Invoke(name, TurretIffSide.Hostile);
            row.AddChild(friendly);
            row.AddChild(hostile);
            PresentList.AddChild(row);
        }
    }

    private static TurretDoctrine? SharedDoctrine(List<TurretCommandTurretEntry> turrets)
    {
        if (turrets.Count == 0)
            return TurretDoctrine.Neutral;

        var doctrine = turrets[0].Doctrine;
        foreach (var turret in turrets)
        {
            if (turret.Doctrine != doctrine)
                return null;
        }

        return doctrine;
    }

    private static TurretDoctrine NextDoctrine(TurretDoctrine doctrine)
    {
        return doctrine switch
        {
            TurretDoctrine.Neutral => TurretDoctrine.Hostile,
            TurretDoctrine.Hostile => TurretDoctrine.Friendly,
            _ => TurretDoctrine.Neutral,
        };
    }

    private static string DoctrineName(TurretDoctrine doctrine)
    {
        return Loc.GetString(doctrine switch
        {
            TurretDoctrine.Hostile => "turret-command-mode-hostile",
            TurretDoctrine.Friendly => "turret-command-mode-friendly",
            _ => "turret-command-mode-neutral",
        });
    }

    private void UpdateMap(TurretCommandConsoleState state)
    {
        NavMap.SetMarkers(Array.Empty<TurretMapMarker>());

        if (!state.HasGrid || !_entities.TryGetEntity(state.Grid, out var grid))
        {
            NavMap.MapUid = null;
            return;
        }

        NavMap.MapUid = grid;
        NavMap.ApplyAccent(state.Accent);
        NavMap.ForceNavMapUpdate();

        var markers = new List<TurretMapMarker>(state.Turrets.Count);
        foreach (var turret in state.Turrets)
            markers.Add(new TurretMapMarker(
                turret.Entity,
                turret.Name,
                turret.Position,
                turret.Enabled,
                turret.Doctrine,
                turret.Jammed ? _jammed : turret.Enabled ? state.Accent : _stoodDown));

        NavMap.SetMarkers(markers);
    }

    private void ApplyChrome(Color accent, TurretDoctrine? doctrine)
    {
        var border = new Color(accent.R, accent.G, accent.B, 0.95f);
        var panel = new Color(accent.R * 0.16f, accent.G * 0.14f, accent.B * 0.10f, 0.96f);
        var ink = new Color(
            Math.Clamp(accent.R * 0.55f + 0.35f, 0f, 1f),
            Math.Clamp(accent.G * 0.55f + 0.28f, 0f, 1f),
            Math.Clamp(accent.B * 0.45f + 0.2f, 0f, 1f));

        MapPanel.PanelOverride = Flat(panel, border, 2);
        PresentPanel.PanelOverride = Flat(panel, border, 2);
        TurretPanel.PanelOverride = Flat(panel, border, 2);
        AddPanel.PanelOverride = Flat(panel, border, 2);
        FriendlyPanel.PanelOverride = Flat(panel, border, 2);
        HostilePanel.PanelOverride = Flat(panel, border, 2);

        MapHint.FontColorOverride = ink;
        AllHint.FontColorOverride = ink;
        PresentHeading.FontColorOverride = ink;
        FriendlyHeading.FontColorOverride = ink;
        HostileHeading.FontColorOverride = ink;
        ModeHint.FontColorOverride = ink;

        MarkMode(NeutralButton, doctrine == TurretDoctrine.Neutral, border, panel);
        MarkMode(HostileModeButton, doctrine == TurretDoctrine.Hostile, border, panel);
        MarkMode(FriendlyModeButton, doctrine == TurretDoctrine.Friendly, border, panel);
    }

    private static void MarkMode(Button button, bool selected, Color border, Color panel)
    {
        button.Modulate = selected ? Color.White : Color.FromHex("#9a9a9a");
        // The button style stays on the theme; the modulate marks the active doctrine.
        _ = border;
        _ = panel;
    }

    private void FillSideList(BoxContainer list, List<TurretCommandPersonEntry> entries)
    {
        if (entries.Count == 0)
        {
            list.AddChild(new Label { Text = Loc.GetString("turret-command-window-list-empty") });
            return;
        }

        foreach (var person in entries)
        {
            var key = person.Key;
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 2),
            };
            row.AddChild(new Label
            {
                Text = person.Name,
                HorizontalExpand = true,
                ClipText = true,
            });
            var remove = new Button
            {
                Text = Loc.GetString("turret-command-window-remove"),
                MinWidth = 88,
            };
            remove.OnPressed += _ => OnPersonCleared?.Invoke(key);
            row.AddChild(remove);
            list.AddChild(row);
        }
    }

    private static StyleBoxFlat Flat(Color background, Color border, float thickness)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new Thickness(thickness),
        };
    }
}
