using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.Trade;
using Content.Shared.Stacks;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;


namespace Content.Client._Forge.Trade;


[GenerateTypedNameReferences]
public sealed partial class NcStoreMenu : FancyWindow
{
    private readonly Dictionary<string, int> _balancesByCurrency = new();
    private readonly List<string> _barterCats = new();
    private readonly UiStateBinder _binder;
    private readonly List<string> _buyCats = new();
    private readonly NcStoreClientCatalogModel _catalogModel = new();
    private readonly Dictionary<string, int> _massSellTotals = new();
    private readonly IPrototypeManager _proto;
    private readonly HashSet<string> _scratchBarterCatSet = new();
    private readonly HashSet<string> _scratchBuyCatSet = new();
    private readonly HashSet<string> _scratchSellCatSet = new();
    private readonly List<string> _sellCats = new();
    private readonly SpriteSystem _sprites;
    private readonly List<string> _visibleBarterIds = new();
    private readonly List<string> _visibleBuyIds = new();
    private readonly List<string> _visibleSellIds = new();
    private readonly HashSet<string> _visibleUnionScratch = new();
    private bool _closed;
    private bool _hasBarterTab;
    private bool _hasBuyTab;
    private bool _hasContractsTab;
    private bool _hasSellTab;
    private ulong _lastVisibleIdsSig;
    private string _search = string.Empty;
    private string _searchLower = string.Empty;
    private Control? _tabBarter;
    private Control? _tabBuy;
    private Control? _tabContracts;
    private bool _tabsCaptured;
    private Control? _tabSell;
    private StoreUiColorsData _uiColors = new();
    private ulong _uiThemeHash;
    private PanelContainer? _windowBackdropPanel;
    public Action<string>? OnContractClaim;

    public NcStoreMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        TabContainer.SetTabTitle(TabBuy, Loc.GetString("nc-store-tab-buy"));
        TabContainer.SetTabTitle(TabSell, Loc.GetString("nc-store-tab-sell"));
        TabContainer.SetTabTitle(TabBarter, Loc.GetString("nc-store-tab-barter"));
        TabContainer.SetTabTitle(TabContracts, Loc.GetString("nc-store-tab-contracts"));
        ApplyUiTheme(_uiColors);
        _sprites = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
        _proto = IoCManager.Resolve<IPrototypeManager>();

        Header.BindServices(_proto, _sprites);

        BuyView.Initialize(StoreMode.Buy, _proto, _sprites, Loc.GetString("nc-store-tab-buy"), false);
        SellView.Initialize(StoreMode.Sell, _proto, _sprites, Loc.GetString("nc-store-tab-sell"), true);
        BarterView.Initialize(StoreMode.Barter, _proto, _sprites, Loc.GetString("nc-store-tab-barter"), false);

        BuyView.ConfigureCategories(GetCategoryDisplayName, GetCategoryToolTip);
        SellView.ConfigureCategories(GetCategoryDisplayName, GetCategoryToolTip);
        BarterView.ConfigureCategories(GetCategoryDisplayName, GetCategoryToolTip);

        Tabs.OnTabChanged += _ => CloseActiveContractConfirmWindow();
        BuyView.SelectedCategoryChanged += _ => CloseActiveContractConfirmWindow();
        SellView.SelectedCategoryChanged += _ => CloseActiveContractConfirmWindow();
        BarterView.SelectedCategoryChanged += _ => CloseActiveContractConfirmWindow();

        BuyView.VisibleIdsChanged += ids =>
        {
            _visibleBuyIds.Clear();
            _visibleBuyIds.AddRange(ids);
            EmitVisibleListingIdsChanged();
        };

        SellView.VisibleIdsChanged += ids =>
        {
            _visibleSellIds.Clear();
            _visibleSellIds.AddRange(ids);
            EmitVisibleListingIdsChanged();
        };

        BarterView.VisibleIdsChanged += ids =>
        {
            _visibleBarterIds.Clear();
            _visibleBarterIds.AddRange(ids);
            EmitVisibleListingIdsChanged();
        };

        Header.OnSearchChanged += text =>
        {
            if (_closed)
                return;

            _search = text;
            _searchLower = text.ToLowerInvariant();
            BuyView.SetSearch(_searchLower);
            SellView.SetSearch(_searchLower);
            BarterView.SetSearch(_searchLower);
            OnSearchChanged?.Invoke(_search);
            RefreshListings();
        };

        SellView.MassSellButtonControl.Disabled = true;
        SellView.MassSellButtonControl.ClipText = true;
        SellView.MassSellButtonControl.Text = Loc.GetString("nc-store-mass-sell-button");
        SellView.MassSellButtonControl.ToolTip = Loc.GetString("nc-store-mass-sell-tooltip");
        SellView.MassSellButtonControl.OnPressed += _ => OnMassSellPulledCrate?.Invoke();

        _binder = new(this);
    }

    public event Action<string>? OnContractTake;
    public event Action<string>? OnContractSkip;
    public event Action<string>? OnContractRequestPinpointer;

    private string GetCategoryDisplayName(string catId) =>
        catId switch
        {
            NcStoreClientCatalogModel.CatIdReady => Loc.GetString("nc-store-cat-ready-short"),
            NcStoreClientCatalogModel.CatIdCrate => Loc.GetString("nc-store-cat-crate-short"),
            _ => catId
        };

    private string GetCategoryToolTip(string catId) =>
        catId switch
        {
            NcStoreClientCatalogModel.CatIdReady => Loc.GetString("nc-store-cat-ready-full"),
            NcStoreClientCatalogModel.CatIdCrate => Loc.GetString("nc-store-cat-crate-full"),
            _ => catId
        };

    public event Action<string>? OnSearchChanged;
    public event Action<StoreListingData, int>? OnBarterPressed;
    public event Action<StoreListingData, int>? OnBuyPressed;
    public event Action<StoreListingData, int>? OnSellPressed;
    public event Action? OnMassSellPulledCrate;
    public event Action<string[]>? OnVisibleListingIdsChanged;

    public void SetDisplayTitle(string title)
    {
        var resolved = string.IsNullOrWhiteSpace(title)
            ? Loc.GetString("nc-store-window-title")
            : title;

        Title = resolved;
    }

    private void EmitVisibleListingIdsChanged()
    {
        if (OnVisibleListingIdsChanged == null)
            return;

        _visibleUnionScratch.Clear();

        for (var i = 0; i < _visibleBuyIds.Count; i++)
        {
            var id = _visibleBuyIds[i];
            if (!string.IsNullOrWhiteSpace(id))
                _visibleUnionScratch.Add(id);
        }

        for (var i = 0; i < _visibleSellIds.Count; i++)
        {
            var id = _visibleSellIds[i];
            if (!string.IsNullOrWhiteSpace(id))
                _visibleUnionScratch.Add(id);
        }

        for (var i = 0; i < _visibleBarterIds.Count; i++)
        {
            var id = _visibleBarterIds[i];
            if (!string.IsNullOrWhiteSpace(id))
                _visibleUnionScratch.Add(id);
        }

        var arr = _visibleUnionScratch.ToArray();
        Array.Sort(arr, static (a, b) => string.CompareOrdinal(a, b));

        var sig = 14695981039346656037UL;
        for (var i = 0; i < arr.Length; i++)
            sig = unchecked((sig ^ (uint) StableStringHash(arr[i])) * 1099511628211UL);

        if (sig == _lastVisibleIdsSig)
            return;

        _lastVisibleIdsSig = sig;
        OnVisibleListingIdsChanged(arr);
    }

    private int GetBalanceForCurrency(string currencyId)
    {
        if (string.IsNullOrWhiteSpace(currencyId))
            return 0;

        return _balancesByCurrency.GetValueOrDefault(currencyId, 0);
    }

    public void SetBalancesByCurrency(Dictionary<string, int> balances)
    {
        _balancesByCurrency.Clear();

        foreach (var (cur, amt) in balances)
        {
            if (string.IsNullOrWhiteSpace(cur))
                continue;

            _balancesByCurrency[cur] = amt;
        }

        Header.SetBalances(_balancesByCurrency);
    }


    public void SetMassSellTotals(Dictionary<string, int> totals)
    {
        _massSellTotals.Clear();
        foreach (var (cur, amt) in totals)
            _massSellTotals[cur] = amt;
        var btn = SellView.MassSellButtonControl;
        btn.Text = Loc.GetString("nc-store-mass-sell-button");
        btn.ClipText = true;

        if (_massSellTotals.Count == 0)
        {
            btn.ToolTip = Loc.GetString("nc-store-mass-sell-tooltip");
            btn.Disabled = true;
            return;
        }

        btn.Disabled = false;

        var parts = _massSellTotals
            .Where(p => p.Value > 0 && !string.IsNullOrWhiteSpace(p.Key))
            .Select(p => Loc.GetString(
                "nc-store-currency-format",
                ("amount", p.Value),
                ("currency", CurrencyName(p.Key))))
            .ToList();

        var full = parts.Count > 0 ? string.Join(", ", parts) : "-";

        btn.ToolTip = Loc.GetString("nc-store-mass-sell-tooltip-with-reward", ("reward", full));
    }

    public void PopulateCatalog(
        List<StoreListingStaticData> listings,
        bool hasBuyTab,
        bool hasSellTab,
        bool hasBarterTab,
        bool hasContractsTab,
        StoreUiColorsData? uiColors
    ) =>
        _binder.PopulateCatalog(listings, hasBuyTab, hasSellTab, hasBarterTab, hasContractsTab, uiColors);


    private void RebuildCategoriesFromCatalog()
    {
        _barterCats.Clear();
        _buyCats.Clear();
        _sellCats.Clear();

        _scratchBarterCatSet.Clear();
        _scratchBuyCatSet.Clear();
        _scratchSellCatSet.Clear();

        var catalog = _catalogModel.Catalog;
        for (var i = 0; i < catalog.Count; i++)
        {
            var it = catalog[i];
            if (string.IsNullOrWhiteSpace(it.Category))
                continue;

            if (it.Mode == StoreMode.Buy)
                _scratchBuyCatSet.Add(it.Category);
            else if (it.Mode == StoreMode.Sell)
                _scratchSellCatSet.Add(it.Category);
            else if (it.Mode == StoreMode.Barter)
                _scratchBarterCatSet.Add(it.Category);
        }

        _barterCats.AddRange(_scratchBarterCatSet);
        _buyCats.AddRange(_scratchBuyCatSet);
        _sellCats.AddRange(_scratchSellCatSet);

        _barterCats.Sort(static (a, b) => string.Compare(a, b, StringComparison.CurrentCulture));
        _buyCats.Sort(static (a, b) => string.Compare(a, b, StringComparison.CurrentCulture));
        _sellCats.Sort(static (a, b) => string.Compare(a, b, StringComparison.CurrentCulture));

        BuildCategoryButtons();
    }

    private void UpdateVirtualSellCategories()
    {
        var hasReady = false;
        var hasCrate = false;

        var items = _catalogModel.Items;
        for (var i = 0; i < items.Count; i++)
        {
            var it = items[i];

            if (!hasReady && it is { Mode: StoreMode.Sell, Category: NcStoreClientCatalogModel.CatIdReady, })
                hasReady = true;

            if (!hasCrate && it is { Mode: StoreMode.Sell, Category: NcStoreClientCatalogModel.CatIdCrate, })
                hasCrate = true;

            if (hasReady && hasCrate)
                break;
        }

        _sellCats.Remove(NcStoreClientCatalogModel.CatIdReady);
        _sellCats.Remove(NcStoreClientCatalogModel.CatIdCrate);

        var insertIndex = 0;
        if (hasReady)
            _sellCats.Insert(insertIndex++, NcStoreClientCatalogModel.CatIdReady);

        if (hasCrate)
            _sellCats.Insert(insertIndex, NcStoreClientCatalogModel.CatIdCrate);

        BuildCategoryButtons();
    }

    public void ApplyDynamicState(
        Dictionary<string, int> balancesByCurrency,
        Dictionary<string, int> remainingById,
        Dictionary<string, int> ownedById,
        Dictionary<string, int> crateUnitsById,
        Dictionary<string, int> massTotals,
        bool hasBuyTab,
        bool hasSellTab,
        bool hasBarterTab,
        bool hasContractsTab,
        List<ContractClientData> contracts,
        int contractSkipCost,
        string contractSkipCurrency,
        bool isSparseDynamicSnapshot,
        List<string> snapshotScopeIds
    ) =>
        _binder.ApplyDynamicState(
            balancesByCurrency,
            remainingById,
            ownedById,
            crateUnitsById,
            massTotals,
            hasBuyTab,
            hasSellTab,
            hasBarterTab,
            hasContractsTab,
            contracts,
            contractSkipCost,
            contractSkipCurrency,
            isSparseDynamicSnapshot,
            snapshotScopeIds);


    private void RebuildItemsFromCatalogAndDynamic()
    {
        _catalogModel.RebuildItemsFromCatalogAndDynamic();
        BuyView.SyncAvailableIds(_catalogModel.AvailableIds);
        SellView.SyncAvailableIds(_catalogModel.AvailableIds);
        BarterView.SyncAvailableIds(_catalogModel.AvailableIds);
    }

    private void RefreshListings()
    {
        var items = _catalogModel.Items;
        BuyView.BindListingsData(items, GetBalanceForCurrency, (d, qty) => OnBuyPressed?.Invoke(d, qty));
        SellView.BindListingsData(items, static _ => int.MaxValue, (d, qty) => OnSellPressed?.Invoke(d, qty));
        BarterView.BindListingsData(items, static _ => int.MaxValue, (d, qty) => OnBarterPressed?.Invoke(d, qty));

        BuyView.SetSearch(_searchLower);
        SellView.SetSearch(_searchLower);
        BarterView.SetSearch(_searchLower);
    }

    private void BuildCategoryButtons()
    {
        BuyView.SetCategories(_buyCats);
        SellView.SetCategories(_sellCats);
        BarterView.SetCategories(_barterCats);
    }

    private string CurrencyName(string? currencyId)
    {
        if (string.IsNullOrWhiteSpace(currencyId))
            return string.Empty;

        if (_proto.TryIndex<StackPrototype>(currencyId, out var stackProto) &&
            _proto.TryIndex<EntityPrototype>(stackProto.Spawn, out var currencyEnt))
            return currencyEnt.Name;

        return currencyId;
    }

    public void CleanupBeforeClose()
    {
        if (_closed)
            return;

        _closed = true;

        CloseActiveContractConfirmWindow();
        BuyView.ClearCaches();
        SellView.ClearCaches();
        BarterView.ClearCaches();
        _catalogModel.Clear();
        _balancesByCurrency.Clear();
        _massSellTotals.Clear();
        _visibleBuyIds.Clear();
        _visibleSellIds.Clear();
        _visibleBarterIds.Clear();
        _visibleUnionScratch.Clear();
        _lastVisibleIdsSig = 0UL;
    }
}
