using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.BsEnergy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.BsEnergy;

[GenerateTypedNameReferences]
public sealed partial class BsTransmitterWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly string _minuteLocStr = Loc.GetString("ui-bs-energy-time-minute");
    private readonly string _balanceLocStr = Loc.GetString("ui-bs-transmitter-money-label");
    private int _maxValue;
    private int _stepSize;
    private int _power;

    public event Action<int>? OnChangeTargetPower;
    public event Action<int>? OnPriceChanged;
    public event Action<BaseButton.ButtonEventArgs>? OnEnableToggle;
    public event Action? OnWithdraw;

    public BsTransmitterWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CurrentSupplyLabel.Text = Loc.GetString("ui-bs-energy-network-value", ("watts", 0));
        PowerConsumerLabel.Text = Loc.GetString("ui-bs-energy-network-value", ("watts", 0));
        TargetPowerLabel.Text = Loc.GetString("ui-bs-energy-network-value", ("watts", 0));
        NetworkStatsLabel.Text = Loc.GetString("ui-bs-energy-unanchored");
        ExpectedIncomeLabel.Text = $"$0 / {_minuteLocStr}";

        PriceSpinBox.IsValid = val => val >= 0;
        PriceSpinBox.LineEditControl.PlaceHolder = $"{BsEnergySettings.PassiveIncome}";

        EnableButton.OnPressed += args => OnEnableToggle?.Invoke(args);
        WithdrawButton.OnPressed += _ => OnWithdraw?.Invoke();
        PriceSpinBox.ValueChanged += args => OnPriceChanged?.Invoke(args.Value);
    }

    public void SetEntity(EntityUid uid)
    {
        SpriteViewControl.SetEntity(uid);
    }

    public void UpdateUI(BsTransmitterInterfaceStateMessage stateMessage)
    {
        if (_maxValue == 0 && stateMessage.MaxValue > 0)
            _maxValue = stateMessage.MaxValue;

        if (_stepSize == 0 && stateMessage.MaxValue > 0)
        {
            _stepSize = stateMessage.StepSize;
            RequestedPowerIncreaseButton.Text = Loc.GetString("ui-bs-energy-step-increase", ("watts", _stepSize));
            RequestedPowerDecreaseButton.Text = Loc.GetString("ui-bs-energy-step-decrease", ("watts", _stepSize));

            RequestedPowerIncreaseButton.OnPressed += _ => RequestedPowerChanged(_stepSize);
            RequestedPowerDecreaseButton.OnPressed += _ => RequestedPowerChanged(-1 * _stepSize);
        }

        _power = stateMessage.TargetPower;
        EnableButton.Pressed = stateMessage.Enabled;
        ExpectedIncomeLabel.Text = $"${stateMessage.Income:F0} / {_minuteLocStr}";
        ConnectedDevicesLabel.Text = $"{stateMessage.ConnectedCount} / {stateMessage.MaxConnected}";
        TotalMoneyLabel.Text = $"{_balanceLocStr} ${stateMessage.Money:F0}";
        PowerConsumerLabel.Text = Loc.GetString("ui-bs-energy-network-value", ("watts", stateMessage.PowerConsumer));
        TargetPowerLabel.Text = Loc.GetString("ui-bs-energy-network-value", ("watts", stateMessage.TargetPower));
        CurrentSupplyLabel.Text = Loc.GetString("ui-bs-energy-network-value", ("watts", stateMessage.AvailablePower));

        if (stateMessage.NetworkStats is { } netStats)
        {
            NetworkStatsLabel.Text = Loc.GetString("ui-bs-energy-network-stats-value", ("load", netStats.Load), ("supply", netStats.Supply));

            var good = netStats.Load <= netStats.Supply;
            NetworkStatsLabel.SetOnlyStyleClass(good ? "Good" : "Caution");
        }
        else
        {
            NetworkStatsLabel.Text = Loc.GetString("ui-bs-energy-unanchored");
            NetworkStatsLabel.StyleClasses.Clear();
        }

        if (!PriceSpinBox.LineEditControl.HasKeyboardFocus())
            PriceSpinBox.OverrideValue(stateMessage.Price);
    }

    private void RequestedPowerChanged(int watts)
    {
        if (_maxValue == 0)
            return;

        var newVal = _power + watts;
        _power = newVal < _maxValue ? Math.Max(0, newVal) : _maxValue;
        OnChangeTargetPower?.Invoke(_power);
    }
}
