using Content.Shared._Forge.WallPaint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Forge.WallPaint.UI;

[GenerateTypedNameReferences]
public sealed partial class WallPaintWindow : DefaultWindow
{
    [Dependency] private IEntityManager _entity = default!;

    private WallPaintPlacementSystem _wallPaint = default!;

    public WallPaintWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _wallPaint = _entity.System<WallPaintPlacementSystem>();
        ColorPicker.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv;
        ColorPicker.Color = _wallPaint.Color;
        ErasePaint.Pressed = _wallPaint.Erase;

        ColorPicker.OnColorChanged += color =>
        {
            var clamped = WallPaintColor.Clamp(color);
            if (!MathHelper.CloseToPercent(color, clamped))
                ColorPicker.Color = clamped;

            _wallPaint.SetColor(clamped);
        };

        ErasePaint.OnToggled += args => _wallPaint.SetErase(args.Pressed);
    }

    protected override void Opened()
    {
        base.Opened();
        _wallPaint.SetActive(true);
    }

    public override void Close()
    {
        base.Close();
        _wallPaint.Deactivate();
    }

    protected override void Dispose(bool disposing)
    {
        _wallPaint.Deactivate();
        base.Dispose(disposing);
    }
}
