using Content.Client.Message;
using Content.Shared._Forge.Genetics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.Genetics.UI;

[GenerateTypedNameReferences]
public sealed partial class GeneticsConsoleWindow : DefaultWindow
{
    private static readonly Color GoodColor = Color.FromHex("#7DDE7D");
    private static readonly Color BadColor = Color.FromHex("#E07A7A");
    private static readonly Color NeutralColor = Color.FromHex("#A8A8A8");
    private static readonly Color OkColor = Color.FromHex("#88CC88");
    private static readonly Color WarnColor = Color.FromHex("#E0B45A");
    private static readonly Color ErrorColor = Color.FromHex("#E07A7A");
    private static readonly Color ExpressedColor = Color.FromHex("#C8E070");

    private readonly Dictionary<string, GeneticsConsoleBranchEntry> _branches = new();
    private GeneticsConsoleBoundUserInterfaceState? _state;

    public string? SelectedGeneId { get; private set; }

    public event Action<int>? OnPulseBlock;
    public event Action<string, bool>? OnPrintJournal;

    public GeneticsConsoleWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        MainTabs.SetTabTitle(0, Loc.GetString("genetics-console-tab-work"));
        MainTabs.SetTabTitle(1, Loc.GetString("genetics-console-tab-journal"));
    }

    public void Populate(GeneticsConsoleBoundUserInterfaceState state)
    {
        _state = state;
        PopulateStatus(state);
        PopulateBranches(state);
        PopulateDiscoveries(state);
        PopulateSelectedBranch();
        UpdateActionButtons();
    }

    private void PopulateStatus(GeneticsConsoleBoundUserInterfaceState state)
    {
        OccupantLabel.Text = state.OccupantPresent
            ? Loc.GetString("genetics-console-occupant", ("name", state.OccupantName))
            : Loc.GetString("genetics-console-occupant-none");

        UniqueDnaLabel.Text = state.OccupantPresent && !string.IsNullOrEmpty(state.UniqueDna)
            ? Loc.GetString("genetics-console-unique-dna", ("dna", state.UniqueDna))
            : Loc.GetString("genetics-console-unique-dna-none");

        if (state.OccupantPresent)
        {
            InstabilityLabel.Text = Loc.GetString("genetics-console-instability",
                ("current", state.Instability),
                ("threshold", state.InstabilityThreshold));
            InstabilityLabel.FontColorOverride = state.Instability >= state.InstabilityThreshold
                ? ErrorColor
                : OkColor;
        }
        else
        {
            InstabilityLabel.Text = Loc.GetString("genetics-console-instability-none");
            InstabilityLabel.FontColorOverride = NeutralColor;
        }

        if (state.ScannerConnected)
        {
            MutagenLabel.Text = Loc.GetString("genetics-console-mutagen",
                ("current", state.Mutagen.ToString("0")),
                ("max", state.MutagenMax.ToString("0")),
                ("cost", state.IrradiateCost.ToString("0")),
                ("pulse", state.PulseCost.ToString("0")));
            MutagenLabel.FontColorOverride = state.Mutagen < state.IrradiateCost
                ? ErrorColor
                : state.Mutagen < state.IrradiateCost * 3
                    ? WarnColor
                    : OkColor;
        }
        else
        {
            MutagenLabel.Text = Loc.GetString("genetics-console-mutagen-none");
            MutagenLabel.FontColorOverride = NeutralColor;
        }

        if (!state.Powered)
        {
            ScannerStatusLabel.Text = Loc.GetString("genetics-console-unpowered");
            ScannerStatusLabel.FontColorOverride = ErrorColor;
        }
        else if (!state.ScannerConnected)
        {
            ScannerStatusLabel.Text = Loc.GetString("genetics-console-scanner-disconnected");
            ScannerStatusLabel.FontColorOverride = ErrorColor;
        }
        else if (!state.ScannerInRange)
        {
            ScannerStatusLabel.Text = Loc.GetString("genetics-console-scanner-out-of-range");
            ScannerStatusLabel.FontColorOverride = WarnColor;
        }
        else if (!state.OccupantPresent)
        {
            ScannerStatusLabel.Text = Loc.GetString("genetics-console-scanner-empty");
            ScannerStatusLabel.FontColorOverride = NeutralColor;
        }
        else
        {
            ScannerStatusLabel.Text = Loc.GetString("genetics-console-scanner-connected");
            ScannerStatusLabel.FontColorOverride = OkColor;
        }
    }

    private void PopulateBranches(GeneticsConsoleBoundUserInterfaceState state)
    {
        _branches.Clear();
        foreach (var branch in state.Branches)
            _branches[branch.Id] = branch;

        if (SelectedGeneId != null && !_branches.ContainsKey(SelectedGeneId))
            SelectedGeneId = null;

        GeneList.DisposeAllChildren();

        var hasBranches = state.Branches.Count > 0;
        NoGenesLabel.Visible = !hasBranches;
        GeneListScroll.Visible = hasBranches;

        if (!hasBranches)
            return;

        var group = new ButtonGroup();
        foreach (var branch in state.Branches)
        {
            var button = new Button
            {
                Text = Loc.GetString("genetics-console-gene-list-entry",
                    ("branch", Loc.GetString($"genetics-branch-{branch.Branch.ToString().ToLowerInvariant()}")),
                    ("sequence", DnaSequence.Format(branch.Sequence))),
                ToggleMode = true,
                Group = group,
                HorizontalExpand = true,
                TextAlign = Label.AlignMode.Left,
                ClipText = true,
                Margin = new Thickness(0, 1),
                Pressed = branch.Id == SelectedGeneId,
            };
            button.Label.FontColorOverride = branch.Expressed ? ExpressedColor : NeutralColor;

            var branchId = branch.Id;
            button.OnPressed += _ =>
            {
                SelectedGeneId = branchId;
                PopulateSelectedBranch();
                UpdateActionButtons();
            };

            GeneList.AddChild(button);
        }
    }

    private void PopulateDiscoveries(GeneticsConsoleBoundUserInterfaceState state)
    {
        DiscoveryList.DisposeAllChildren();
        var has = state.Discoveries.Count > 0;
        NoDiscoveriesLabel.Visible = !has;
        DiscoveryScroll.Visible = has;
        if (!has)
            return;

        var canPrint = state.Powered;
        foreach (var entry in state.Discoveries)
        {
            var color = entry.Quality switch
            {
                GeneQuality.Good => GoodColor,
                GeneQuality.Bad => BadColor,
                _ => NeutralColor,
            };

            var box = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 8),
            };

            box.AddChild(new Label
            {
                Text = Loc.GetString("genetics-console-journal-entry",
                    ("name", entry.Name),
                    ("branch", Loc.GetString($"genetics-branch-{entry.Branch.ToString().ToLowerInvariant()}")),
                    ("sequence", entry.Sequence)),
                FontColorOverride = color,
                HorizontalExpand = true,
            });

            var desc = new RichTextLabel { HorizontalExpand = true };
            desc.SetMarkupPermissive(Loc.GetString("genetics-console-journal-desc", ("desc", entry.Description)));
            box.AddChild(desc);

            var buttons = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 4,
            };

            var geneId = entry.GeneId;
            var isolate = new Button
            {
                Text = Loc.GetString("genetics-console-journal-print"),
                HorizontalExpand = true,
                Disabled = !canPrint,
            };
            isolate.OnPressed += _ => OnPrintJournal?.Invoke(geneId, true);

            var clean = new Button
            {
                Text = Loc.GetString("genetics-console-journal-clean"),
                HorizontalExpand = true,
                Disabled = !canPrint,
            };
            clean.OnPressed += _ => OnPrintJournal?.Invoke(geneId, false);

            buttons.AddChild(isolate);
            buttons.AddChild(clean);
            box.AddChild(buttons);
            DiscoveryList.AddChild(box);
        }
    }

    private void PopulateSelectedBranch()
    {
        if (SelectedGeneId is not { } id || !_branches.TryGetValue(id, out var branch))
        {
            SelectGeneLabel.Visible = true;
            GeneDetails.Visible = false;
            HintLegendLabel.Visible = false;
            CodonBar.DisposeAllChildren();
            return;
        }

        SelectGeneLabel.Visible = false;
        GeneDetails.Visible = true;

        GeneNameLabel.Text = branch.Title;
        GeneNameLabel.FontColorOverride = branch.Expressed ? ExpressedColor : NeutralColor;
        GeneDescriptionLabel.SetMarkupPermissive(branch.Description);
        GeneActiveLabel.Text = Loc.GetString(branch.Expressed
            ? "genetics-console-gene-active"
            : "genetics-console-gene-inactive");
        GeneBranchLabel.Text = Loc.GetString("genetics-console-gene-branch",
            ("branch", Loc.GetString($"genetics-branch-{branch.Branch.ToString().ToLowerInvariant()}")));
        GeneSequenceLabel.Text = Loc.GetString("genetics-console-gene-sequence",
            ("sequence", DnaSequence.Format(branch.Sequence)));
        HintLegendLabel.Visible = branch.BlockHints.Count > 0;
        HintLegendLabel.Text = Loc.GetString("genetics-console-hint-legend");

        RebuildCodonBar(branch);
    }

    private void UpdateActionButtons()
    {
        if (_state is not { } state)
        {
            SetOccupantActionsDisabled(true);
            EjectButton.Disabled = true;
            return;
        }

        var occupantReady = state.Powered && state.OccupantPresent && state.ScannerInRange;
        SetOccupantActionsDisabled(!occupantReady);
        IrradiateButton.Disabled = !occupantReady || state.OccupantCritical || state.Mutagen < state.IrradiateCost;

        var selected = SelectedGeneId != null && _branches.TryGetValue(SelectedGeneId, out var branch)
            ? branch
            : null;

        ActivateButton.Disabled = !occupantReady || selected == null;
        DeactivateButton.Disabled = !occupantReady || selected is not { CanDeactivate: true };
        IsolateButton.Disabled = !occupantReady || selected is not { CanIsolate: true };
        CleanButton.Disabled = !occupantReady || selected is not { CanClean: true };

        EjectButton.Disabled = !state.Powered || !state.ScannerConnected;
    }

    private void RebuildCodonBar(GeneticsConsoleBranchEntry branch)
    {
        CodonBar.DisposeAllChildren();
        for (var i = 0; i < branch.Sequence.Count; i++)
        {
            var codon = branch.Sequence[i];
            var index = i;
            var hint = i < branch.BlockHints.Count ? (GeneBlockHint) branch.BlockHints[i] : GeneBlockHint.None;
            var canPulse = _state is { Powered: true, OccupantPresent: true, ScannerInRange: true, OccupantCritical: false }
                           && _state.Mutagen >= _state.PulseCost;
            var button = new Button
            {
                Text = codon,
                MinWidth = 40,
                Disabled = !canPulse,
                ToolTip = Loc.GetString(hint switch
                {
                    GeneBlockHint.OnTrack => "genetics-console-codon-tooltip-on",
                    GeneBlockHint.OffTrack => "genetics-console-codon-tooltip-off",
                    _ => branch.BlockHints.Count > 0
                        ? "genetics-console-codon-tooltip-none"
                        : "genetics-console-codon-tooltip",
                }),
            };
            button.Label.FontColorOverride = hint switch
            {
                GeneBlockHint.OnTrack => GoodColor,
                GeneBlockHint.OffTrack => WarnColor,
                _ => branch.BlockHints.Count > 0 ? Color.White : NeutralColor,
            };
            button.OnPressed += _ => OnPulseBlock?.Invoke(index);
            CodonBar.AddChild(button);

            if (i < branch.Sequence.Count - 1)
            {
                CodonBar.AddChild(new Label
                {
                    Text = "-",
                    VerticalAlignment = VAlignment.Center,
                    FontColorOverride = NeutralColor,
                });
            }
        }
    }

    private void SetOccupantActionsDisabled(bool disabled)
    {
        IrradiateButton.Disabled = disabled;
        ActivateButton.Disabled = disabled;
        DeactivateButton.Disabled = disabled;
        IsolateButton.Disabled = disabled;
        CleanButton.Disabled = disabled;
    }
}
