using Content.Client._Forge.UserInterface; // Forge-Change
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Ghost.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Configuration;
using Content.Client._NF.CryoSleep; // Frontier

namespace Content.Client.UserInterface.Systems.Ghost.Widgets;

[GenerateTypedNameReferences]
public sealed partial class GhostGui : UIWidget
{
    [Dependency] private IGameTiming _gameTiming = default!;
    [Dependency] private IConfigurationManager _configurationManager = default!;

    private TimeSpan? _respawnTime;

    public GhostTargetWindow TargetWindow { get; }
    public GhostRespawnRulesWindow RulesWindow { get; }
    public CryosleepWakeupWindow CryosleepWakeupWindow { get; } // Frontier

    public event Action? RequestWarpsPressed;
    public event Action? ReturnToBodyPressed;
    public event Action? GhostRolesPressed;
    public event Action? GhostRespawnPressed;

    public GhostGui()
    {
        RobustXamlLoader.Load(this);

        TargetWindow = new GhostTargetWindow();
        RulesWindow = new GhostRespawnRulesWindow();
        CryosleepWakeupWindow = new CryosleepWakeupWindow(); // Frontier
        RulesWindow.RespawnButton.OnPressed += _ => GhostRespawnPressed?.Invoke();

        MouseFilter = MouseFilterMode.Ignore;

        GhostWarpButton.OnPressed += _ => RequestWarpsPressed?.Invoke();
        ReturnToBodyButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesPressed?.Invoke();
        GhostRespawnButton.OnPressed += _ => RulesWindow.OpenCentered();
        CryosleepReturnButton.OnPressed += _ => CryosleepWakeupWindow.OpenCentered(); // Frontier
        // Forge-Change-Start
        ForgeUiSizing.EnsureInitialized();
        ApplyHudScale();
        // Forge-Change-End
    }

    // Forge-Change-Start
    protected override void EnteredTree()
    {
        base.EnteredTree();
        ForgeUiSizing.HudScaleChanged += ApplyHudScale;
    }

    protected override void ExitedTree()
    {
        ForgeUiSizing.HudScaleChanged -= ApplyHudScale;
        base.ExitedTree();
    }

    private void ApplyHudScale()
    {
        var height = 28f * ForgeUiSizing.HudScale;
        ReturnToBodyButton.MinHeight = height;
        GhostWarpButton.MinHeight = height;
        GhostRolesButton.MinHeight = height;
        GhostRespawnButton.MinHeight = height;
        CryosleepReturnButton.MinHeight = height;
    }
    // Forge-Change-End

    public void Hide()
    {
        TargetWindow.Close();
        Visible = false;
    }

    public void UpdateRespawn(TimeSpan? respawnTime)
    {
        _respawnTime = respawnTime;
    }

    public void Update(int? roles, bool? canReturnToBody, bool canUncryo)
    {
        ReturnToBodyButton.Disabled = !canReturnToBody ?? true;

        if (roles != null)
        {
            var rolesText = Loc.GetString("ghost-gui-ghost-roles-button", ("count", roles));
            // Button.Text always invalidates measure, even when the string is unchanged.
            if (GhostRolesButton.Text != rolesText)
                GhostRolesButton.Text = rolesText;

            if (roles > 0)
            {
                GhostRolesButton.StyleClasses.Add(StyleBase.ButtonCaution);
            }
            else
            {
                GhostRolesButton.StyleClasses.Remove(StyleBase.ButtonCaution);
            }
        }

        // Rebuilding every warp button dirties the UI even while the window is closed.
        if (TargetWindow.IsOpen)
            TargetWindow.Populate();

        CryosleepReturnButton.Disabled = !canUncryo;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        string text;
        bool disabled;

        if (_respawnTime is null || _gameTiming.CurTime > _respawnTime)
        {
            text = Loc.GetString("ghost-gui-respawn-button-allowed");
            disabled = false;
        }
        else
        {
            double delta = (_respawnTime.Value - _gameTiming.CurTime).TotalSeconds;
            text = Loc.GetString("ghost-gui-respawn-button-denied", ("time", $"{delta:f1}"));
            disabled = true;
        }

        // This runs every frame while ghosted. An unchanged label still invalidates the whole HUD.
        if (GhostRespawnButton.Text != text)
            GhostRespawnButton.Text = text;

        if (GhostRespawnButton.Disabled != disabled)
            GhostRespawnButton.Disabled = disabled;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            TargetWindow.Dispose();
        }
    }
}
