// Forge-Change-full
using Content.Client.Humanoid;
using Content.Shared._EE.Contractors.Prototypes;
using Content.Shared._EE.Contractors.Systems;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Inventory;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;

namespace Content.Client._Forge.Contractors.UI;

[GenerateTypedNameReferences]
public sealed partial class PassportDocumentControl : BoxContainer
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private static readonly Color PaperInk = Color.FromHex("#1A120C");
    private static readonly Color PaperMuted = Color.FromHex("#6B5535");

    private EntityUid? _photoDummy;

    public PassportDocumentControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        PhotoView.Stretch = SpriteView.StretchMode.Fit;
    }

    public void UpdateFromProfile(HumanoidCharacterProfile? profile, string pid)
    {
        ApplyTheme(profile?.Nationality);

        if (profile == null)
        {
            ShowUnregistered(pid);
            return;
        }

        PhotoMissingLabel.Visible = false;
        PhotoView.Visible = true;

        var (surname, given) = SplitName(profile.Name);
        var nationalityName = GetNationalityName(profile.Nationality);
        var code = GetNationalityCode(profile.Nationality);
        var speciesName = GetSpeciesName(profile.Species);
        var yearOfBirth = SharedPassportSystem.CurrentYear - profile.Age;
        var height = GetHeightCm(profile);

        CountryLabel.Text = FormatBannerCountry(nationalityName);
        PhotoCodeLabel.Text = code;
        TypeValueLabel.Text = Loc.GetString("passport-ui-type-value");
        CodeValueLabel.Text = code;
        NumberValueLabel.Text = string.IsNullOrEmpty(pid)
            ? Loc.GetString("passport-ui-unregistered")
            : pid;
        SurnameLabel.Text = surname.ToUpperInvariant();
        GivenNamesLabel.Text = given;
        NationalityLabel.Text = nationalityName;
        SpeciesLabel.Text = speciesName;
        BirthLabel.Text = Loc.GetString("passport-ui-year-value", ("year", yearOfBirth));
        SexLabel.Text = LocSex(profile.Sex);
        HeightLabel.Text = Loc.GetString("passport-ui-height-value", ("height", height));
        AuthorityLabel.Text = Loc.GetString("passport-ui-authority-value");

        BuildMrz(code, surname, given, pid, yearOfBirth, profile.Sex);
        ReloadPhoto(profile);
    }

    public void Clear()
    {
        ShowUnregistered(string.Empty);
    }

    private void ShowUnregistered(string pid)
    {
        PhotoView.Visible = false;
        PhotoMissingLabel.Visible = true;
        DeletePhotoDummy();

        CountryLabel.Text = FormatBannerCountry(Loc.GetString("passport-ui-unregistered"));
        PhotoCodeLabel.Text = "---";
        TypeValueLabel.Text = Loc.GetString("passport-ui-type-value");
        CodeValueLabel.Text = "XXX";
        NumberValueLabel.Text = string.IsNullOrEmpty(pid) ? "---------------" : pid;
        SurnameLabel.Text = "-----";
        GivenNamesLabel.Text = "-----";
        NationalityLabel.Text = Loc.GetString("passport-ui-unregistered");
        SpeciesLabel.Text = "-----";
        BirthLabel.Text = "----";
        SexLabel.Text = "-----";
        HeightLabel.Text = "-----";
        AuthorityLabel.Text = Loc.GetString("passport-ui-unregistered");
        MrzLine1Label.Text = "P<XXX<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<";
        MrzLine2Label.Text = "<<<<<<<<<<<<<<<XXX<<<<<<<<<<<<<<<<<<<<<<";
    }

    private void ApplyTheme(string? nationality)
    {
        var theme = GetTheme(nationality);

        PaperRoot.PanelOverride = Box(theme.Page, theme.Gold, 2);
        BannerPanel.PanelOverride = Box(theme.Leather);
        PhotoOuterFrame.PanelOverride = Box(Color.FromHex("#2A2118"), theme.Gold, 3);
        MrzPanel.PanelOverride = Box(Color.FromHex("#1F1812"));

        CountryLabel.FontColorOverride = theme.Gold;
        DocumentTitleLabel.FontColorOverride = theme.Page;
        PhotoCaptionLabel.FontColorOverride = PaperMuted;
        PhotoCodeLabel.FontColorOverride = PaperMuted;

        foreach (var label in new[]
                 {
                     TypeValueLabel, CodeValueLabel, NumberValueLabel, SurnameLabel, GivenNamesLabel,
                     NationalityLabel, SpeciesLabel, BirthLabel, SexLabel, HeightLabel, AuthorityLabel
                 })
        {
            label.FontColorOverride = PaperInk;
        }
    }

    private void ReloadPhoto(HumanoidCharacterProfile profile)
    {
        DeletePhotoDummy();

        if (!_prototypeManager.TryIndex<SpeciesPrototype>(profile.Species, out var species))
            return;

        var dummy = _entityManager.SpawnEntity(species.DollPrototype, MapCoordinates.Nullspace);
        _entityManager.System<HumanoidAppearanceSystem>().LoadProfile(dummy, profile);
        _entityManager.System<MetaDataSystem>().SetEntityName(dummy, profile.Name);
        DressPhotoDummy(dummy, profile.Nationality);

        _photoDummy = dummy;
        PhotoView.SetEntity(dummy);
        PhotoView.Modulate = new Color(1f, 0.96f, 0.9f);
    }

    private void DressPhotoDummy(EntityUid dummy, string? nationality)
    {
        var inventory = _entityManager.System<InventorySystem>();
        var (jumpsuit, shoes) = GetNationalityOutfit(nationality);
        TryEquipPhotoSlot(dummy, inventory, "jumpsuit", jumpsuit);
        TryEquipPhotoSlot(dummy, inventory, "shoes", shoes);
    }

    private void TryEquipPhotoSlot(EntityUid dummy, InventorySystem inventory, string slot, EntProtoId prototype)
    {
        if (!_prototypeManager.HasIndex(prototype))
            return;

        var item = _entityManager.SpawnEntity(prototype, MapCoordinates.Nullspace);
        if (!inventory.TryEquip(dummy, item, slot, silent: true, force: true))
            _entityManager.DeleteEntity(item);
    }

    private static (EntProtoId Jumpsuit, EntProtoId Shoes) GetNationalityOutfit(string? nationality)
    {
        return nationality switch
        {
            "TransSolarFederation" => ("ClothingUniformTSFMCDress", "ClothingShoesBootsJack"),
            "Imperial" => ("ClothingUniformJumpsuitEmpireConsul", "ClothingShoesLeather"),
            "USSP" => ("ClothingUniformServiceDressUSSP", "ClothingShoesBootsJack"),
            "FreeColonies" => ("ClothingUniformJumpsuitMilitaryMerc", "ClothingShoesBootsWork"),
            _ => ("ClothingUniformJumpsuitColorGrey", "ClothingShoesColorBlack"),
        };
    }

    private void DeletePhotoDummy()
    {
        if (_photoDummy == null)
            return;

        _entityManager.DeleteEntity(_photoDummy.Value);
        _photoDummy = null;
        PhotoView.SetEntity(null);
    }

    private void BuildMrz(string code, string surname, string given, string pid, int yearOfBirth, Sex sex)
    {
        var sexChar = sex switch
        {
            Sex.Male => "M",
            Sex.Female => "F",
            _ => "X",
        };

        MrzLine1Label.Text = PadMrz($"P<{SanitizeMrz(code)}<{SanitizeMrz(surname)}<<{SanitizeMrz(given)}", 44);
        MrzLine2Label.Text = PadMrz($"{SanitizeMrz(pid.Replace("-", string.Empty))}{SanitizeMrz(code)}{yearOfBirth % 100:00}{sexChar}", 44);
    }

    private static string SanitizeMrz(string value)
    {
        var chars = new char[value.Length];
        var n = 0;
        foreach (var c in value.ToUpperInvariant())
        {
            if (char.IsLetterOrDigit(c))
                chars[n++] = c;
            else if (c is ' ' or '-')
                chars[n++] = '<';
        }

        return n == 0 ? string.Empty : new string(chars, 0, n);
    }

    private static string PadMrz(string value, int length)
    {
        if (value.Length >= length)
            return value[..length];

        return value.PadRight(length, '<');
    }

    private static (string Surname, string Given) SplitName(string name)
    {
        var parts = name.Trim().Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length == 0)
            return ("-----", "-----");
        if (parts.Length == 1)
            return (parts[0], parts[0]);

        return (parts[^1], string.Join(' ', parts[..^1]));
    }

    private string GetNationalityName(string nationality)
    {
        if (_prototypeManager.TryIndex<NationalityPrototype>(nationality, out var proto))
            return Loc.GetString(proto.NameKey);

        return nationality;
    }

    public static string GetNationalityCode(string? nationality)
    {
        return nationality switch
        {
            "TransSolarFederation" => "TSF",
            "Imperial" => "IMP",
            "USSP" => "SSP",
            "FreeColonies" => "FCL",
            _ => "XXX",
        };
    }

    private string GetSpeciesName(string species)
    {
        if (_prototypeManager.TryIndex<SpeciesPrototype>(species, out var proto))
            return Loc.GetString(proto.Name);

        return species;
    }

    private static string LocSex(Sex sex)
    {
        return sex switch
        {
            Sex.Male => Loc.GetString("humanoid-profile-editor-sex-male-text"),
            Sex.Female => Loc.GetString("humanoid-profile-editor-sex-female-text"),
            _ => Loc.GetString("humanoid-profile-editor-sex-unsexed-text"),
        };
    }

    private int GetHeightCm(HumanoidCharacterProfile profile)
    {
        if (!_prototypeManager.TryIndex<SpeciesPrototype>(profile.Species, out var species))
            return (int) MathF.Round(profile.Appearance.Height * 176.1f);

        return (int) MathF.Round(profile.Appearance.Height * species.AverageHeight);
    }

    public static PassportTheme GetTheme(string? nationality)
    {
        return nationality switch
        {
            "TransSolarFederation" => new PassportTheme(
                Color.FromHex("#1B365D"),
                Color.FromHex("#C9A227"),
                Color.FromHex("#E7D7B6")),
            "Imperial" => new PassportTheme(
                Color.FromHex("#5C1212"),
                Color.FromHex("#D4AF37"),
                Color.FromHex("#F1DEC0")),
            "USSP" => new PassportTheme(
                Color.FromHex("#7A1616"),
                Color.FromHex("#FFD54A"),
                Color.FromHex("#F0D9B5")),
            "FreeColonies" => new PassportTheme(
                Color.FromHex("#1F4D3A"),
                Color.FromHex("#A8D5A2"),
                Color.FromHex("#E4EEDF")),
            _ => new PassportTheme(
                Color.FromHex("#3B1F1A"),
                Color.FromHex("#C9A227"),
                Color.FromHex("#E8D9B8")),
        };
    }

    private static string FormatBannerCountry(string name)
    {
        var upper = name.ToUpperInvariant();
        if (upper.Length <= 26)
            return upper;

        var mid = upper.Length / 2;
        var split = upper.LastIndexOf(' ', mid);
        if (split < 0)
            split = upper.IndexOf(' ', mid);
        if (split < 0)
            return upper;

        return upper[..split] + "\n" + upper[(split + 1)..];
    }

    private static StyleBoxFlat Box(Color background, Color? border = null, int thickness = 0)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border ?? background,
            BorderThickness = new Thickness(thickness),
        };
    }

    protected override void ExitedTree()
    {
        DeletePhotoDummy();
        base.ExitedTree();
    }

    public readonly record struct PassportTheme(Color Leather, Color Gold, Color Page);
}
