// Forge-Change-full
using Content.Client.Humanoid;
using Content.Shared._EE.Contractors.Prototypes;
using Content.Shared._EE.Contractors.Systems;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Inventory;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;

namespace Content.Client._Forge.Contractors.UI;

[GenerateTypedNameReferences]
public sealed partial class PassportPdaControl : BoxContainer
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private EntityUid? _photoDummy;

    public PassportPdaControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        PhotoView.Stretch = SpriteView.StretchMode.Fit;
    }

    public void UpdateFromProfile(HumanoidCharacterProfile? profile, string pid)
    {
        if (profile == null)
        {
            ShowBlank(pid);
            return;
        }

        PhotoMissingLabel.Visible = false;
        PhotoView.Visible = true;

        var nationalityName = GetNationalityName(profile.Nationality);
        var yearOfBirth = SharedPassportSystem.CurrentYear - profile.Age;
        var height = GetHeightCm(profile);

        StatusLabel.Text = Loc.GetString("passport-ui-pda-status-valid");
        NameValueLabel.Text = profile.Name;
        NationalityValueLabel.Text = nationalityName;
        SpeciesValueLabel.Text = GetSpeciesName(profile.Species);
        SexValueLabel.Text = LocSex(profile.Sex);
        BirthValueLabel.Text = Loc.GetString("passport-ui-year-value", ("year", yearOfBirth));
        HeightValueLabel.Text = Loc.GetString("passport-ui-height-value", ("height", height));
        NumberValueLabel.Text = string.IsNullOrEmpty(pid)
            ? Loc.GetString("passport-ui-unregistered")
            : pid;
        AuthLabel.Text = Loc.GetString("passport-ui-pda-auth");

        ReloadPhoto(profile);
    }

    public void Clear()
    {
        ShowBlank(string.Empty);
    }

    private void ShowBlank(string pid)
    {
        PhotoView.Visible = false;
        PhotoMissingLabel.Visible = true;
        DeletePhotoDummy();

        StatusLabel.Text = Loc.GetString("passport-ui-pda-status-blank");
        NameValueLabel.Text = Loc.GetString("passport-ui-unregistered");
        NationalityValueLabel.Text = "-----";
        SpeciesValueLabel.Text = "-----";
        SexValueLabel.Text = "-----";
        BirthValueLabel.Text = "----";
        HeightValueLabel.Text = "-----";
        NumberValueLabel.Text = string.IsNullOrEmpty(pid) ? "---------------" : pid;
        AuthLabel.Text = Loc.GetString("passport-ui-pda-auth-blank");
    }

    private void ReloadPhoto(HumanoidCharacterProfile profile)
    {
        DeletePhotoDummy();

        if (!_prototypeManager.TryIndex<SpeciesPrototype>(profile.Species, out var species))
            return;

        var dummy = _entityManager.SpawnEntity(species.DollPrototype, MapCoordinates.Nullspace);
        _entityManager.System<HumanoidAppearanceSystem>().LoadProfile(dummy, profile);
        _entityManager.System<MetaDataSystem>().SetEntityName(dummy, profile.Name);
        DressPhotoDummy(dummy, profile.Nationality);

        _photoDummy = dummy;
        PhotoView.SetEntity(dummy);
        PhotoView.Modulate = new Color(0.85f, 1f, 0.98f);
    }

    private void DressPhotoDummy(EntityUid dummy, string? nationality)
    {
        var inventory = _entityManager.System<InventorySystem>();
        var (jumpsuit, shoes) = GetNationalityOutfit(nationality);
        TryEquipPhotoSlot(dummy, inventory, "jumpsuit", jumpsuit);
        TryEquipPhotoSlot(dummy, inventory, "shoes", shoes);
    }

    private void TryEquipPhotoSlot(EntityUid dummy, InventorySystem inventory, string slot, EntProtoId prototype)
    {
        if (!_prototypeManager.HasIndex(prototype))
            return;

        var item = _entityManager.SpawnEntity(prototype, MapCoordinates.Nullspace);
        if (!inventory.TryEquip(dummy, item, slot, silent: true, force: true))
            _entityManager.DeleteEntity(item);
    }

    private static (EntProtoId Jumpsuit, EntProtoId Shoes) GetNationalityOutfit(string? nationality)
    {
        return nationality switch
        {
            "TransSolarFederation" => ("ClothingUniformTSFMCDress", "ClothingShoesBootsJack"),
            "Imperial" => ("ClothingUniformJumpsuitEmpireConsul", "ClothingShoesLeather"),
            "USSP" => ("ClothingUniformServiceDressUSSP", "ClothingShoesBootsJack"),
            "FreeColonies" => ("ClothingUniformJumpsuitMilitaryMerc", "ClothingShoesBootsWork"),
            _ => ("ClothingUniformJumpsuitColorGrey", "ClothingShoesColorBlack"),
        };
    }

    private void DeletePhotoDummy()
    {
        if (_photoDummy == null)
            return;

        _entityManager.DeleteEntity(_photoDummy.Value);
        _photoDummy = null;
        PhotoView.SetEntity(null);
    }

    private string GetNationalityName(string nationality)
    {
        if (_prototypeManager.TryIndex<NationalityPrototype>(nationality, out var proto))
            return Loc.GetString(proto.NameKey);

        return nationality;
    }

    private string GetSpeciesName(string species)
    {
        if (_prototypeManager.TryIndex<SpeciesPrototype>(species, out var proto))
            return Loc.GetString(proto.Name);

        return species;
    }

    private static string LocSex(Sex sex)
    {
        return sex switch
        {
            Sex.Male => Loc.GetString("humanoid-profile-editor-sex-male-text"),
            Sex.Female => Loc.GetString("humanoid-profile-editor-sex-female-text"),
            _ => Loc.GetString("humanoid-profile-editor-sex-unsexed-text"),
        };
    }

    private int GetHeightCm(HumanoidCharacterProfile profile)
    {
        if (!_prototypeManager.TryIndex<SpeciesPrototype>(profile.Species, out var species))
            return (int) MathF.Round(profile.Appearance.Height * 176.1f);

        return (int) MathF.Round(profile.Appearance.Height * species.AverageHeight);
    }

    protected override void ExitedTree()
    {
        DeletePhotoDummy();
        base.ExitedTree();
    }
}
