using Content.Shared._Forge.Features;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._Forge.Features.UI;

[GenerateTypedNameReferences]
public sealed partial class CombinationLockWindow : DefaultWindow
{
    public event Action<int>? OnKeypadPressed;
    public event Action? OnEnterPressed;
    public event Action? OnClearPressed;

    public CombinationLockWindow()
    {
        RobustXamlLoader.Load(this);
        FillKeypad();
    }

    private void FillKeypad()
    {
        for (var i = 1; i <= 9; i++)
            AddDigit(i);

        var clear = new Button { Text = Loc.GetString("remnant-lock-ui-clear") };
        clear.OnPressed += _ => OnClearPressed?.Invoke();
        KeypadGrid.AddChild(clear);

        AddDigit(0);

        var enter = new Button { Text = Loc.GetString("remnant-lock-ui-enter") };
        enter.OnPressed += _ => OnEnterPressed?.Invoke();
        KeypadGrid.AddChild(enter);
    }

    private void AddDigit(int value)
    {
        var button = new Button { Text = value.ToString() };
        button.OnPressed += _ => OnKeypadPressed?.Invoke(value);
        KeypadGrid.AddChild(button);
    }

    public void UpdateState(CombinationLockUiState state)
    {
        StatusLabel.Text = state.Status switch
        {
            CombinationLockUiStatus.Success => Loc.GetString("remnant-lock-ui-status-success"),
            CombinationLockUiStatus.Failure => Loc.GetString("remnant-lock-ui-status-failure"),
            _ => Loc.GetString("remnant-lock-ui-status-idle")
        };

        var filled = new string('*', Math.Max(0, state.EnteredLength));
        var blanks = new string('_', Math.Max(0, state.MaxLength - state.EnteredLength));
        CodeLabel.Text = filled + blanks;
    }
}
