using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.Features.UI;

[GenerateTypedNameReferences]
public sealed partial class RemnantConsoleWindow : DefaultWindow
{
    public event Action<int>? OnButtonPressed;

    public RemnantConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateButtons(List<string> labels)
    {
        ButtonContainer.DisposeAllChildren();
        for (var i = 0; i < labels.Count; i++)
        {
            var index = i;
            var button = new Button
            {
                Text = labels[i],
                HorizontalExpand = true
            };
            button.OnPressed += _ => OnButtonPressed?.Invoke(index);
            ButtonContainer.AddChild(button);
        }
    }
}
