- type: entity
  id: PortableGeneratorClunkerCircuitboard
  parent: BaseMachineCircuitboard
  name: Clunker portable generator machine board
  components:
    - type: Sprite
      state: makeshift
    - type: MachineBoard
      prototype: PortableGeneratorClunker
      requirements: # Frontier
        Capacitor: 1 # Frontier stackRequirements<requirements
      stackRequirements:
        Cable: 10
    - type: PhysicalComposition
      materialComposition:
        Glass: 200
      chemicalComposition:
        Silicon: 20
    - type: StaticPrice
      price: 40
    - type: Construction
      graph: goblin_makeshift_circuit
      node: clunkerScrapCircuit
    - type: Tag
      tags:
      - PortableGeneratorClunkerCircuitboard
      - Trash

- type: entity
  id: GoblinThrusterCircuitboard
  parent: BaseMachineCircuitboard
  name: Goblin thruster machine board
  components:
    - type: Sprite
      state: makeshift
    - type: MachineBoard
      prototype: GoblinThruster
      requirements:
        Capacitor: 1
      stackRequirements:
        Steel: 10
    - type: PhysicalComposition
      materialComposition:
        Glass: 200
      chemicalComposition:
        Silicon: 20
    - type: StaticPrice
      price: 40
    - type: Construction
      graph: goblin_makeshift_circuit
      node: goblinThrusterCircuitboard
    - type: Tag
      tags:
      - GoblinThrusterCircuitboard
      - Trash

- type: entity
  id: GoblinComputerShuttleCircuitboard
  parent: BaseComputerCircuitboard
  name: goblin-computer-shuttle-circuitboard
  description: goblin-computer-shuttle-circuitboard-desc
  components:
    - type: Sprite
      state: makeshift
    - type: ComputerBoard
      prototype: ComputerShuttleGoblin
    - type: PhysicalComposition
      materialComposition:
        Glass: 200
      chemicalComposition:
        Silicon: 20
    - type: StaticPrice
      price: 40
    - type: Construction
      graph: goblin_makeshift_circuit
      node: goblinComputerShuttleCircuitboard
    - type: Tag
      tags:
      - Trash

- type: entity
  parent: BaseItem
  name: goblin-scrap-circuitboard
  description: goblin-scrap-circuitboard-desc
  id: GoblinScrapCircuitboard
  components:
  - type: Sprite
    sprite: Objects/Materials/Scrap/generic.rsi
    layers:
    - state: glass-4
      map: [ "base" ]
  - type: Item
    size: Normal
  - type: Construction
    graph: goblin_makeshift_circuit
    node: incompleteCircuitboard
  - type: Tag
    tags:
    - Trash

#region BsTransmitter
- type: entity
  id: BsTransmitterCircuitboardT1
  parent: BaseMachineCircuitboard
  name: bluespace transmitter board T1
  description: bluespace transmitter board T1
  components:
  - type: MachineBoard
    prototype: BsTransmitterT1
    componentRequirements:
      AmeFuelContainer:
        amount: 3
        defaultPrototype: AmeJar
    stackRequirements:
      Steel: 20
      Glass: 20
      Gold: 20
      Silver: 20
      UraniumFissile: 2
      Diamond: 1
      Bluespace: 1

- type: entity
  id: BsTransmitterCircuitboardT2
  parent: BaseMachineCircuitboard
  name: bluespace transmitter board T2
  description: bluespace transmitter board T2
  components:
  - type: MachineBoard
    prototype: BsTransmitterT2
    frameSize: 2x2
    componentRequirements:
      AmeFuelContainer:
        amount: 3
        defaultPrototype: AmeJar
    stackRequirements:
      Steel: 40
      Glass: 40
      Gold: 40
      Silver: 40
      UraniumFissile: 3
      Diamond: 2
      Bluespace: 2
  - type: Tag
    tags:
    - MachineBoard2x2

- type: entity
  id: BsTransmitterCircuitboardT3
  parent: BaseMachineCircuitboard
  name: bluespace transmitter board T3
  description: bluespace transmitter board T3
  components:
  - type: MachineBoard
    prototype: BsTransmitterT3
    frameSize: 3x3
    componentRequirements:
      AmeFuelContainer:
        amount: 3
        defaultPrototype: AmeJar
    stackRequirements:
      Steel: 80
      Glass: 80
      Gold: 80
      Silver: 80
      UraniumFissile: 4
      Diamond: 3
      Bluespace: 3
  - type: Tag
    tags:
    - MachineBoard3x3

#BsReceiver Board
- type: entity
  id: BsReceiverCircuitboardT1
  parent: BaseMachineCircuitboard
  name: bluespace receiver board T1
  description: bluespace receiver board T1
  components:
  - type: MachineBoard
    prototype: BsReceiverT1
    componentRequirements:
      AmeFuelContainer:
        amount: 3
        defaultPrototype: AmeJar
    stackRequirements:
      Steel: 20
      Glass: 20
      Gold: 20
      Silver: 20
      UraniumFissile: 2
      Diamond: 1
      Bluespace: 1

- type: entity
  id: BsReceiverCircuitboardT2
  parent: BaseMachineCircuitboard
  name: bluespace receiver board T2
  description: bluespace receiver board T2
  components:
  - type: MachineBoard
    prototype: BsReceiverT2
    frameSize: 2x2
    componentRequirements:
      AmeFuelContainer:
        amount: 3
        defaultPrototype: AmeJar
    stackRequirements:
      Steel: 40
      Glass: 40
      Gold: 40
      Silver: 40
      UraniumFissile: 3
      Diamond: 2
      Bluespace: 2
  - type: Tag
    tags:
    - MachineBoard2x2

- type: entity
  id: BsReceiverCircuitboardT3
  parent: BaseMachineCircuitboard
  name: bluespace receiver board T3
  description: bluespace receiver board T3
  components:
  - type: MachineBoard
    prototype: BsReceiverT3
    frameSize: 3x3
    componentRequirements:
      AmeFuelContainer:
        amount: 3
        defaultPrototype: AmeJar
    stackRequirements:
      Steel: 80
      Glass: 80
      Gold: 80
      Silver: 80
      UraniumFissile: 4
      Diamond: 3
      Bluespace: 3
  - type: Tag
    tags:
    - MachineBoard3x3

#region Cloaking
- type: entity
  id: MachineCloakingCDMSCircuitboard
  parent: BaseMachineCircuitboard
  name: CDM-S "Stick" board
  description: CDM-S "Stick" board
  components:
  - type: Sprite
    state: security
  - type: MachineBoard
    prototype: CloakingDeviceStick
    requirements:
      Capacitor: 4
      MatterBin: 2
      Manipulator: 4
    componentRequirements:
      AmeFuelContainer:
        amount: 3
        defaultPrototype: AmeJar
    stackRequirements:
      Steel: 10
      Glass: 10
      Plasteel: 10
      Plasma: 30
      UraniumFissile: 1

- type: entity
  id: MachineCloakingChameleonCircuitboard
  parent: BaseMachineCircuitboard
  name: CDM-A "Chameleon" board
  description: CDM-A "Chameleon" board
  components:
  - type: Sprite
    state: security
  - type: MachineBoard
    prototype: CloakingDeviceChameleon
    minimumStockPartRating: 4
    requirements:
      Capacitor: 4
      MatterBin: 2
      Manipulator: 4
    componentRequirements:
      AmeFuelContainer:
        amount: 6
        defaultPrototype: AmeJar
    stackRequirements:
      Steel: 17
      Glass: 17
      Plasteel: 28
      Plasma: 42
      Gold: 7
      Silver: 7
      UraniumFissile: 2

- type: entity
  id: MachineCloakingWeepingAngelCircuitboard
  parent: BaseMachineCircuitboard
  name: ADSCDM "Weeping Angel" board
  description: ADSCDM "Weeping Angel" board
  components:
  - type: Sprite
    state: security
  - type: MachineBoard
    prototype: CloakingDeviceWeepingAngel
    frameSize: 2x2
    minimumStockPartRating: 6
    requirements:
      Capacitor: 8
      MatterBin: 4
      Manipulator: 4
    componentRequirements:
      AmeFuelContainer:
        amount: 12
        defaultPrototype: AmeJar
    stackRequirements:
      Steel: 40
      Glass: 40
      Plasteel: 66
      Plasma: 78
      Gold: 20
      Silver: 20
      UraniumFissile: 4
  - type: Tag
    tags:
    - MachineBoard2x2

#region BsBoarding
- type: entity
  parent: BaseComputerCircuitboard
  id: BoardingTeleportConsoleCircuitboard
  name: bluespace boarding console board
  description: A computer circuit board for a bluespace boarding console.
  components:
  - type: Sprite
    state: cpu_science
  - type: ComputerBoard
    prototype: ComputerBoardingTeleport
  - type: Tag
    tags:
    - DroneUsable
    - HighRiskItem

- type: entity
  parent: BaseMachineCircuitboard
  id: BoardingBluespaceScramblerMachineCircuitboard
  name: bluespace scrambler board
  description: A machine printed circuit board for a bluespace scrambler.
  components:
  - type: Sprite
    state: science
  - type: MachineBoard
    prototype: BoardingBluespaceScrambler
    requirements:
      Manipulator: 2
      Capacitor: 4
    stackRequirements:
      Steel: 5
      Glass: 5
      Plasma: 3

- type: entity
  parent: BaseMachineCircuitboard
  id: BoardingTeleportEngineMachineCircuitboard
  name: bluespace boarding engine board
  description: A machine circuit board for a bluespace boarding engine.
  components:
  - type: Sprite
    state: science
  - type: MachineBoard
    prototype: BoardingTeleportEngine
    requirements:
      Manipulator: 3
      Capacitor: 3
    stackRequirements:
      Steel: 6
      Glass: 6
      Plasma: 2

- type: entity
  parent: BaseMachineCircuitboard
  id: BoardingTeleportPlatformMachineCircuitboard
  name: bluespace boarding platform board
  description: A machine circuit board for a boarding platform.
  components:
  - type: Sprite
    state: science
  - type: MachineBoard
    prototype: BoardingTeleportPlatform
    requirements:
      Manipulator: 2
      Capacitor: 2
    stackRequirements:
      Steel: 5
      Glass: 5

- type: entity
  parent: BoardingTeleportEngineMachineCircuitboard
  id: BoardingTeleportEngineAdvancedMachineCircuitboard
  name: advanced bluespace boarding engine board
  description: A machine circuit board for an advanced bluespace boarding engine.
  components:
  - type: MachineBoard
    prototype: BoardingTeleportEngineAdvanced
    requirements:
      Manipulator: 4
      Capacitor: 4
    stackRequirements:
      Steel: 8
      Glass: 8
      Plasma: 4
      Silver: 2

- type: entity
  parent: BoardingTeleportPlatformMachineCircuitboard
  id: BoardingTeleportPlatformAdvancedMachineCircuitboard
  name: advanced bluespace boarding platform board
  description: A machine circuit board for an advanced boarding platform.
  components:
  - type: MachineBoard
    prototype: BoardingTeleportPlatformAdvanced
    requirements:
      Manipulator: 3
      Capacitor: 3
    stackRequirements:
      Steel: 7
      Glass: 7
      Silver: 2

- type: entity
  parent: BoardingTeleportEngineMachineCircuitboard
  id: BoardingTeleportEngineExperimentalMachineCircuitboard
  name: experimental bluespace boarding engine board
  description: A machine circuit board for an experimental bluespace boarding engine.
  components:
  - type: MachineBoard
    prototype: BoardingTeleportEngineExperimental
    requirements:
      Manipulator: 5
      Capacitor: 5
    stackRequirements:
      Steel: 10
      Glass: 10
      Plasma: 6
      Silver: 4

- type: entity
  parent: BoardingTeleportPlatformMachineCircuitboard
  id: BoardingTeleportPlatformExperimentalMachineCircuitboard
  name: experimental bluespace boarding platform board
  description: A machine circuit board for an experimental boarding platform.
  components:
  - type: MachineBoard
    prototype: BoardingTeleportPlatformExperimental
    requirements:
      Manipulator: 4
      Capacitor: 4
    stackRequirements:
      Steel: 9
      Glass: 9
      Plasma: 4
      Silver: 3
