using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.Radio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Forge.Radio.Ui;

[GenerateTypedNameReferences]
public sealed partial class ConfigurableEncryptionKeyMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    public event Action<string>? OnFrequencyChanged;

    private bool _updating;

    public ConfigurableEncryptionKeyMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        FrequencyLineEdit.OnTextEntered += e => OnFrequencyChanged?.Invoke(e.Text);
        FrequencyLineEdit.OnFocusExit += e => OnFrequencyChanged?.Invoke(e.Text);

        RadioFrequencyPresetUi.Populate(PopularFrequencyOptions, _prototypes);
        PopularFrequencyOptions.OnItemSelected += args =>
        {
            if (_updating)
                return;

            PopularFrequencyOptions.SelectId(args.Id);
            if (args.Id == RadioFrequencyPresetUi.CustomOptionId)
            {
                FrequencyLineEdit.GrabKeyboardFocus();
                return;
            }

            OnFrequencyChanged?.Invoke(args.Id.ToString());
        };
    }

    public void Update(ConfigurableEncryptionKeyBoundUIState state)
    {
        _updating = true;
        FrequencyLineEdit.Text = state.Frequency.ToString();
        FrequencyLineEdit.PlaceHolder = Loc.GetString("handheld-radio-custom-placeholder",
            ("min", state.MinFrequency),
            ("max", state.MaxFrequency));
        RadioFrequencyPresetUi.Select(PopularFrequencyOptions, state.Frequency);
        _updating = false;
    }
}
