#Survival boxes all replaced with mono versions with extended tanks.
- type: loadout
  id: RenegateBoxSurvivalNFOxygenExtended
  name: loadout-name-RenegateBoxSurvivalNFOxygenExtended
  hideEffects:
  - !type:GroupLoadoutEffect
    proto: OxygenBreatherNF
  storage:
    back:
    - RenegateBoxSurvivalMonoOxygenExtended

- type: loadout
  id: RenegateBoxSurvivalNFNitrogenExtended
  name: loadout-name-RenegateBoxSurvivalNFNitrogenExtended
  hideEffects:
  - !type:GroupLoadoutEffect
    proto: NitrogenBreatherNF
  storage:
    back:
    - RenegateBoxSurvivalMonoNitrogenExtended
