using System.Collections.Generic;
using System.Numerics;
using System.Text;
using Content.Client.Lobby;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.Sponsor;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._Forge.Sponsor.UI;

[GenerateTypedNameReferences]
public sealed partial class SponsorWindow : FancyWindow
{
    // Forge-Change: hardcoded "become a sponsor" link. Update this if the donation page changes.
    private const string SponsorUrl = "https://boosty.to/corvaxforge";

    [Dependency] private readonly IClientPreferencesManager _prefs = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly ISharedSponsorManager _sponsors = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;

    private readonly ColorSelectorSliders _oocColorSelector = new();
    private readonly ColorSelectorSliders _loocColorSelector = new();

    // Live color swatches shown above each selector so the player sees the actual color, not just its name.
    private readonly StyleBoxFlat _oocSwatchStyle = new() { BackgroundColor = Color.White };
    private readonly StyleBoxFlat _loocSwatchStyle = new() { BackgroundColor = Color.White };

    // Maps a GhostSkinOption item index to the chosen ghost skin entity id ("" = default observer).
    private readonly List<string> _ghostSkinIds = new();

    public SponsorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Swatch goes above the sliders; the sliders' own label keeps showing the color name.
        OocColorContainer.AddChild(MakeSwatch(_oocSwatchStyle));
        OocColorContainer.AddChild(_oocColorSelector);
        LoocColorContainer.AddChild(MakeSwatch(_loocSwatchStyle));
        LoocColorContainer.AddChild(_loocColorSelector);

        _oocColorSelector.OnColorChanged += color => _oocSwatchStyle.BackgroundColor = color.WithAlpha(1f);
        _loocColorSelector.OnColorChanged += color => _loocSwatchStyle.BackgroundColor = color.WithAlpha(1f);

        GhostSkinOption.OnItemSelected += args =>
        {
            GhostSkinOption.SelectId(args.Id);
            UpdateGhostPreview();
        };

        SaveButton.OnPressed += _ => OnSave();
        ResetButton.OnPressed += _ => OnReset();
        BecomeSponsorButton.OnPressed += _ => IoCManager.Resolve<IUriOpener>().OpenUri(SponsorUrl);

        Refresh();
    }

    private static PanelContainer MakeSwatch(StyleBoxFlat style)
    {
        return new PanelContainer
        {
            PanelOverride = style,
            MinSize = new Vector2(0, 24),
            Margin = new Thickness(0, 0, 0, 2),
        };
    }

    private SponsorLevel GetLocalLevel()
    {
        var user = _player.LocalSession?.UserId;
        if (user != null && _sponsors.TryGetSponsor(user.Value, out var level))
            return level;

        return SponsorLevel.None;
    }

    private void Refresh()
    {
        var level = GetLocalLevel();

        if (level == SponsorLevel.None)
        {
            SponsorView.Visible = false;
            NonSponsorView.Visible = true;
            BuildNonSponsorView();
        }
        else
        {
            NonSponsorView.Visible = false;
            SponsorView.Visible = true;
            BuildSponsorView(level);
        }
    }

    private void BuildSponsorView(SponsorLevel level)
    {
        SponsorData.SponsorNames.TryGetValue(level, out var levelName);
        SponsorStatusLabel.Text = Loc.GetString("sponsor-window-status",
            ("level", levelName ?? level.ToString()));

        // Ghost skins available to this level (plus a "default observer" entry).
        GhostSkinOption.Clear();
        _ghostSkinIds.Clear();

        GhostSkinOption.AddItem(Loc.GetString("sponsor-window-ghost-skin-default"), 0);
        _ghostSkinIds.Add(string.Empty);

        var current = _prefs.Preferences?.SponsorGhostSkin ?? string.Empty;
        var selectedIndex = 0;

        foreach (var (entityId, _) in SponsorData.GetAvailableGhostSkins(level))
        {
            var id = _ghostSkinIds.Count;
            var name = _proto.TryIndex<EntityPrototype>(entityId, out var proto) ? proto.Name : entityId;
            GhostSkinOption.AddItem(name, id);
            _ghostSkinIds.Add(entityId);

            if (entityId == current)
                selectedIndex = id;
        }

        GhostSkinOption.SelectId(selectedIndex);
        UpdateGhostPreview();

        // Colors. Transparent in prefs means "unset" -> fall back to the level color (or white).
        SponsorData.SponsorColor.TryGetValue(level, out var levelColorHex);
        var fallback = levelColorHex != null ? Color.FromHex(levelColorHex, Color.White) : Color.White;

        var ooc = _prefs.Preferences?.SponsorOOCColor ?? Color.Transparent;
        var looc = _prefs.Preferences?.SponsorLOOCColor ?? Color.Transparent;

        // Assigning .Color does not raise OnColorChanged, so sync the swatches manually here.
        _oocColorSelector.Color = ooc == Color.Transparent ? fallback : ooc.WithAlpha(1f);
        _loocColorSelector.Color = looc == Color.Transparent ? fallback : looc.WithAlpha(1f);
        _oocSwatchStyle.BackgroundColor = _oocColorSelector.Color.WithAlpha(1f);
        _loocSwatchStyle.BackgroundColor = _loocColorSelector.Color.WithAlpha(1f);
    }

    private void UpdateGhostPreview()
    {
        var index = GhostSkinOption.SelectedId;
        var skinId = index >= 0 && index < _ghostSkinIds.Count ? _ghostSkinIds[index] : string.Empty;

        // Default observer preview when no skin is selected.
        var protoId = string.IsNullOrEmpty(skinId) ? "MobObserver" : skinId;
        GhostPreview.SetPrototype(_proto.HasIndex<EntityPrototype>(protoId) ? protoId : null);
    }

    private void OnSave()
    {
        var index = GhostSkinOption.SelectedId;
        var skinId = index >= 0 && index < _ghostSkinIds.Count ? _ghostSkinIds[index] : string.Empty;

        // Force opaque so the server doesn't read the color as "unset" (transparent).
        var ooc = _oocColorSelector.Color.WithAlpha(1f);
        var looc = _loocColorSelector.Color.WithAlpha(1f);

        _prefs.UpdateSponsorPreferences(ooc, looc, skinId);
    }

    private void OnReset()
    {
        // Transparent colors + empty skin revert to the level defaults on the server.
        _prefs.UpdateSponsorPreferences(Color.Transparent, Color.Transparent, string.Empty);
        Refresh();
    }

    private void BuildNonSponsorView()
    {
        PitchLabel.SetMarkup(Loc.GetString("sponsor-window-pitch"));

        LevelCardsContainer.RemoveAllChildren();

        foreach (SponsorLevel level in Enum.GetValues(typeof(SponsorLevel)))
        {
            if (level == SponsorLevel.None)
                continue;

            SponsorData.SponsorNames.TryGetValue(level, out var name);
            SponsorData.SponsorColor.TryGetValue(level, out var colorHex);
            var ghostSkins = SponsorData.SponsorGhost.TryGetValue(level, out var ids) ? ids : new List<string>();
            var hasGhostSkin = ghostSkins.Count > 0;

            var card = new PanelContainer { StyleClasses = { "AngleRect" }, HorizontalExpand = true };

            // Text on the left, ghost-skin preview (if this level unlocks one) on the right.
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(8, 6, 8, 6),
                HorizontalExpand = true,
            };

            var box = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            };

            var title = new RichTextLabel();
            title.SetMarkup($"[bold][color={colorHex ?? "#ffffff"}]{name ?? level.ToString()}[/color][/bold]");
            box.AddChild(title);

            var perks = new StringBuilder();
            perks.AppendLine(Loc.GetString("sponsor-window-perk-ooc"));
            perks.AppendLine(Loc.GetString("sponsor-window-perk-looc"));
            if (hasGhostSkin)
                perks.AppendLine(Loc.GetString("sponsor-window-perk-ghost-skin"));

            var perksLabel = new RichTextLabel();
            perksLabel.SetMarkup(perks.ToString().TrimEnd());
            box.AddChild(perksLabel);

            row.AddChild(box);

            // Show a preview for every ghost skin this level unlocks.
            foreach (var skin in ghostSkins)
            {
                if (!_proto.HasIndex<EntityPrototype>(skin))
                    continue;

                var preview = new EntityPrototypeView
                {
                    Scale = new Vector2(2, 2),
                    MinSize = new Vector2(64, 64),
                    Margin = new Thickness(4, 0, 0, 0),
                    VerticalAlignment = VAlignment.Center,
                    HorizontalAlignment = HAlignment.Right,
                };
                preview.SetPrototype(skin);
                row.AddChild(preview);
            }

            card.AddChild(row);
            LevelCardsContainer.AddChild(card);
        }
    }
}
