- type: job
  id: Arbiter
  name: forge-job-name-arbiter
  description: forge-job-desc-arbiter
  playTimeTracker: JobArbiter
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 64800 # 18 hours
    - !type:DepartmentTimeRequirement
      department: Empire
      time: 43200 # 12 hours
    - !type:RoleTimeRequirement
      role: JobPraetorian
      time: 21600 # 6 hours
    - !type:SpeciesRequirement
      species:
      - Human
    - !type:SexRequirement
      sex:
      - Male
    - !type:AgeRequirement
      requiredAge: 35
  setPreference: true
  startingGear: ArbiterGear
  alwaysUseSpawner: true
  icon: JobIconEmpireArbiter
  assignedCompany: Imperial
  assignedNationality: Imperial
  supervisors: job-supervisors-praefect
  weight: 40
  displayWeight: 40
  canBeAntag: false
  access:
  - EmpireSecApartment
  accessGroups:
  - CommandEmpireAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - Empire
  - !type:AddImplantSpecial
    implants: [ ImplantGuard, EmpireTrackingImplant ]

- type: startingGear
  id: ArbiterGear
  storage:
    back:
    - EmpireSecApartmentTablet
