- type: job
  id: Auxilia # Soldier
  name: forge-job-name-auxilia
  description: forge-job-desc-auxilia
  supervisors: job-supervisors-praetorian
  playTimeTracker: JobAuxilia
  icon: JobIconEmpireAuxilia
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 43200 # 12 hours
    - !type:DepartmentTimeRequirement
      department: Empire
      time: 21600 # 6 hours
    - !type:SpeciesRequirement
      species:
        - Human
        - Dwarf
  # alternateRequirementSets:
  #   longerPlaytimeLessSec:
  #   - !type:RoleTimeRequirement
  #     role: # Позже добавить альтернативные тебования времени за аналогичную роль у ТСФ
  #     time: 43200 # 12 hours
  startingGear: AuxiliaGear
  weight: 15
  displayWeight: 15
  canBeAntag: false
  setPreference: true
  assignedCompany: Imperial
  assignedNationality: Imperial
  accessGroups:
  - GeneralEmpireAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - Empire
  - !type:AddImplantSpecial
    implants: [ ImplantGuard , EmpireTrackingImplant]

- type: startingGear
  id: AuxiliaGear
  # equipment:
  #   ears:
  #   belt:
  #   pocket1:
  #   pocket2:
  # storage:
  #   back:
  #   - RadioHandheldNF