- type: job
  id: Inquisitor
  name: forge-job-name-inquisitor
  description: forge-job-desc-inquisitor
  playTimeTracker: JobInquisitor
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 43200 # 12 hours
    - !type:DepartmentTimeRequirement
      department: Empire
      time: 21600 # 6 hours
    - !type:SpeciesRequirement
      species:
        - Human
    - !type:AgeRequirement
      requiredAge: 40
    - !type:SexRequirement
      sex:
      - Male
  # alternateRequirementSets:
  #   longerPlaytimeLessSec:
  #   - !type:RoleTimeRequirement
  #     role: # Требования попросили оставить низкими для людей с whitelist
  #     time: 43200 # 12 hours
  whitelisted: true
  startingGear: InquisitorGear
  alwaysUseSpawner: true
  icon: JobIconEmpireInquisitor
  assignedCompany: Imperial
  assignedNationality: Imperial
  supervisors: job-supervisors-inquisitor-grand
  weight: 30
  displayWeight: 30
  canBeAntag: false
  setPreference: true
  access:
  - EmpireInqusitor
  - EmpireSmallInq
  - EmpireSecApartment
  accessGroups:
  - CommandEmpireAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - Empire
  - !type:AddImplantSpecial
    implants: [ ImplantGuard , EmpireTrackingImplant]

- type: startingGear
  id: InquisitorGear
  storage:
    back:
    - EmpireSecApartmentTablet
