- type: loadout
  id: EmpireBoxSurvivalMonoOxygenExtended
  name: loadout-name-EmpireBoxSurvivalMonoOxygenExtended
  hideEffects:
  - !type:GroupLoadoutEffect
    proto: OxygenBreatherNF
  storage:
    back:
    - EmpireBoxSurvivalMonoOxygenExtended

- type: loadout
  id: EmpireBoxSurvivalMonoNitrogenExtended
  name: loadout-name-EmpireBoxSurvivalMonoNitrogenExtended
  hideEffects:
  - !type:GroupLoadoutEffect
    proto: NitrogenBreatherNF
  storage:
    back:
    - EmpireBoxSurvivalMonoNitrogenExtended
