using System;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.Access.UI;

[GenerateTypedNameReferences]
public sealed partial class JobPresetListItem : BoxContainer
{
    public sealed class ViewState(string title, string subtitle, Texture? iconTexture)
    {
        public string Title { get; } = title;
        public string Subtitle { get; } = subtitle;
        public Texture? IconTexture { get; } = iconTexture;
    }

    public event Action? ApplyPressed;
    public event Action? CreateInjectorPressed;

    public JobPresetListItem(ViewState state)
    {
        RobustXamlLoader.Load(this);

        JobTitle.Text = state.Title;
        JobSubtitle.SetMessage(state.Subtitle);
        JobIcon.Texture = state.IconTexture;

        ApplyButton.OnPressed += _ => ApplyPressed?.Invoke();
        CreateInjectorButton.OnPressed += _ => CreateInjectorPressed?.Invoke();
    }

    public void SetSubtitle(string text, Color color)
    {
        JobSubtitle.SetMessage(text);
        JobSubtitle.Modulate = color;
    }

    public ButtonGroup? Group
    {
        get => ApplyButton.Group;
        set => ApplyButton.Group = value;
    }

    public bool Pressed
    {
        get => ApplyButton.Pressed;
        set => ApplyButton.Pressed = value;
    }

    public bool ApplyDisabled
    {
        get => ApplyButton.Disabled;
        set => ApplyButton.Disabled = value;
    }

    public bool InjectorDisabled
    {
        get => CreateInjectorButton.Disabled;
        set => CreateInjectorButton.Disabled = value;
    }

    public void SetTooltips(string? text)
    {
        ApplyButton.ToolTip = text;
        CreateInjectorButton.ToolTip = text;
    }
}
