using System.IO;
using System.Numerics;
using Content.Client._Forge.Paper;
using Content.Shared._Forge.Paper;
using Content.Shared.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Client.UserInterface.RichText;
using Content.Client.UserInterface.RichText;
using Robust.Shared.Input;

namespace Content.Client.Paper.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class PaperWindow : BaseWindow
    {
        [Dependency] private IInputManager _inputManager = default!;
        [Dependency] private IResourceCache _resCache = default!;
        [Dependency] private IFileDialogManager _fileDialogs = default!;

        [ViewVariables]
        private static Color DefaultTextColor = new(25, 25, 25);

        // <summary>
        // Size of resize handles around the paper
        private const int DRAG_MARGIN_SIZE = 16;

        // We keep a reference to the paper content texture that we create
        // so that we can modify it later.
        private StyleBoxTexture _paperContentTex = new();

        // The number of lines that the content image represents.
        // See PaperVisualsComponent.ContentImageNumLines.
        private float _paperContentLineScale = 1.0f;

        // If paper limits the size in one or both axes, it'll affect whether
        // we're able to resize this UI or not. Default to everything enabled:
        private DragMode _allowedResizeModes = ~DragMode.None;

        private readonly Type[] _allowedTags = new Type[] {
            typeof(BoldItalicTag),
            typeof(BoldTag),
            typeof(BulletTag),
            typeof(ColorTag),
            typeof(HeadingTag),
            typeof(ItalicTag),
            typeof(MonoTag)
        };

        public event Action<string>? OnSaved;

        // Forge-Change: language dropdown while writing
        private readonly List<string> _languageIds = new();
        private string? _pickedLanguage;

        private int _MaxInputLength = -1;
        private bool _imageDialogOpen;
        public int MaxInputLength
        {
            get
            {
                return _MaxInputLength;
            }
            set
            {
                _MaxInputLength = value;
                UpdateFillState();
            }
        }

        public PaperWindow()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            // We can't configure the RichTextLabel contents from xaml, so do it here:
            BlankPaperIndicator.SetMessage(Loc.GetString("paper-ui-blank-page-message"), null, DefaultTextColor);

            // Hook up the close button:
            CloseButton.OnPressed += _ => Close();

            Input.OnKeyBindDown += args => // Solution while TextEdit don't have events
            {
                if (args.Function == EngineKeyFunctions.MultilineTextSubmit)
                {
                    // SaveButton is disabled when we hit the max input limit. Just check
                    // that flag instead of trying to calculate the input length again
                    if (!SaveButton.Disabled)
                    {
                        RunOnSaved();
                        args.Handle();
                    }
                }
            };

            Input.OnTextChanged += args =>
            {
                UpdateFillState();
            };

            SaveButton.OnPressed += _ =>
            {
                RunOnSaved();
            };

            SaveButton.Text = Loc.GetString("paper-ui-save-button",
                ("keybind", _inputManager.GetKeyFunctionButtonString(EngineKeyFunctions.MultilineTextSubmit)));
            InsertImageButton.Text = Loc.GetString("paper-ui-insert-image-button");
            InsertImageButton.ToolTip = Loc.GetString("paper-ui-insert-image-tooltip");
            InsertImageButton.OnPressed += _ =>
            {
                OnInsertImagePressed();
            };
            // Forge-Change: high-contrast language label + actually apply OptionButton selection
            LanguageLabel.Text = Loc.GetString("paper-language-ui-language");
            LanguageLabel.FontColorOverride = Color.FromHex("#F2F2F2");
            LanguageSelector.Filterable = true;
            LanguageSelector.OnItemSelected += args =>
            {
                LanguageSelector.SelectId(args.Id);
                if (args.Id >= 0 && args.Id < _languageIds.Count)
                    _pickedLanguage = _languageIds[args.Id];
            };
        }

        /// <summary>
        ///     Initialize this UI according to <code>visuals</code> Initializes
        ///     textures, recalculates sizes, and applies some layout rules.
        /// </summary>
        public void InitVisuals(EntityUid entity, PaperVisualsComponent visuals)
        {
            // Randomize the placement of any stamps based on the entity UID
            // so that there's some variety in different papers.
            StampDisplay.PlacementSeed = (int)entity;

            // Initialize the background:
            PaperBackground.ModulateSelfOverride = visuals.BackgroundModulate;
            var backgroundImage = visuals.BackgroundImagePath != null? _resCache.GetResource<TextureResource>(visuals.BackgroundImagePath) : null;
            if (backgroundImage != null)
            {
                var backgroundImageMode = visuals.BackgroundImageTile ? StyleBoxTexture.StretchMode.Tile : StyleBoxTexture.StretchMode.Stretch;
                var backgroundPatchMargin = visuals.BackgroundPatchMargin;
                PaperBackground.PanelOverride = new StyleBoxTexture
                {
                    Texture = backgroundImage,
                    TextureScale = visuals.BackgroundScale,
                    Mode = backgroundImageMode,
                    PatchMarginLeft = backgroundPatchMargin.Left,
                    PatchMarginTop = backgroundPatchMargin.Top,
                    PatchMarginRight = backgroundPatchMargin.Right,
                    PatchMarginBottom = backgroundPatchMargin.Bottom
                };

            }
            else
            {
                PaperBackground.PanelOverride = null;
            }


            // Then the header:
            if (visuals.HeaderImagePath != null)
            {
                HeaderImage.TexturePath = visuals.HeaderImagePath;
                HeaderImage.MinSize = HeaderImage.TextureNormal?.Size ?? Vector2.Zero;
            }

            HeaderImage.ModulateSelfOverride = visuals.HeaderImageModulate;
            HeaderImage.Margin = visuals.HeaderMargin;


            PaperContent.ModulateSelfOverride = visuals.ContentImageModulate;
            WrittenTextLabel.ModulateSelfOverride = visuals.FontAccentColor;
            FillStatus.ModulateSelfOverride = visuals.FontAccentColor;

            var contentImage = visuals.ContentImagePath != null ? _resCache.GetResource<TextureResource>(visuals.ContentImagePath) : null;
            if (contentImage != null)
            {
                // Setup the paper content texture, but keep a reference to it, as we can't set
                // some font-related properties here. We'll fix those up later, in Draw()
                _paperContentTex = new StyleBoxTexture
                {
                    Texture = contentImage,
                    Mode = StyleBoxTexture.StretchMode.Tile,
                };
                PaperContent.PanelOverride = _paperContentTex;
                _paperContentLineScale = visuals.ContentImageNumLines;
            }

            PaperContent.Margin = visuals.ContentMargin;

            if (visuals.MaxWritableArea != null)
            {
                var a = (Vector2)visuals.MaxWritableArea;
                // Paper has requested that this has a maximum area that you can write on.
                // So, we'll make the window non-resizable and fix the size of the content.
                // Ideally, would like to be able to allow resizing only one direction.
                ScrollingContents.MinSize = Vector2.Zero;
                ScrollingContents.MinSize = a;

                if (a.X > 0.0f)
                {
                    ScrollingContents.MaxWidth = a.X;
                    _allowedResizeModes &= ~(DragMode.Left | DragMode.Right);

                    // Since this dimension has been specified by the user, we
                    // need to undo the SetSize which was configured in the xaml.
                    // Controls use NaNs to indicate unset for this value.
                    // This is leaky - there should be a method for this
                    SetWidth = float.NaN;
                }

                if (a.Y > 0.0f)
                {
                    ScrollingContents.MaxHeight = a.Y;
                    _allowedResizeModes &= ~(DragMode.Top | DragMode.Bottom);
                    SetHeight = float.NaN;
                }
            }
        }

        /// <summary>
        ///     Control interface. We'll mostly rely on the children to do the drawing
        ///     but in order to get lines on paper to match up with the rich text labels,
        ///     we need to do a small calculation to sync them up.
        /// </summary>
        protected override void Draw(DrawingHandleScreen handle)
        {
            // Now do the deferred setup of the written area. At the point
            // that InitVisuals runs, the label hasn't had it's style initialized
            // so we need to get some info out now:
            if (WrittenTextLabel.TryGetStyleProperty<Font>("font", out var font))
            {
                float fontLineHeight = font.GetLineHeight(1.0f);
                // This positions the texture so the font baseline is on the bottom:
                _paperContentTex.ExpandMarginTop = font.GetDescent(UIScale);
                // And this scales the texture so that it's a single text line:
                var scaleY = (_paperContentLineScale * fontLineHeight) / _paperContentTex.Texture?.Height ?? fontLineHeight;
                _paperContentTex.TextureScale = new Vector2(1, scaleY);

                // Now, we might need to add some padding to the text to ensure
                // that, even if a header is specified, the text will line up with
                // where the content image expects the font to be rendered (i.e.,
                // adjusting the height of the header image shouldn't cause the
                // text to be offset from a line)
                {
                    var headerHeight = HeaderImage.Size.Y + HeaderImage.Margin.Top + HeaderImage.Margin.Bottom;
                    var headerInLines = headerHeight / (fontLineHeight * _paperContentLineScale);
                    var paddingRequiredInLines = (float)Math.Ceiling(headerInLines) - headerInLines;
                    var verticalMargin = fontLineHeight * paddingRequiredInLines * _paperContentLineScale;
                    TextAlignmentPadding.Margin = new Thickness(0.0f, verticalMargin, 0.0f, 0.0f);
                }
            }

            base.Draw(handle);
        }

        /// <summary>
        ///     Initialize the paper contents, i.e. the text typed by the
        ///     user and any stamps that have peen put on the page.
        /// </summary>
        /// <param name="obscureWhileEditing">
        /// When true, Mode is Write but the local player cannot read the page —
        /// show the same garbled text as reading and do not put it in the editor.
        /// </param>
        public void Populate(PaperComponent.PaperBoundUserInterfaceState state, bool obscureWhileEditing = false)
        {
            bool isEditing = state.Mode == PaperComponent.PaperAction.Write && !obscureWhileEditing;
            bool wasEditing = InputContainer.Visible;
            InputContainer.Visible = isEditing;
            EditButtons.Visible = isEditing;

            var msg = new FormattedMessage();
            msg.AddMarkupPermissive(state.Text);

            // Frontier: signatures shouldn't walk off the page
            if (state.StampedBy.Count > 0)
            {
                for (int i = 0; i < 6; i++)
                    msg.AddMarkupPermissive("\r\n");
            }
            // End Frontier

            // Keep a hidden label for font metrics in Draw(). Drawings are
            // sibling TextureRects so RobustToolbox rich-text is untouched.
            WrittenTextLabel.SetMessage(msg, _allowedTags, DefaultTextColor);
            RebuildWrittenContent(state.Text, state.StampedBy.Count > 0);

            if (isEditing)
            {
                WrittenContent.Visible = false;
                BlankPaperIndicator.Visible = false;
                if (!wasEditing)
                {
                    Input.TextRope = Rope.Leaf.Empty;
                    Input.CursorPosition = new TextEdit.CursorPos();
                    Input.InsertAtCursor(state.Text);
                }
            }
            else
            {
                WrittenContent.Visible = state.Text.Length > 0;
                BlankPaperIndicator.Visible = state.Text.Length == 0;
            }

            StampDisplay.RemoveAllChildren();
            StampDisplay.RemoveStamps();
            foreach(var stamper in state.StampedBy)
            {
                StampDisplay.AddStamp(new StampWidget { StampInfo = stamper });
            }
        }

        private void RebuildWrittenContent(string text, bool stampPadding)
        {
            WrittenContent.RemoveAllChildren();

            var maxWidth = PaperContent.MaxWidth > 0 ? PaperContent.MaxWidth : 600f;
            foreach (var part in PaperPixelArtCodec.SplitDocument(text))
            {
                if (part.Art is { } art)
                {
                    WrittenContent.AddChild(PaperPixelArtView.Create(art, maxWidth));
                    continue;
                }

                if (string.IsNullOrEmpty(part.Text))
                    continue;

                WrittenContent.AddChild(CreatePaperLabel(part.Text));
            }

            if (stampPadding)
                WrittenContent.AddChild(CreatePaperLabel("\r\n\r\n\r\n\r\n\r\n\r\n"));
        }

        private RichTextLabel CreatePaperLabel(string markup)
        {
            var label = new RichTextLabel
            {
                StyleClasses = { "PaperWrittenText" },
                VerticalAlignment = Control.VAlignment.Top,
                ModulateSelfOverride = WrittenTextLabel.ModulateSelfOverride
            };
            var msg = new FormattedMessage();
            msg.AddMarkupPermissive(markup);
            label.SetMessage(msg, _allowedTags, DefaultTextColor);
            return label;
        }

        /// <summary>
        ///     BaseWindow interface. Allow users to drag UI around by grabbing
        ///     anywhere on the page (like FancyWindow) but try to calculate
        ///     reasonable dragging bounds because this UI can have round corners,
        ///     and it can be hard to judge where to click to resize.
        /// </summary>
        protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        {
            var mode = DragMode.None;

            // Be quite generous with resize margins:
            if (relativeMousePos.Y < DRAG_MARGIN_SIZE)
            {
                mode |= DragMode.Top;
            }
            else if (relativeMousePos.Y > Size.Y - DRAG_MARGIN_SIZE)
            {
                mode |= DragMode.Bottom;
            }

            if (relativeMousePos.X < DRAG_MARGIN_SIZE)
            {
                mode |= DragMode.Left;
            }
            else if (relativeMousePos.X > Size.X - DRAG_MARGIN_SIZE)
            {
                mode |= DragMode.Right;
            }

            if((mode & _allowedResizeModes) == DragMode.None)
            {
                return DragMode.Move;
            }
            return mode & _allowedResizeModes;
        }

        // Forge-Change: languages the local player can write this page in
        public void SetLanguageOptions(IReadOnlyList<(string Id, string Name)> languages, string? selectedId)
        {
            var visible = languages.Count > 0;
            LanguageSelector.Visible = visible;
            LanguageLabel.Visible = visible;
            if (!visible)
            {
                _languageIds.Clear();
                _pickedLanguage = null;
                LanguageSelector.Clear();
                return;
            }

            var sameList = _languageIds.Count == languages.Count;
            if (sameList)
            {
                for (var i = 0; i < languages.Count; i++)
                {
                    if (_languageIds[i] != languages[i].Id)
                    {
                        sameList = false;
                        break;
                    }
                }
            }

            if (!sameList)
            {
                LanguageSelector.Clear();
                _languageIds.Clear();
                for (var i = 0; i < languages.Count; i++)
                {
                    LanguageSelector.AddItem(languages[i].Name, i);
                    _languageIds.Add(languages[i].Id);
                }
            }

            var toSelect = _pickedLanguage != null && _languageIds.Contains(_pickedLanguage)
                ? _pickedLanguage
                : selectedId;

            var selected = 0;
            for (var i = 0; i < _languageIds.Count; i++)
            {
                if (_languageIds[i] == toSelect)
                {
                    selected = i;
                    break;
                }
            }

            _pickedLanguage = _languageIds[selected];
            if (LanguageSelector.SelectedId != selected)
                LanguageSelector.SelectId(selected);
        }

        public string? GetSelectedLanguage()
        {
            if (!LanguageSelector.Visible)
                return null;

            var id = LanguageSelector.SelectedId;
            if (id < 0 || id >= _languageIds.Count)
                return null;

            return _languageIds[id];
        }

        private async void OnInsertImagePressed()
        {
            if (_imageDialogOpen || InsertImageButton.Disabled)
                return;

            _imageDialogOpen = true;
            InsertImageButton.Disabled = true;

            var filters = new FileDialogFilters(
                new FileDialogFilters.Group("png", "webp", "jpg", "jpeg", "gif", "bmp"),
                new FileDialogFilters.Group("png"),
                new FileDialogFilters.Group("webp"),
                new FileDialogFilters.Group("jpg", "jpeg"));
            await using var file = await _fileDialogs.OpenFile(filters, FileAccess.Read);

            _imageDialogOpen = false;

            if (Disposed)
                return;

            if (file == null)
            {
                UpdateFillState();
                return;
            }

            var maxChars = GetRemainingInputChars();
            if (!PaperPixelArtImporter.TryImport(file, maxChars, out var markup, out var error))
            {
                FillStatus.Text = Loc.GetString(error switch
                {
                    PaperPixelArtImportError.FileTooLarge => "paper-ui-insert-image-too-large",
                    PaperPixelArtImportError.NoSpace => "paper-ui-insert-image-no-space",
                    _ => "paper-ui-insert-image-failed"
                });
                UpdateFillState(keepStatusMessage: true);
                return;
            }

            InsertDrawingMarkup(markup);
            UpdateFillState();
        }

        private void InsertDrawingMarkup(string markup)
        {
            var text = Rope.Collapse(Input.TextRope);
            var cursor = Math.Clamp(Input.CursorPosition.Index, 0, text.Length);
            var prefix = cursor > 0 && text[cursor - 1] != '\n' ? "\n" : string.Empty;
            Input.InsertAtCursor(prefix + markup + "\n");
        }

        private int GetRemainingInputChars()
        {
            var used = PaperPixelArtCodec.Compress(Rope.Collapse(Input.TextRope)).Length;
            if (MaxInputLength < 0)
                return PaperPixelArtCodec.MaxPixels * 6;

            // Leave a little room for the wrapping newlines around the tag.
            return Math.Max(0, MaxInputLength - used - 2);
        }

        private void RunOnSaved()
        {
            // Prevent further saving while text processing still in
            SaveButton.Disabled = true;
            // Forge-Change: store compact pixel-art instead of one [color] tag per pixel
            OnSaved?.Invoke(PaperPixelArtCodec.Compress(Rope.Collapse(Input.TextRope)));
        }

        private void UpdateFillState(bool keepStatusMessage = false)
        {
            if (MaxInputLength != -1)
            {
                // Forge-Change: count the compressed length so pasted drawings can be saved
                var inputLength = PaperPixelArtCodec.Compress(Rope.Collapse(Input.TextRope)).Length;
                if (!keepStatusMessage)
                {
                    FillStatus.Text = Loc.GetString("paper-ui-fill-level",
                        ("currentLength", inputLength),
                        ("maxLength", MaxInputLength));
                }

                SaveButton.Disabled = inputLength > MaxInputLength;
                InsertImageButton.Disabled = _imageDialogOpen || GetRemainingInputChars() < 32;
            }
            else
            {
                if (!keepStatusMessage)
                    FillStatus.Text = "";
                SaveButton.Disabled = false;
                InsertImageButton.Disabled = _imageDialogOpen;
            }
        }
    }
}
