using System.Linq;// Forge-Change
using System.Numerics;
using System.Text;
using Content.Client._Forge.Botany.UI;
using Content.Shared._Forge.Botany;// Forge-Change
using Content.Shared._NF.PlantAnalyzer;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes; // Forge-Change

namespace Content.Client._NF.PlantAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class PlantAnalyzerWindow : BaseWindow
{
    [Dependency] private readonly IResourceCache _resCache = default!;
    [Dependency] private readonly IPrototypeManager _prototypes = default!; // Forge-Change

    private readonly BotanyUiStyles _styles;
    private readonly BotanyChipButton _printLabel;
    private PlantAnalyzerScannedSeedPlantInformation? _scan;
    private AnalyzerSection _section = AnalyzerSection.Overview;

    private enum AnalyzerSection
    {
        Overview,
        Tray,
        Genetics,
        Tolerances,
        Mutations
    }

    public event Action? OnPrintLabel;

    public PlantAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _styles = new BotanyUiStyles(_resCache);

        TitleLabel.Text = Loc.GetString("plant-analyzer-interface-title");
        DetailHeader.Text = Loc.GetString("plant-analyzer-detail-header");
        ListHeader.Text = Loc.GetString("plant-analyzer-list-header");
        OsLabel.Text = Loc.GetString("plant-analyzer-os");
        PlantNameLabel.Text = Loc.GetString("plant-analyzer-window-no-seed-information-text");
        StatusLabel.Text = string.Empty;

        CloseButton.OnPressed += _ => Close();
        _printLabel = _styles.Action(Loc.GetString("plant-analyzer-print-label"));
        _printLabel.Margin = new Thickness(0, 0, 0, 0);
        _printLabel.OnPressed += _ => OnPrintLabel?.Invoke();
        _printLabel.Disabled = true;
        PrintLabelHost.AddChild(_printLabel);
        ApplyChrome();
        RebuildSectionList();
        ShowNoData();
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos) => DragMode.Move;

    public void Populate(PlantAnalyzerScannedSeedPlantInformation msg)
    {
        if (string.IsNullOrEmpty(msg.SeedName) && !msg.IsTray)
        {
            _scan = null;
            PlantNameLabel.Text = Loc.GetString("plant-analyzer-window-no-seed-information-text");
            StatusLabel.Text = string.Empty;
            _printLabel.Disabled = true;
            RebuildSectionList();
            ShowNoData();
            return;
        }

        _scan = msg;
        _printLabel.Disabled = msg.IsTray || msg.TargetEntity == null;
        var seedName = Loc.GetString(string.IsNullOrEmpty(msg.SeedName) ? "plant-analyzer-unknown-plant" : msg.SeedName);
        PlantNameLabel.Text = msg.IsTray
            ? Loc.GetString("plant-analyzer-window-label-name-scanned-plant", ("seedName", seedName))
            : Loc.GetString("plant-analyzer-window-label-name-scanned-seed", ("seedName", seedName));

        if (msg.IsTray)
        {
            var status = msg.Dead
                ? Loc.GetString("plant-analyzer-tray-dead")
                : msg.HarvestReady
                    ? Loc.GetString("plant-analyzer-tray-harvest")
                    : Loc.GetString("plant-analyzer-tray-growing");
            StatusLabel.Text = status;
            StatusLabel.FontColorOverride = msg.Dead
                ? BotanyUiTheme.Danger
                : msg.HarvestReady
                    ? BotanyUiTheme.Harvest
                    : BotanyUiTheme.Ok;
        }
        else
        {
            StatusLabel.Text = Loc.GetString("plant-analyzer-window-tab-basics");
            StatusLabel.FontColorOverride = BotanyUiTheme.Text;
        }

        if (_section == AnalyzerSection.Tray && !msg.IsTray)
            _section = AnalyzerSection.Overview;

        RebuildSectionList();
        ShowSection();
    }

    private void RebuildSectionList()
    {
        ListContainer.DisposeAllChildren();

        AddSectionButton(AnalyzerSection.Overview, Loc.GetString("plant-analyzer-section-overview"), Loc.GetString("plant-analyzer-section-overview-sub"));
        if (_scan?.IsTray == true)
            AddSectionButton(AnalyzerSection.Tray, Loc.GetString("plant-analyzer-section-tray"), Loc.GetString("plant-analyzer-section-tray-sub"));
        AddSectionButton(AnalyzerSection.Genetics, Loc.GetString("plant-analyzer-section-genetics"), Loc.GetString("plant-analyzer-section-genetics-sub"));
        AddSectionButton(AnalyzerSection.Tolerances, Loc.GetString("plant-analyzer-section-tolerances"), Loc.GetString("plant-analyzer-section-tolerances-sub"));
        AddSectionButton(AnalyzerSection.Mutations, Loc.GetString("plant-analyzer-section-mutations"), Loc.GetString("plant-analyzer-section-mutations-sub"));
    }

    private void AddSectionButton(AnalyzerSection section, string title, string subtitle)
    {
        var button = new BotanyListButton(_styles) { Key = section };
        button.SetContent(title, subtitle);
        button.ApplySelected(_section == section);
        button.OnPressed += _ =>
        {
            _section = section;
            RebuildSectionList();
            ShowSection();
        };
        ListContainer.AddChild(button);
    }

    private void ShowSection()
    {
        DetailContainer.DisposeAllChildren();

        if (_scan == null)
        {
            ShowNoData();
            return;
        }

        switch (_section)
        {
            case AnalyzerSection.Overview:
                ShowOverview(_scan);
                break;
            case AnalyzerSection.Tray:
                ShowTray(_scan);
                break;
            case AnalyzerSection.Genetics:
                ShowGenetics(_scan);
                break;
            case AnalyzerSection.Tolerances:
                ShowTolerances(_scan);
                break;
            case AnalyzerSection.Mutations:
                ShowMutations(_scan);
                break;
        }
    }

    private void ShowOverview(PlantAnalyzerScannedSeedPlantInformation msg)
    {
        DetailHeader.Text = Loc.GetString("plant-analyzer-section-overview");
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-yield"), $"{msg.SeedYield:D0}"));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-potency"), $"{msg.SeedPotency:F0}%"));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-harvest"), Loc.GetString($"plant-analyzer-harvest-{msg.HarvestType}")));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-endurance"), $"{msg.Endurance:F0}"));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-lifespan"), $"{msg.Lifespan:F1}"));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-maturation"), $"{msg.Maturation:F1}"));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-production"), $"{msg.Production:F1}"));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-stages"), $"{msg.GrowthStages:D0}"));
    }

    private void ShowTray(PlantAnalyzerScannedSeedPlantInformation msg)
    {
        DetailHeader.Text = Loc.GetString("plant-analyzer-section-tray");
        if (!msg.IsTray)
        {
            DetailContainer.AddChild(_styles.Sub(Loc.GetString("plant-analyzer-section-tray-seed-only")));
            return;
        }

        var status = msg.Dead
            ? Loc.GetString("plant-analyzer-tray-dead")
            : msg.HarvestReady
                ? Loc.GetString("plant-analyzer-tray-harvest")
                : Loc.GetString("plant-analyzer-tray-growing");
        var statusColor = msg.Dead ? BotanyUiTheme.Danger : msg.HarvestReady ? BotanyUiTheme.Harvest : BotanyUiTheme.Ok;

        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-status"), status, statusColor));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-health"), $"{msg.TrayHealth:0} / {msg.TrayEndurance:0}", HealthColor(msg.TrayHealth, msg.TrayEndurance)));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-age"), msg.Age.ToString()));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-water"), $"{msg.WaterLevel:0}", msg.WaterLevel <= 15 ? BotanyUiTheme.Warning : BotanyUiTheme.Text));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-nutrition"), $"{msg.NutritionLevel:0}", msg.NutritionLevel <= 8 ? BotanyUiTheme.Warning : BotanyUiTheme.Text));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-toxins"), $"{msg.Toxins:0}", msg.Toxins >= 40 ? BotanyUiTheme.Danger : BotanyUiTheme.Text));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-weeds"), $"{msg.WeedLevel:0.#}", msg.WeedLevel >= 5 ? BotanyUiTheme.Warning : BotanyUiTheme.Text));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-pests"), $"{msg.PestLevel:0.#}", msg.PestLevel >= 5 ? BotanyUiTheme.Warning : BotanyUiTheme.Text));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("hydroponics-console-field-light-mode"),
            Loc.GetString($"plant-holder-light-{msg.LightMode.ToString().ToLowerInvariant()}"),
            msg.ImproperLight ? BotanyUiTheme.Warning : BotanyUiTheme.Text));

        DetailContainer.AddChild(_styles.Section(Loc.GetString("hydroponics-console-section-warnings")));
        var extra = new List<string>();
        if (msg.ImproperHeat)
            extra.Add(Loc.GetString("plant-analyzer-warning-heat"));
        if (msg.ImproperPressure)
            extra.Add(Loc.GetString("plant-analyzer-warning-pressure"));
        if (msg.ImproperLight)
            extra.Add(Loc.GetString("plant-analyzer-warning-light"));
        if (msg.MissingGas)
            extra.Add(Loc.GetString("plant-analyzer-warning-gas"));

        DetailContainer.AddChild(extra.Count == 0
            ? _styles.Body(Loc.GetString("plant-analyzer-extra-none"), 12, BotanyUiTheme.Ok)
            : _styles.Body(string.Join("\n", extra), 12, BotanyUiTheme.Warning));
    }

    private void ShowGenetics(PlantAnalyzerScannedSeedPlantInformation msg)
    {
        DetailHeader.Text = Loc.GetString("plant-analyzer-section-genetics");
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-consume"), FormatGases(msg.ConsumeGases)));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-exude"), FormatGases(msg.ExudeGases)));

        DetailContainer.AddChild(_styles.Section(Loc.GetString("hydroponics-console-field-chems")));
        // Forge-Change-start
        if (msg.ChemicalEntries is not { Length: > 0 })
        {
            DetailContainer.AddChild(_styles.Body("—", 12, BotanyUiTheme.Empty));
        }
        else
        {
            foreach (var chem in msg.ChemicalEntries)
            {
                var text = BotanyLocalization.FormatChemical(_prototypes, chem.Id, chem.Min, chem.Max);
                DetailContainer.AddChild(_styles.Body("·  " + text, 12));
            }
        }
        // Forge-Change-end
    }

    private void ShowTolerances(PlantAnalyzerScannedSeedPlantInformation msg)
    {
        DetailHeader.Text = Loc.GetString("plant-analyzer-section-tolerances");
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-nutrient"), $"{msg.NutrientConsumption:F2}"));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-water-use"), $"{msg.WaterConsumption:F2}"));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-ideal-heat"), $"{msg.IdealHeat:F0} K"));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-heat-tol"), $"±{msg.HeatTolerance:F1} K"));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-ideal-light"), $"{msg.IdealLight:F1} cd"));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-light-tol"), $"±{msg.LightTolerance:F1} cd"));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-toxin-tol"), $"{msg.ToxinsTolerance:F1}"));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-low-p"), $"{msg.LowPressureTolerance:F1} kPa"));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-high-p"), $"{msg.HighPressureTolerance:F1} kPa"));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-pest-tol"), $"{msg.PestTolerance:F1}"));
        DetailContainer.AddChild(_styles.KeyValue(Loc.GetString("plant-analyzer-field-weed-tol"), $"{msg.WeedTolerance:F1}"));
    }

    private void ShowMutations(PlantAnalyzerScannedSeedPlantInformation msg)
    {
        DetailHeader.Text = Loc.GetString("plant-analyzer-section-mutations");

        var flags = new List<(string Name, bool On)>();
        flags.Add((Loc.GetString("plant-analyzer-mutation-turnintokudzu"), msg.Mutations.HasFlag(MutationFlags.TurnIntoKudzu)));
        flags.Add((Loc.GetString("plant-analyzer-mutation-seedless"), msg.Mutations.HasFlag(MutationFlags.Seedless)));
        flags.Add((Loc.GetString("plant-analyzer-mutation-ligneous"), msg.Mutations.HasFlag(MutationFlags.Ligneous)));
        flags.Add((Loc.GetString("plant-analyzer-mutation-canscream"), msg.Mutations.HasFlag(MutationFlags.CanScream)));
        flags.Add((Loc.GetString("plant-analyzer-mutation-unviable"), msg.Mutations.HasFlag(MutationFlags.Unviable)));
        flags.Add((Loc.GetString("plant-analyzer-mutation-radioactive"), msg.Mutations.HasFlag(MutationFlags.Radioactive)));
        flags.Add((Loc.GetString("plant-analyzer-mutation-grabber"), msg.Mutations.HasFlag(MutationFlags.CarnivorousGrab)));
        flags.Add((Loc.GetString("plant-analyzer-mutation-pest-eater"), msg.Mutations.HasFlag(MutationFlags.CarnivorousPestEater)));
        flags.Add((Loc.GetString("plant-analyzer-mutation-gene-locked"), msg.Mutations.HasFlag(MutationFlags.GeneLocked)));

        var any = false;
        foreach (var (name, on) in flags)
        {
            if (!on)
                continue;

            if (name == Loc.GetString("plant-analyzer-mutation-gene-locked"))
            {
                // Forge-Change-start
                any = true;
                if (msg.PinnedTraits is { Length: > 0 })
                {
                    DetailContainer.AddChild(_styles.Body(
                        Loc.GetString("hydroponics-console-warn-locked-detail",
                            ("traits", string.Join(", ", msg.PinnedTraits.Select(BotanyLocalization.GetMutationName)))),
                        12, BotanyUiTheme.Ok));
                }
                else
                {
                    DetailContainer.AddChild(_styles.Body("·  " + name, 12, BotanyUiTheme.Ok));
                }

                continue;
                // Forge-Change-end
            }

            any = true;
            var color = name == Loc.GetString("plant-analyzer-mutation-radioactive")
                        || name == Loc.GetString("plant-analyzer-mutation-grabber")
                        || name == Loc.GetString("plant-analyzer-mutation-unviable")
                ? BotanyUiTheme.Danger
                : BotanyUiTheme.Ok;
            DetailContainer.AddChild(_styles.Body("·  " + name, 12, color));
        }

        if (msg.MutationNames is { Length: > 0 })
        {
            foreach (var name in msg.MutationNames)
            {
                any = true;
                // Forge-Change
                DetailContainer.AddChild(_styles.Body("·  " + BotanyLocalization.GetMutationName(name), 12, BotanyUiTheme.Harvest));
            }
        }

        if (!any)
            DetailContainer.AddChild(_styles.Body("—", 12, BotanyUiTheme.Empty));

        DetailContainer.AddChild(_styles.Section(Loc.GetString("plant-analyzer-section-speciation")));
        if (msg.Speciation is not { Length: > 0 })
        {
            DetailContainer.AddChild(_styles.Body("—", 12, BotanyUiTheme.Empty));
        }
        else
        {
            foreach (var species in msg.Speciation)
                DetailContainer.AddChild(_styles.Body("·  " + Loc.GetString(species), 12));
        }
    }

    private void ShowNoData()
    {
        DetailHeader.Text = Loc.GetString("plant-analyzer-detail-header");
        DetailContainer.DisposeAllChildren();
        DetailContainer.AddChild(_styles.Sub(Loc.GetString("plant-analyzer-window-no-seed-information-text")));
    }

    private string FormatGases(GasFlags flags)
    {
        var output = new StringBuilder();
        AppendGas(output, flags, GasFlags.Nitrogen, "gases-nitrogen");
        AppendGas(output, flags, GasFlags.Oxygen, "gases-oxygen");
        AppendGas(output, flags, GasFlags.CarbonDioxide, "gases-co2");
        AppendGas(output, flags, GasFlags.Plasma, "gases-plasma");
        AppendGas(output, flags, GasFlags.Tritium, "gases-tritium");
        AppendGas(output, flags, GasFlags.WaterVapor, "gases-water-vapor");
        AppendGas(output, flags, GasFlags.Ammonia, "gases-ammonia");
        AppendGas(output, flags, GasFlags.NitrousOxide, "gases-n2o");
        AppendGas(output, flags, GasFlags.Frezon, "gases-frezon");
        AppendGas(output, flags, GasFlags.BZ, "gases-bz");
        AppendGas(output, flags, GasFlags.Healium, "gases-healium");
        AppendGas(output, flags, GasFlags.Nitrium, "gases-nitrium");
        AppendGas(output, flags, GasFlags.Pluoxium, "gases-pluoxium");
        return output.Length == 0 ? Loc.GetString("plant-analyzer-plant-gases-none") : output.ToString();
    }

    private static void AppendGas(StringBuilder output, GasFlags flags, GasFlags flag, string loc)
    {
        if (!flags.HasFlag(flag))
            return;
        if (output.Length > 0)
            output.Append(", ");
        output.Append(Loc.GetString(loc));
    }

    private static Color HealthColor(float health, float endurance)
    {
        if (endurance <= 0)
            return BotanyUiTheme.Danger;
        var ratio = health / endurance;
        if (ratio <= 0.25f)
            return BotanyUiTheme.Danger;
        if (ratio <= 0.5f)
            return BotanyUiTheme.Warning;
        return BotanyUiTheme.Ok;
    }

    private void ApplyChrome()
    {
        Background.ModulateSelfOverride = BotanyUiTheme.WindowBackground;
        Border.ModulateSelfOverride = BotanyUiTheme.WindowBorder;
        CloseButton.ModulateSelfOverride = BotanyUiTheme.CloseButton;
        ContentBorder.ModulateSelfOverride = BotanyUiTheme.ContentBorder;
        ContentBackground.ModulateSelfOverride = BotanyUiTheme.ContentBackground;

        TitleLabel.FontOverride = _styles.GetBoldFont(18);
        TitleLabel.FontColorOverride = BotanyUiTheme.Heading;
        PlantNameLabel.FontOverride = _styles.GetRegularFont(12);
        PlantNameLabel.FontColorOverride = BotanyUiTheme.SubText;
        StatusLabel.FontOverride = _styles.GetBoldFont(12);
        StatusLabel.FontColorOverride = BotanyUiTheme.Text;
        DetailHeader.FontOverride = _styles.GetBoldFont(13);
        DetailHeader.FontColorOverride = BotanyUiTheme.Heading;
        ListHeader.FontOverride = _styles.GetBoldFont(13);
        ListHeader.FontColorOverride = BotanyUiTheme.Heading;
        OsLabel.FontOverride = _styles.GetRegularFont(11);
        OsLabel.FontColorOverride = BotanyUiTheme.SubText;

        BotanyUiStyles.ApplyPanel(MainDivider, BotanyUiTheme.Divider, BotanyUiTheme.Divider, 0);
        BotanyUiStyles.ApplyPanel(DetailPanel, BotanyUiTheme.ListBackground, BotanyUiTheme.ListBorder);
        BotanyUiStyles.ApplyPanel(ListPanel, BotanyUiTheme.ListBackground, BotanyUiTheme.ListBorder);
    }
}
