using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.Horizon.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.Horizon.UI;

[GenerateTypedNameReferences]
public sealed partial class HorizonConsoleWindow : FancyWindow
{
    public HorizonConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(HorizonConsoleBoundUserInterfaceState state)
    {
        StatusLabel.Text = $"{state.Phase} / {state.Cluster} / IFF {state.Iff}";
        OrganizationLabel.Text = state.Organization;
        AccessLabel.Text = $"{state.Access} (+{state.Contribution} / -{state.Damage})";
        ResourcesLabel.Text = $"{state.RawResources} raw / {state.Components} comp / {state.Energy} energy";
        CountsLabel.Text = $"{state.Objects} objects / {state.Orders} orders / {state.Incidents} incidents";
        NeedLabel.Text = state.Need;
        DiagnosticsLabel.Text = state.Diagnostics;
        ContributionHintLabel.Text = state.AcceptsResources
            ? Loc.GetString("horizon-console-contribution-hint")
            : Loc.GetString("horizon-console-communication-hint");
        HandoffButton.Visible = state.CanHandoff || state.CarrierControlled;
        HandoffButton.Disabled = !state.CanHandoff;
        HandoffButton.Text = state.CarrierControlled
            ? Loc.GetString("horizon-console-ai-deployed")
            : Loc.GetString("horizon-console-ai-handoff");
    }
}
