using Content.Client.UserInterface.Controls;
using Content.Shared.Radio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Radio.Ui;

[GenerateTypedNameReferences]
public sealed partial class ConfigurableEncryptionKeyMenu : FancyWindow
{
    public event Action<string>? OnFrequencyChanged;

    public ConfigurableEncryptionKeyMenu()
    {
        RobustXamlLoader.Load(this);

        FrequencyLineEdit.OnTextEntered += e => OnFrequencyChanged?.Invoke(e.Text);
        FrequencyLineEdit.OnFocusExit += e => OnFrequencyChanged?.Invoke(e.Text);
    }

    public void Update(ConfigurableEncryptionKeyBoundUIState state)
    {
        FrequencyLineEdit.Text = state.Frequency.ToString();
    }
}
