- type: department
  id: Empire
  name: department-Empire
  description: department-Empire-description
  color: "#ab7a52"
  weight: 50
  roles:
  - Praefect # Imperial Guardian Commander
  - Inquisitor # Just senior inquisitor guy
  - Consul # Imperial Diplomatic Corps.
  - Tessarian # Senior Officer
  - Arbiter # Senior Officer: Sheriff
  - Cardinal # Senior Officer: idk what he do
  - Praetorian # Sub Officer
  - EmpireSmallInquisitor # Sub Officer: Inquisitor squad
  # - EmpireOperator # Sub Officer: Drone Operator
  - Auxilia # Soldier
  - EmpireApotek # Soldier: Medical
  - EmpireTechnican # Soldier: Technican
  - Neophyte # Cadet/Recruit

- type: department
  id: Renegates
  name: department-Renegates
  description: department-Renegates-description
  color: "#333333"
  weight: 50
  roles:
  - Baron
  - Draftsman
  - Overseer
  - Watchman
  - Quack
  - Foreman
  - Flunky
  - Militia

- type: department
  id: TSF
  name: department-TSF
  description: department-TSF-description
  color: "#2d6f9f"
  weight: 55
  roles:
  - TsfCommandingOfficer
  - TsfExecutiveOfficer
  - TsfSeniorOfficer
  - TsfSeniorAide
  - TsfAmbassador
  - TsfRanger
  - TsfRecruit
  - TsfEngineer
  - TsfMedic
  - TsfSl
  - TsfCrew
  - TsfCrewOfficer
