using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.Silicons.StationAi;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Forge.Silicons.StationAi;

[GenerateTypedNameReferences]
public sealed partial class StationAiCustomizationWindow : FancyWindow
{
    [Dependency] private readonly IConfigurationManager _configuration = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    public event Action<string, ProtoId<StationAiScreenPrototype>, Color>? OnApply;

    private readonly Dictionary<ProtoId<StationAiScreenPrototype>, Button> _screens = new();
    private readonly ButtonGroup _screenGroup = new(false);
    private ProtoId<StationAiScreenPrototype> _selectedScreen = "StationAiScreenDefault";
    private string _forceNamePrefix = string.Empty;
    private TimeSpan _cooldownEnd;
    private bool _screensInitialized;

    public StationAiCustomizationWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        NameEdit.IsValid = IsNameValid;
        ColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv;
        SelectedPreview.DisplayRect.Stretch = TextureRect.StretchMode.KeepCentered;
        SelectedPreview.DisplayRect.TextureScale = new Vector2(4f, 4f);

        NameEdit.OnTextChanged += _ => UpdateApplyState();
        ColorSelector.OnColorChanged += UpdatePreviewColor;
        ApplyButton.OnPressed += _ => Apply();
    }

    private void EnsureScreens()
    {
        if (_screensInitialized)
            return;

        _screensInitialized = true;
        foreach (var screen in _prototypes.EnumeratePrototypes<StationAiScreenPrototype>().OrderBy(screen => screen.ID))
            AddScreen(screen);
    }

    private void AddScreen(StationAiScreenPrototype screen)
    {
        var name = Loc.GetString(screen.Name);
        var button = new Button
        {
            MinSize = new Vector2(135, 104),
            HorizontalExpand = true,
            ToggleMode = true,
            Group = _screenGroup,
            ToolTip = name,
        };

        var preview = new TextureRect
        {
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            Texture = _entityManager.System<SpriteSystem>().Frame0(new SpriteSpecifier.Rsi(screen.Sprite, screen.State)),
            Stretch = TextureRect.StretchMode.KeepCentered,
            TextureScale = new Vector2(2f, 2f),
        };

        var label = new Label
        {
            Text = name,
            ClipText = true,
            HorizontalAlignment = HAlignment.Center,
        };

        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
        };
        content.AddChild(preview);
        content.AddChild(label);
        button.AddChild(content);

        button.OnPressed += _ => SelectScreen(screen.ID);
        ScreenGrid.AddChild(button);
        _screens.Add(screen.ID, button);
    }

    private void SelectScreen(ProtoId<StationAiScreenPrototype> screen)
    {
        if (!_screens.ContainsKey(screen) || !_prototypes.TryIndex(screen, out var prototype))
            return;

        _selectedScreen = screen;
        _screens[screen].Pressed = true;
        SelectedPreview.SetFromSpriteSpecifier(new SpriteSpecifier.Rsi(prototype.Sprite, prototype.State));
        UpdatePreviewColor(ColorSelector.Color);
    }

    public void UpdateState(StationAiCustomizationState state)
    {
        EnsureScreens();
        _forceNamePrefix = state.ForceNamePrefix;
        NamePrefixLabel.Text = _forceNamePrefix;
        NamePrefixLabel.Visible = _forceNamePrefix.Length > 0;
        NameEdit.Text = state.Name;
        ColorSelector.Color = state.Color;
        SelectScreen(_screens.ContainsKey(state.Screen) ? state.Screen : (ProtoId<StationAiScreenPrototype>) "StationAiScreenDefault");
        _cooldownEnd = _timing.CurTime + TimeSpan.FromSeconds(state.CooldownSeconds);
        UpdateCooldown();
    }

    private void Apply()
    {
        if (!TryGetNormalizedName(out var name) ||
            !_screens.ContainsKey(_selectedScreen) ||
            !StationAiCustomizationValidator.TryNormalizeColor(ColorSelector.Color, out var color))
        {
            UpdateApplyState();
            return;
        }

        OnApply?.Invoke(name, _selectedScreen, color);
    }

    private void UpdatePreviewColor(Color color)
    {
        if (StationAiCustomizationValidator.TryNormalizeColor(color, out var normalized))
            SelectedPreview.DisplayRect.Modulate = normalized;

        UpdateApplyState();
    }

    private bool IsNameValid(string text)
    {
        return StationAiCustomizationValidator.TryNormalizeNamePart(
            text,
            _forceNamePrefix,
            _configuration.GetCVar(CCVars.RestrictedNames),
            _configuration.GetCVar(CCVars.ICNameCase),
            out _,
            out _);
    }

    private bool TryGetNormalizedName(out string name)
    {
        return StationAiCustomizationValidator.TryNormalizeNamePart(
            NameEdit.Text,
            _forceNamePrefix,
            _configuration.GetCVar(CCVars.RestrictedNames),
            _configuration.GetCVar(CCVars.ICNameCase),
            out name,
            out _);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateCooldown();
    }

    private void UpdateCooldown()
    {
        var remaining = Math.Max(0, (int) Math.Ceiling((_cooldownEnd - _timing.CurTime).TotalSeconds));
        CooldownLabel.Visible = remaining > 0;
        CooldownLabel.Text = remaining > 0
            ? Loc.GetString("station-ai-customization-cooldown", ("seconds", remaining))
            : string.Empty;
        UpdateApplyState(remaining);
    }

    private void UpdateApplyState(int? cooldown = null)
    {
        var invalidName = !TryGetNormalizedName(out _);
        var invalidColor = !StationAiCustomizationValidator.TryNormalizeColor(ColorSelector.Color, out _);
        ValidationLabel.Visible = invalidName || invalidColor;
        ValidationLabel.Text = invalidColor
            ? Loc.GetString("station-ai-customization-invalid-color")
            : invalidName
                ? Loc.GetString("station-ai-customization-invalid-name")
                : string.Empty;

        var remaining = cooldown ?? Math.Max(0, (int) Math.Ceiling((_cooldownEnd - _timing.CurTime).TotalSeconds));
        ApplyButton.Disabled = remaining > 0 || invalidName || invalidColor || !_screens.ContainsKey(_selectedScreen);
    }
}
