using System.Linq;
using System.Numerics;
using Content.Client.Materials.UI;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.ShipWeapons;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.ShipWeapons.UI;

[GenerateTypedNameReferences]
public sealed partial class ShipWeaponFabricatorWindow : FancyWindow
{
    private static readonly Vector2 CompactSize = new(640, 420);
    private static readonly Vector2 ExpandedSize = new(980, 760);

    private readonly ShipWeaponFabricatorBoundUserInterface _owner;
    private readonly MaterialStorageUIController _materialUiController;
    private bool _expanded;

    public ShipWeaponFabricatorWindow(ShipWeaponFabricatorBoundUserInterface owner)
    {
        RobustXamlLoader.Load(this);
        _owner = owner;
        _materialUiController = UserInterfaceManager.GetUIController<MaterialStorageUIController>();
        MinSize = SetSize = CompactSize;

        StartButton.OnPressed += _ => _owner.SendStart();
        EjectButton.OnPressed += _ => _owner.SendEject();
        UpdateState(new ShipWeaponFabricatorState(
            null,
            null,
            Loc.GetString("ship-weapon-fabricator-ui-no-board-details"),
            Loc.GetString("ship-weapon-fabricator-ui-no-loaded-parts"),
            new(),
            new(),
            Loc.GetString("ship-weapon-fabricator-ui-status-no-board"),
            null,
            false,
            false,
            false,
            0,
            null));
    }

    public void UpdateState(ShipWeaponFabricatorState state)
    {
        var hasBoard = state.BoardName != null;
        if (hasBoard != _expanded)
        {
            _expanded = hasBoard;
            MinSize = SetSize = hasBoard ? ExpandedSize : CompactSize;
        }

        var boardText = state.BoardName ?? Loc.GetString("ship-weapon-fabricator-ui-none");
        if (state.QueueText != null)
            boardText = $"{boardText}\n{state.QueueText}";

        BoardNameLabel.SetMessage(boardText);
        TargetNameLabel.SetMessage(state.TargetName ?? " ");
        TargetInfoLabel.SetMessage(state.TargetName ?? Loc.GetString("ship-weapon-fabricator-ui-none"));
        RequirementsLabel.SetMessage(state.RequirementsText);
        StatusLabel.SetMessage(state.StatusText);
        StartButton.Disabled = !state.CanStart;
        EjectButton.Disabled = !state.CanEject;
        RebuildLoadedMaterials(state);
        RebuildLoadedParts(state);

        if (state.TargetPrototypeId != null)
            TargetSprite.SetPrototype(state.TargetPrototypeId);
        else
            TargetSprite.Visible = false;

        if (state.TargetPrototypeId != null)
            TargetSprite.Visible = true;
    }

    private void RebuildLoadedMaterials(ShipWeaponFabricatorState state)
    {
        LoadedMaterialsList.RemoveAllChildren();

        if (state.LoadedMaterials.Count == 0)
        {
            LoadedMaterialsList.AddChild(LoadedMaterialsEmptyLabel);
            return;
        }

        var compatible = state.LoadedMaterials.Where(x => x.Compatible).ToList();
        var incompatible = state.LoadedMaterials.Where(x => !x.Compatible).ToList();

        if (compatible.Count > 0)
        {
            LoadedMaterialsList.AddChild(new Label
            {
                Text = Loc.GetString("ship-weapon-fabricator-ui-loaded-materials-compatible-header"),
                Margin = new Thickness(0, 0, 0, 4)
            });

            foreach (var material in compatible)
                LoadedMaterialsList.AddChild(BuildMaterialRow(material));
        }

        if (incompatible.Count > 0)
        {
            LoadedMaterialsList.AddChild(new Label
            {
                Text = Loc.GetString("ship-weapon-fabricator-ui-loaded-materials-incompatible-header"),
                Margin = new Thickness(0, compatible.Count > 0 ? 8 : 0, 0, 4)
            });

            foreach (var material in incompatible)
                LoadedMaterialsList.AddChild(BuildMaterialRow(material));
        }
    }

    private void RebuildLoadedParts(ShipWeaponFabricatorState state)
    {
        LoadedPartsList.RemoveAllChildren();

        if (state.LoadedParts.Count == 0)
        {
            LoadedPartsList.AddChild(LoadedPartsEmptyLabel);
            LoadedPartsEmptyLabel.Text = state.LoadedPartsText;
            return;
        }

        var compatible = state.LoadedParts.Where(x => x.Compatible).ToList();
        var incompatible = state.LoadedParts.Where(x => !x.Compatible).ToList();

        if (compatible.Count > 0)
        {
            LoadedPartsList.AddChild(new Label
            {
                Text = Loc.GetString("ship-weapon-fabricator-ui-loaded-parts-compatible-header"),
                Margin = new Thickness(0, 0, 0, 4)
            });

            foreach (var part in compatible)
                LoadedPartsList.AddChild(BuildPartRow(part));
        }

        if (incompatible.Count > 0)
        {
            LoadedPartsList.AddChild(new Label
            {
                Text = Loc.GetString("ship-weapon-fabricator-ui-loaded-parts-incompatible-header"),
                Margin = new Thickness(0, compatible.Count > 0 ? 8 : 0, 0, 4)
            });

            foreach (var part in incompatible)
                LoadedPartsList.AddChild(BuildPartRow(part));
        }
    }

    private BoxContainer BuildPartRow(ShipWeaponFabricatorLoadedPartEntry part)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true
        };

        var text = Loc.GetString(
            part.Compatible
                ? "ship-weapon-fabricator-ui-stored-part-with-rating-line"
                : "ship-weapon-fabricator-ui-stored-part-incompatible-line",
            ("count", part.Current),
            ("name", part.DisplayName),
            ("rating", part.Rating));

        var label = new Label
        {
            Text = text,
            HorizontalExpand = true,
            ClipText = true,
            Margin = new Thickness(0, 4, 4, 4)
        };

        row.AddChild(label);

        int[] amounts = { 1, 5, 10, 30 };
        for (var i = 0; i < amounts.Length; i++)
        {
            var amount = amounts[i];
            var styleClass = StyleBase.ButtonOpenBoth;
            if (i == 0)
                styleClass = StyleBase.ButtonOpenRight;
            else if (i == amounts.Length - 1)
                styleClass = StyleBase.ButtonOpenLeft;

            var button = new Button
            {
                Text = amount.ToString(),
                MinWidth = 45,
                Disabled = part.Current < amount,
                StyleClasses = { styleClass }
            };
            button.OnPressed += _ => _owner.SendEjectPart(part.PartPrototype, amount);
            row.AddChild(button);
        }

        return row;
    }

    private BoxContainer BuildMaterialRow(ShipWeaponFabricatorLoadedMaterialEntry material)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true
        };

        string text;
        if (material.Compatible && material.Required is { } required)
        {
            text = Loc.GetString("ship-weapon-fabricator-ui-requirement-line",
                ("current", material.Current),
                ("required", required),
                ("name", material.DisplayName));
        }
        else if (material.Compatible)
        {
            text = Loc.GetString("ship-weapon-fabricator-ui-stored-material-line",
                ("count", material.Current),
                ("name", material.DisplayName));
        }
        else
        {
            text = Loc.GetString("ship-weapon-fabricator-ui-stored-material-incompatible-line",
                ("count", material.Current),
                ("name", material.DisplayName));
        }

        var label = new Label
        {
            Text = text,
            HorizontalExpand = true,
            ClipText = true,
            Margin = new Thickness(0, 4, 4, 4)
        };
        row.AddChild(label);

        int[] amounts = { 1, 5, 10, 30 };
        for (var i = 0; i < amounts.Length; i++)
        {
            var amount = amounts[i];
            var styleClass = StyleBase.ButtonOpenBoth;
            if (i == 0)
                styleClass = StyleBase.ButtonOpenRight;
            else if (i == amounts.Length - 1)
                styleClass = StyleBase.ButtonOpenLeft;

            var button = new Button
            {
                Text = amount.ToString(),
                MinWidth = 45,
                Disabled = material.Current < amount,
                StyleClasses = { styleClass }
            };
            button.OnPressed += _ => _materialUiController.SendLatheEjectMessage(_owner.Owner, material.MaterialId, amount);
            row.AddChild(button);
        }

        return row;
    }
}
