using System.Numerics;
using Content.Client.Shuttles.UI;
using Content.Shared._Forge.ShipyardService;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Physics.Components;

namespace Content.Client._Forge.ShipyardService.UI;

[GenerateTypedNameReferences]
public sealed partial class ShipyardServiceGridControl : BaseShuttleControl
{
    public static readonly Color ReinforceColor = Color.FromHex("#d4a017");
    public static readonly Color PlastitaniumColor = Color.FromHex("#7ec8e3");
    public static readonly Color PartsColor = Color.FromHex("#e07a3d");
    public static readonly Color RepairColor = Color.FromHex("#e05050");

    public EntityUid? Shuttle;
    public List<ShipyardServiceUpgradeMarker> Markers = new();
    public readonly HashSet<int> Selected = new();
    public int? HoveredId;

    public bool ShowReinforce = true;
    public bool ShowPlastitanium = true;
    public bool ShowParts = true;
    public bool ShowRepair = true;

    public event Action? SelectionChanged;
    public event Action? HoveredChanged;

    protected override bool Draggable => true;

    public ShipyardServiceGridControl() : base(8f, 128f, 32f)
    {
        RobustXamlLoader.Load(this);
    }

    public void SetShuttle(EntityUid? shuttle)
    {
        Shuttle = shuttle;
        if (shuttle == null || !EntManager.TryGetComponent(shuttle.Value, out MapGridComponent? grid))
            return;

        var size = Math.Max(grid.LocalAABB.Width, grid.LocalAABB.Height);
        var range = Math.Clamp(size * 0.55f + 4f, 12f, 96f);
        WorldRange = range;
        ActualRadarRange = range;
        Offset = EntManager.TryGetComponent(shuttle.Value, out PhysicsComponent? physics)
            ? physics.LocalCenter
            : grid.LocalAABB.Center;
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        if (Shuttle == null || Markers.Count == 0)
            return;

        var localPixel = args.PointerLocation.Position - GlobalPixelPosition;
        if (!TryPickMarker(InverseMapPosition(localPixel), out var closest))
            return;

        if (!Selected.Add(closest.Id))
            Selected.Remove(closest.Id);

        SelectionChanged?.Invoke();
        args.Handle();
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        if (Shuttle == null || Markers.Count == 0)
        {
            SetHovered(null);
            return;
        }

        if (!TryPickMarker(InverseMapPosition(args.RelativePixelPosition), out var marker))
        {
            SetHovered(null);
            return;
        }

        SetHovered(marker.Id);
    }

    private void SetHovered(int? id)
    {
        if (HoveredId == id)
            return;

        HoveredId = id;
        HoveredChanged?.Invoke();
    }

    private bool TryPickMarker(Vector2 gridLocal, out ShipyardServiceUpgradeMarker marker)
    {
        marker = default!;
        ShipyardServiceUpgradeMarker? closest = null;
        var closestDist = 0.85f;

        foreach (var candidate in Markers)
        {
            if (!IsVisible(candidate.Action))
                continue;

            var dist = (candidate.LocalPosition - gridLocal).Length();
            if (dist >= closestDist)
                continue;

            closest = candidate;
            closestDist = dist;
        }

        if (closest == null && Shuttle != null && EntManager.TryGetComponent(Shuttle.Value, out MapGridComponent? grid))
        {
            var tile = Maps.CoordinatesToTile(Shuttle.Value, grid, new EntityCoordinates(Shuttle.Value, gridLocal));
            foreach (var candidate in Markers)
            {
                if (candidate.Tile == tile && IsVisible(candidate.Action))
                {
                    closest = candidate;
                    break;
                }
            }
        }

        if (closest == null)
            return false;

        marker = closest;
        return true;
    }

    public bool IsVisible(ShipyardServiceAction action)
    {
        return action switch
        {
            ShipyardServiceAction.Reinforce => ShowReinforce,
            ShipyardServiceAction.Plastitanium => ShowPlastitanium,
            ShipyardServiceAction.UpgradeParts => ShowParts,
            ShipyardServiceAction.Repair => ShowRepair,
            _ => false
        };
    }

    public static Color GetMarkerColor(ShipyardServiceAction action)
    {
        return action switch
        {
            ShipyardServiceAction.Reinforce => ReinforceColor,
            ShipyardServiceAction.Plastitanium => PlastitaniumColor,
            ShipyardServiceAction.UpgradeParts => PartsColor,
            ShipyardServiceAction.Repair => RepairColor,
            _ => Color.White
        };
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);
        DrawBacking(handle);

        if (Shuttle == null || !EntManager.TryGetComponent(Shuttle.Value, out MapGridComponent? grid))
        {
            DrawNoSignal(handle);
            return;
        }

        DrawCircles(handle);

        var gridToView = Matrix3x2.CreateTranslation(-Offset)
                         * Matrix3x2.CreateScale(MinimapScale, -MinimapScale)
                         * Matrix3x2.CreateTranslation(MidPointVector);

        DrawGrid(handle, gridToView, (Shuttle.Value, grid), Color.FromHex("#6ea56e"), 0.18f);

        var tileSize = grid.TileSize;
        DrawMarkers(handle, (Shuttle.Value, grid), gridToView, tileSize, repairPass: true);
        DrawMarkers(handle, (Shuttle.Value, grid), gridToView, tileSize, repairPass: false);
    }

    private void DrawMarkers(
        DrawingHandleScreen handle,
        Entity<MapGridComponent> shuttle,
        Matrix3x2 gridToView,
        float tileSize,
        bool repairPass)
    {
        foreach (var marker in Markers)
        {
            if (!IsVisible(marker.Action))
                continue;

            var isRepair = marker.Action == ShipyardServiceAction.Repair;
            if (isRepair != repairPass)
                continue;

            var bl = Maps.TileToVector(shuttle, marker.Tile);
            var inset = isRepair ? 0.04f * tileSize : 0.18f * tileSize;
            var p1 = Vector2.Transform(bl + new Vector2(inset, inset), gridToView);
            var p2 = Vector2.Transform(bl + new Vector2(tileSize - inset, tileSize - inset), gridToView);
            var left = Math.Min(p1.X, p2.X);
            var top = Math.Min(p1.Y, p2.Y);
            var right = Math.Max(p1.X, p2.X);
            var bottom = Math.Max(p1.Y, p2.Y);
            var box = new UIBox2(left, top, right, bottom);
            var selected = Selected.Contains(marker.Id);
            var hovered = HoveredId == marker.Id;
            var color = GetMarkerColor(marker.Action);
            handle.DrawRect(box, color.WithAlpha(selected ? 0.9f : hovered ? 0.7f : 0.42f));
            handle.DrawRect(box, selected || hovered ? Color.White : color.WithAlpha(0.95f), false);
        }
    }
}
