using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.ShipyardService;
using Content.Shared._NF.Bank;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Forge.ShipyardService.UI;

[GenerateTypedNameReferences]
public sealed partial class ShipyardServiceWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;

    private ShipyardServiceBoundUserInterfaceState _state = new();
    private bool _updatingShuttles;

    public event Action? RepairPressed;
    public event Action? UpgradePartsPressed;
    public event Action? ReinforcePressed;
    public event Action? PlastitaniumPressed;
    public event Action<NetEntity>? ShuttleSelected;
    public event Action? OpenGridPressed;

    public ShipyardServiceWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        RepairButton.OnPressed += _ => RepairPressed?.Invoke();
        UpgradePartsButton.OnPressed += _ => UpgradePartsPressed?.Invoke();
        ReinforceButton.OnPressed += _ => ReinforcePressed?.Invoke();
        PlastitaniumButton.OnPressed += _ => PlastitaniumPressed?.Invoke();
        GridButton.OnPressed += _ => OpenGridPressed?.Invoke();
        ShuttleOption.OnItemSelected += args =>
        {
            ShuttleOption.SelectId(args.Id);
            if (_updatingShuttles)
                return;
            if (ShuttleOption.GetItemMetadata(args.Id) is NetEntity shuttle)
                ShuttleSelected?.Invoke(shuttle);
        };
    }

    public void UpdateState(ShipyardServiceBoundUserInterfaceState state)
    {
        _state = state;
        BalanceLabel.Text = state.Balance < 0
            ? Loc.GetString("shipyard-service-no-bank")
            : BankSystemExtensions.ToSpesoString(state.Balance);

        RebuildShuttleOptions(state);
        RefreshQuote(state.Quote);
    }

    private void RebuildShuttleOptions(ShipyardServiceBoundUserInterfaceState state)
    {
        _updatingShuttles = true;
        ShuttleOption.Clear();

        if (state.Shuttles.Count == 0)
        {
            ShuttleOption.AddItem(Loc.GetString("shipyard-service-no-shuttle"));
            ShuttleOption.Disabled = true;
            _updatingShuttles = false;
            return;
        }

        ShuttleOption.Disabled = false;
        var selectedId = 0;
        for (var i = 0; i < state.Shuttles.Count; i++)
        {
            var entry = state.Shuttles[i];
            ShuttleOption.AddItem($"{entry.Name} ({entry.ClassLabel})");
            ShuttleOption.SetItemMetadata(i, entry.Shuttle);
            if (state.SelectedShuttle == entry.Shuttle)
                selectedId = i;
        }

        ShuttleOption.SelectId(selectedId);
        _updatingShuttles = false;
    }

    private void RefreshQuote(ShipyardServiceQuote quote)
    {
        if (!quote.HasShuttle)
        {
            ShuttleInfoLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("shipyard-service-no-shuttle-desc")));
            ClickHintLabel.SetMessage(new FormattedMessage());
            RepairInfoLabel.SetMessage(new FormattedMessage());
            PartsInfoLabel.SetMessage(new FormattedMessage());
            ReinforceInfoLabel.SetMessage(new FormattedMessage());
            PlastitaniumInfoLabel.SetMessage(new FormattedMessage());
            RepairButton.Disabled = true;
            UpgradePartsButton.Disabled = true;
            ReinforceButton.Disabled = true;
            PlastitaniumButton.Disabled = true;
            GridButton.Disabled = true;
            return;
        }

        ShuttleInfoLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("shipyard-service-shuttle-info",
            ("name", FormattedMessage.EscapeText(quote.ShuttleName)),
            ("class", FormattedMessage.EscapeText(quote.ClassLabel)),
            ("price", BankSystemExtensions.ToSpesoString(quote.VesselPrice)))));
        ClickHintLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("shipyard-service-click-hint")));

        RepairInfoLabel.SetMessage(GetRepairMarkup(quote));
        PartsInfoLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("shipyard-service-parts-info",
            ("count", quote.PartCount),
            ("amount", BankSystemExtensions.ToSpesoString(quote.PartCost)))));
        ReinforceInfoLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("shipyard-service-reinforce-info",
            ("count", quote.ReinforceCount),
            ("amount", BankSystemExtensions.ToSpesoString(quote.ReinforceCost)))));
        PlastitaniumInfoLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("shipyard-service-plastitanium-info",
            ("count", quote.PlastitaniumCount),
            ("amount", BankSystemExtensions.ToSpesoString(quote.PlastitaniumCost)))));

        RepairButton.Disabled = quote.RepairCount <= 0 || quote.RepairOnCooldown;
        UpgradePartsButton.Disabled = quote.PartCount <= 0;
        ReinforceButton.Disabled = quote.ReinforceCount <= 0;
        PlastitaniumButton.Disabled = quote.PlastitaniumCount <= 0;
        GridButton.Disabled = false;
    }

    private FormattedMessage GetRepairMarkup(ShipyardServiceQuote quote)
    {
        if (quote.RepairOnCooldown)
        {
            var remaining = quote.RepairReadyAt - _timing.CurTime;
            if (remaining < TimeSpan.Zero)
                remaining = TimeSpan.Zero;

            return FormattedMessage.FromMarkupOrThrow(Loc.GetString("shipyard-service-repair-info-cooldown",
                ("minutes", Math.Max(1, (int) Math.Ceiling(remaining.TotalMinutes)))));
        }

        if (quote.OccupancyDue && quote.OccupancyFee > 0)
        {
            return FormattedMessage.FromMarkupOrThrow(Loc.GetString("shipyard-service-repair-info-occupancy",
                ("count", quote.RepairCount),
                ("repair", BankSystemExtensions.ToSpesoString(quote.RepairWorkCost)),
                ("occupancy", BankSystemExtensions.ToSpesoString(quote.OccupancyFee)),
                ("amount", BankSystemExtensions.ToSpesoString(quote.RepairCost))));
        }

        return FormattedMessage.FromMarkupOrThrow(Loc.GetString("shipyard-service-repair-info",
            ("count", quote.RepairCount),
            ("amount", BankSystemExtensions.ToSpesoString(quote.RepairCost))));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_state.Quote.HasShuttle && _state.Quote.RepairOnCooldown)
            RefreshQuote(_state.Quote);
    }
}
