using Content.Client._Forge.Radio.Ui;
using Content.Client.UserInterface.Controls;
using Content.Shared._NC.Radio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._NC.Radio.UI;

[GenerateTypedNameReferences]
public sealed partial class HandheldRadioMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    public event Action<bool>? OnMicPressed;
    public event Action<bool>? OnSpeakerPressed;
    public event Action<string>? OnFrequencyChanged;

    private bool _updating;
    private bool _editingFrequency;

    public HandheldRadioMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        MicButton.OnPressed += args => OnMicPressed?.Invoke(args.Button.Pressed);
        SpeakerButton.OnPressed += args => OnSpeakerPressed?.Invoke(args.Button.Pressed);

        FrequencyLineEdit.OnTextChanged += _ =>
        {
            _editingFrequency = true;
            PopularFrequencyOptions.SelectId(RadioFrequencyPresetUi.CustomOptionId);
        };
        FrequencyLineEdit.OnTextEntered += e => SubmitFrequency(e.Text);
        FrequencyLineEdit.OnFocusExit += e => SubmitFrequency(e.Text);

        RadioFrequencyPresetUi.Populate(PopularFrequencyOptions, _prototypes);
        PopularFrequencyOptions.OnItemSelected += args =>
        {
            if (_updating)
                return;

            PopularFrequencyOptions.SelectId(args.Id);
            if (args.Id == RadioFrequencyPresetUi.CustomOptionId)
            {
                _editingFrequency = true;
                FrequencyLineEdit.GrabKeyboardFocus();
                return;
            }

            SubmitFrequency(args.Id.ToString());
        };
    }

    private void SubmitFrequency(string frequency)
    {
        _editingFrequency = false;
        OnFrequencyChanged?.Invoke(frequency);
    }

    public void Update(HandheldRadioBoundUIState state)
    {
        _updating = true;
        MicButton.Pressed = state.MicEnabled;
        SpeakerButton.Pressed = state.SpeakerEnabled;
        if (!_editingFrequency)
        {
            FrequencyLineEdit.Text = state.Frequency.ToString();
            RadioFrequencyPresetUi.Select(PopularFrequencyOptions, state.Frequency);
        }
        FrequencyLineEdit.PlaceHolder = Loc.GetString("handheld-radio-custom-placeholder",
            ("min", state.MinFrequency),
            ("max", state.MaxFrequency));
        _updating = false;
    }
}
