using System.Linq;
using Content.Client.Decals;
using Content.Client.Decals.UI;
using Content.Shared.Decals;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._Forge.Mapping.UI;

[GenerateTypedNameReferences]
public sealed partial class MappingPaletteWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public DecalPlacementSystem DecalSystem = default!;

    private PaletteColorPicker? _picker;
    private ProtoId<DecalPrototype>? _id;
    private Color _decalColor = Color.White;
    private float _decalRotation;
    private bool _decalSnap = true;
    private int _decalZIndex;
    private bool _decalCleanable;
    private bool _decalAuto;
    private FloatSpinBox _decalRotationSpin = default!;

    public MappingPaletteWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _decalRotationSpin = new FloatSpinBox(90.0f, 0) { HorizontalExpand = true };
        DecalSpinBoxContainer.AddChild(_decalRotationSpin);

        DecalColorPicker.OnColorChanged += OnDecalColorPicked;
        DecalPickerOpen.OnPressed += OnDecalPickerOpenPressed;
        _decalRotationSpin.OnValueChanged += args =>
        {
            _decalRotation = args.Value;
            UpdateDecal();
        };
        DecalEnableAuto.OnToggled += args =>
        {
            _decalAuto = args.Pressed;
            if (_id is { } id)
                SelectDecal(id);
        };
        DecalEnableSnap.OnToggled += args =>
        {
            _decalSnap = args.Pressed;
            UpdateDecal();
        };
        DecalEnableCleanable.OnToggled += args =>
        {
            _decalCleanable = args.Pressed;
            UpdateDecal();
        };
        DecalZIndexSpinBox.ValueChanged += args =>
        {
            _decalZIndex = args.Value;
            UpdateDecal();
        };

        for (var i = 0; i < EntitySpawnWindow.InitOpts.Length; i++)
            EntityPlacementMode.AddItem(EntitySpawnWindow.InitOpts[i], i);
    }

    public void SelectDecal(string decalId, Decal? sampled = null)
    {
        if (!_prototype.TryIndex<DecalPrototype>(decalId, out var decal))
            return;

        _id = decalId;

        if (sampled != null)
        {
            _decalColor = sampled.Color ?? Color.White;
            _decalRotation = (float) sampled.Angle.Degrees;
            _decalZIndex = sampled.ZIndex;
            _decalCleanable = sampled.Cleanable;
            DecalColorPicker.Color = _decalColor;
            _decalRotationSpin.Value = _decalRotation;
            DecalZIndexSpinBox.Value = _decalZIndex;
            DecalEnableCleanable.Pressed = _decalCleanable;
        }
        else if (_decalAuto)
        {
            _decalCleanable = decal.DefaultCleanable;
            _decalSnap = decal.DefaultSnap;
            DecalEnableCleanable.Pressed = _decalCleanable;
            DecalEnableSnap.Pressed = _decalSnap;
        }

        DecalColorPicker.Color = _decalColor;
        UpdateDecal();
    }

    private void OnDecalColorPicked(Color color)
    {
        _decalColor = color;
        DecalColorPicker.Color = color;
        UpdateDecal();
    }

    private void OnDecalPickerOpenPressed(ButtonEventArgs obj)
    {
        if (_picker == null)
        {
            _picker = new PaletteColorPicker();
            _picker.OpenToLeft();
            _picker.PaletteList.OnItemSelected += args =>
            {
                var color = ((Color?) args.ItemList.GetSelected().First().Metadata)!.Value;
                OnDecalColorPicked(color);
            };
            return;
        }

        if (_picker.IsOpen)
            _picker.Close();
        else
            _picker.Open();
    }

    private void UpdateDecal()
    {
        if (_id is not { } id)
            return;

        DecalSystem.UpdateDecalInfo(id, _decalColor, _decalRotation, _decalSnap, _decalZIndex, _decalCleanable);
    }
}
