using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.KIAS;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._Forge.KIAS;

[GenerateTypedNameReferences]
public sealed partial class KiasWindow : FancyWindow
{
    public event Action? RefreshRequested;
    public event Action<bool>? ControlRequested;
    public event Action<KiasAudioSettingsMessage>? AudioChanged;
    public event Action? QuietRequested;
    private readonly Dictionary<Label, RichTextLabel> _details = new();
    private readonly Dictionary<KiasAudioChannel, OptionButton> _tonePickers = new();

    public KiasWindow()
    {
        RobustXamlLoader.Load(this);
        foreach (var details in new[] { Devices, EventLog, Automation, AtmosDetails, CrewDetails, PowerDetails, DefenceDetails, NavigationDetails, FaultDetails })
        {
            var parent = details.Parent!;
            var index = parent.Children.ToList().IndexOf(details);
            parent.RemoveChild(details);
            details.ClipText = true;
            var wrapped = new RichTextLabel { Margin = new Thickness(4) };
            _details[details] = wrapped;
            var panel = KiasUi.Panel(wrapped);
            panel.Margin = new Thickness(4);
            parent.AddChild(panel);
            panel.SetPositionInParent(index);
        }
        foreach (var channel in Enum.GetValues<KiasAudioChannel>())
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            row.AddChild(new Label { Text = Loc.GetString($"kias-audio-{channel.ToString().ToLowerInvariant()}") });
            var picker = new OptionButton { HorizontalExpand = true };
            foreach (var preset in Enum.GetValues<KiasTonePreset>())
                picker.AddItem(Loc.GetString($"kias-tone-{preset.ToString().ToLowerInvariant()}"), (int) preset);
            picker.OnItemSelected += args =>
            {
                picker.SelectId(args.Id);
                AudioChanged?.Invoke(new KiasAudioSettingsMessage { Channel = channel, Preset = (KiasTonePreset) args.Id });
            };
            var preview = new Button { Text = Loc.GetString("kias-audio-preview") };
            preview.OnPressed += _ => AudioChanged?.Invoke(new KiasAudioSettingsMessage { Channel = channel, Preset = (KiasTonePreset) picker.SelectedId, Preview = true });
            row.AddChild(picker);
            row.AddChild(preview);
            AudioPanel.AddChild(row);
            _tonePickers[channel] = picker;
        }
        RefreshButton.OnPressed += _ => RefreshRequested?.Invoke();
        var pages = new[] { "overview", "atmos", "crew", "power", "defence", "navigation", "faults" };
        for (var i = 0; i < pages.Length; i++)
            Pages.SetTabTitle(i, Loc.GetString($"kias-page-{pages[i]}"));
        RunManual.OnPressed += _ => ControlRequested?.Invoke(false);
        ResetAlert.OnPressed += _ => ControlRequested?.Invoke(true);
        RunQuiet.OnPressed += _ => QuietRequested?.Invoke();
    }

    public void UpdateState(KiasManagementState state)
    {
        AudioPanel.Visible = state.Audio != null;
        if (state.Audio is { } audio)
        {
            _tonePickers[KiasAudioChannel.Notification].SelectId((int) audio.Notification);
            _tonePickers[KiasAudioChannel.Warning].SelectId((int) audio.Warning);
            _tonePickers[KiasAudioChannel.Battle].SelectId((int) audio.Battle);
            _tonePickers[KiasAudioChannel.Emergency].SelectId((int) audio.Emergency);
        }
        var status = Loc.GetString(state.Online ? "kias-online" : "kias-status-offline");
        var counts = Loc.GetString("kias-overview-counts", ("devices", state.Entities), ("crew", state.Crew));
        Status.SetMessage(Robust.Shared.Utility.FormattedMessage.FromUnformatted(status));
        Counts.SetMessage(Robust.Shared.Utility.FormattedMessage.FromUnformatted(counts));
        Status.ToolTip = status;
        Counts.ToolTip = counts;
        Devices.Text = state.Devices;
        EventLog.Text = state.Log;
        AtmosDetails.Text = state.Atmos;
        CrewDetails.Text = state.CrewDetails;
        PowerDetails.Text = state.Power + "\n" + state.Resources;
        DefenceDetails.Text = state.Defence;
        NavigationDetails.Text = state.Navigation;
        FaultDetails.Text = state.Faults;
        Alert.SetMessage(Robust.Shared.Utility.FormattedMessage.FromUnformatted(state.Alert));
        Alert.ToolTip = state.Alert;
        Automation.Text = state.Automation;
        foreach (var details in new[] { Devices, EventLog, Automation, AtmosDetails, CrewDetails, PowerDetails, DefenceDetails, NavigationDetails, FaultDetails })
            details.ToolTip = details.Text;
        foreach (var (label, wrapped) in _details)
            wrapped.SetMessage(Robust.Shared.Utility.FormattedMessage.FromUnformatted(label.Text ?? string.Empty));
        RunManual.Disabled = RunQuiet.Disabled = ResetAlert.Disabled = !state.Online;
    }
}
