using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.KIAS;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.KIAS;

[GenerateTypedNameReferences]
public sealed partial class KiasWindow : FancyWindow
{
    public event Action? RefreshRequested;
    public event Action<string>? MessageChanged;
    public event Action<KiasProtocolMessage>? ProtocolChanged;
    public event Action<bool>? ControlRequested;
    private KiasUiState? _state;

    public KiasWindow()
    {
        RobustXamlLoader.Load(this);
        RefreshButton.OnPressed += _ => RefreshRequested?.Invoke();
        SaveMessage.OnPressed += _ => MessageChanged?.Invoke(MessageInput.Text);
        var pages = new[] { "overview", "atmos", "crew", "power", "defence", "navigation", "faults" };
        for (var i = 0; i < pages.Length; i++)
            Pages.SetTabTitle(i, Loc.GetString($"kias-page-{pages[i]}"));
        foreach (var trigger in Enum.GetValues<KiasTrigger>())
            TriggerPicker.AddItem(Loc.GetString($"kias-trigger-{trigger.ToString().ToLowerInvariant()}"), (int) trigger);
        foreach (var action in Enum.GetValues<KiasActionKind>())
            ActionPicker.AddItem(Loc.GetString($"kias-action-{action.ToString().ToLowerInvariant()}"), (int) action);
        DispositionPicker.AddItem(Loc.GetString("kias-protocol-any-contact"), 0);
        foreach (var disposition in Enum.GetValues<KiasContactDisposition>())
            DispositionPicker.AddItem(Loc.GetString($"kias-contact-{disposition.ToString().ToLowerInvariant()}"), (int) disposition + 1);
        DispositionPicker.OnItemSelected += args => DispositionPicker.SelectId(args.Id);
        TriggerPicker.OnItemSelected += args => TriggerPicker.SelectId(args.Id);
        ActionPicker.OnItemSelected += args => ActionPicker.SelectId(args.Id);
        TargetPicker.OnItemSelected += args => TargetPicker.SelectId(args.Id);
        ProtocolPicker.OnItemSelected += args => { ProtocolPicker.SelectId(args.Id); PopulateProtocol(args.Id); };
        SaveProtocol.OnPressed += _ => SubmitProtocol(false);
        RemoveProtocol.OnPressed += _ => SubmitProtocol(true);
        RunManual.OnPressed += _ => ControlRequested?.Invoke(false);
        ResetAlert.OnPressed += _ => ControlRequested?.Invoke(true);
    }

    public void UpdateState(KiasUiState state)
    {
        Status.Text = Loc.GetString(state.Online ? "kias-online" : "kias-status-offline");
        Counts.Text = $"Entities: {state.Entities} // Crew: {state.Crew}";
        Devices.Text = state.Devices;
        EventLog.Text = state.Log;
        AtmosDetails.Text = state.Atmos;
        CrewDetails.Text = state.CrewDetails;
        PowerDetails.Text = state.Power;
        DefenceDetails.Text = state.Defence;
        NavigationDetails.Text = state.Navigation;
        FaultDetails.Text = state.Faults;
        Alert.Text = state.Alert;
        CoveragePanel.Visible = state.Coverage.Count > 0;
        CoverageMap.Cells = state.Coverage;
        ProtocolEditor.Visible = state.ProtocolsAvailable;
        NetEntity? previousTarget = null;
        var previousIndex = TargetPicker.SelectedId - 1;
        if (_state != null && previousIndex >= 0 && previousIndex < _state.Targets.Count)
            previousTarget = _state.Targets[previousIndex].Entity;
        TargetPicker.Clear();
        TargetPicker.AddItem(Loc.GetString("kias-protocol-whole-ship"), 0);
        for (var i = 0; i < state.Targets.Count; i++)
            TargetPicker.AddItem(state.Targets[i].Name, i + 1);
        TargetPicker.SelectId(state.Targets.FindIndex(entry => entry.Entity == previousTarget) + 1);
        if (_state == null || _state.ProtocolRevision != state.ProtocolRevision)
        {
            var selected = Math.Min(ProtocolPicker.SelectedId, state.Protocols.Count);
            _state = state;
            ProtocolPicker.Clear();
            for (var i = 0; i < state.Protocols.Count; i++)
                ProtocolPicker.AddItem($"{i + 1}. {Loc.GetString($"kias-trigger-{state.Protocols[i].Trigger.ToString().ToLowerInvariant()}")}", i);
            ProtocolPicker.AddItem(Loc.GetString("kias-protocol-new"), state.Protocols.Count);
            ProtocolPicker.SelectId(selected);
            PopulateProtocol(selected);
        }
        else
            _state = state;
        MessageEditor.Visible = state.ServiceTool;
        if (!MessageInput.HasKeyboardFocus())
            MessageInput.Text = state.Message;
    }

    private void PopulateProtocol(int index)
    {
        if (_state == null)
            return;
        var protocol = index < _state.Protocols.Count ? _state.Protocols[index] : new KiasProtocolView { Enabled = true, Value = true, Cooldown = 10 };
        TriggerPicker.SelectId((int) protocol.Trigger);
        DispositionPicker.SelectId(protocol.Disposition is { } disposition ? (int) disposition + 1 : 0);
        MinimumInput.Text = protocol.MinimumValue.ToString();
        CrewUnavailable.Pressed = protocol.RequireCrewUnavailable;
        ActionPicker.SelectId((int) protocol.Action);
        var target = _state.Targets.FindIndex(entry => entry.Entity == protocol.Target);
        TargetPicker.SelectId(target + 1);
        GroupInput.Text = protocol.Group;
        PortInput.Text = protocol.Port;
        ProtocolMessage.Text = protocol.Message;
        CooldownInput.Text = protocol.Cooldown.ToString();
        ProtocolEnabled.Pressed = protocol.Enabled;
        ActionValue.Pressed = protocol.Value;
    }

    private void SubmitProtocol(bool delete)
    {
        if (_state == null || !float.TryParse(CooldownInput.Text, out var cooldown) || !float.TryParse(MinimumInput.Text, out var minimum))
            return;
        var selected = TargetPicker.SelectedId - 1;
        ProtocolChanged?.Invoke(new KiasProtocolMessage { Index = ProtocolPicker.SelectedId, Delete = delete,
            Trigger = (KiasTrigger) TriggerPicker.SelectedId, Action = (KiasActionKind) ActionPicker.SelectedId,
            Disposition = DispositionPicker.SelectedId == 0 ? null : (KiasContactDisposition) (DispositionPicker.SelectedId - 1),
            MinimumValue = minimum, RequireCrewUnavailable = CrewUnavailable.Pressed,
            Target = selected >= 0 && selected < _state.Targets.Count ? _state.Targets[selected].Entity : null,
            Group = GroupInput.Text, Port = PortInput.Text, Message = ProtocolMessage.Text, Value = ActionValue.Pressed,
            Enabled = ProtocolEnabled.Pressed, Cooldown = cooldown });
    }
}
