using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.KIAS;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._Forge.KIAS;

[GenerateTypedNameReferences]
public sealed partial class KiasWindow : FancyWindow
{
    public event Action? RefreshRequested;
    public event Action<bool>? ControlRequested;
    public event Action<KiasAudioSettingsMessage>? AudioChanged;
    public event Action? QuietRequested;
    private readonly Dictionary<KiasAudioChannel, OptionButton> _tonePickers = new();

    public KiasWindow()
    {
        RobustXamlLoader.Load(this);
        foreach (var channel in Enum.GetValues<KiasAudioChannel>())
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            row.AddChild(new Label { Text = Loc.GetString($"kias-audio-{channel.ToString().ToLowerInvariant()}") });
            var picker = new OptionButton();
            foreach (var preset in Enum.GetValues<KiasTonePreset>())
                picker.AddItem(Loc.GetString($"kias-tone-{preset.ToString().ToLowerInvariant()}"), (int) preset);
            picker.OnItemSelected += args =>
            {
                picker.SelectId(args.Id);
                AudioChanged?.Invoke(new KiasAudioSettingsMessage { Channel = channel, Preset = (KiasTonePreset) args.Id });
            };
            var preview = new Button { Text = Loc.GetString("kias-audio-preview") };
            preview.OnPressed += _ => AudioChanged?.Invoke(new KiasAudioSettingsMessage { Channel = channel, Preset = (KiasTonePreset) picker.SelectedId, Preview = true });
            row.AddChild(picker);
            row.AddChild(preview);
            AudioPanel.AddChild(row);
            _tonePickers[channel] = picker;
        }
        RefreshButton.OnPressed += _ => RefreshRequested?.Invoke();
        var pages = new[] { "overview", "atmos", "crew", "power", "defence", "navigation", "faults" };
        for (var i = 0; i < pages.Length; i++)
            Pages.SetTabTitle(i, Loc.GetString($"kias-page-{pages[i]}"));
        RunManual.OnPressed += _ => ControlRequested?.Invoke(false);
        ResetAlert.OnPressed += _ => ControlRequested?.Invoke(true);
        RunQuiet.OnPressed += _ => QuietRequested?.Invoke();
    }

    public void UpdateState(KiasManagementState state)
    {
        AudioPanel.Visible = state.Audio != null;
        if (state.Audio is { } audio)
        {
            _tonePickers[KiasAudioChannel.Notification].SelectId((int) audio.Notification);
            _tonePickers[KiasAudioChannel.Warning].SelectId((int) audio.Warning);
            _tonePickers[KiasAudioChannel.Battle].SelectId((int) audio.Battle);
            _tonePickers[KiasAudioChannel.Emergency].SelectId((int) audio.Emergency);
        }
        Status.Text = Loc.GetString(state.Online ? "kias-online" : "kias-status-offline");
        Counts.Text = $"Entities: {state.Entities} // Crew: {state.Crew}";
        Devices.Text = state.Devices;
        EventLog.Text = state.Log;
        AtmosDetails.Text = state.Atmos;
        CrewDetails.Text = state.CrewDetails;
        PowerDetails.Text = state.Power + "\n" + state.Resources;
        DefenceDetails.Text = state.Defence;
        NavigationDetails.Text = state.Navigation;
        FaultDetails.Text = state.Faults;
        Alert.Text = state.Alert;
        Automation.Text = state.Automation;
        RunManual.Disabled = RunQuiet.Disabled = ResetAlert.Disabled = !state.Online;
    }
}
