using System.Linq;
using System.Numerics;
using Content.Client.Parallax; // Frontier: Parallax control for the background
using Content.Client.Research;
using Content.Client.UserInterface.Controls;
using Content.Shared._Goobstation.Research;
using Content.Shared.Access.Systems;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Goobstation.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyResearchConsoleMenu : FancyWindow
{
    public Action<string>? OnTechnologyCardPressed;
    public Action? OnServerButtonPressed;

    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private IPlayerManager _player = default!;

    private readonly ResearchSystem _research;
    private readonly SpriteSystem _sprite;
    private readonly AccessReaderSystem _accessReader;

    /// <summary>
    /// Console entity
    /// </summary>
    public EntityUid Entity;

    /// <summary>
    /// Currently selected tech
    /// Exists for better UI refreshing
    /// </summary>
    public ProtoId<TechnologyPrototype>? CurrentTech;

    /// <summary>
    /// All technologies and their availability
    /// </summary>
    public Dictionary<string, ResearchAvailability> List = new();

    public Dictionary<string, byte> Progress = new();

    /// <summary>
    /// Cached research points
    /// </summary>
    public int Points = 0;

    /// <summary>
    /// Is tech currently being dragged
    /// </summary>
    private bool _draggin;

    /// <summary>
    /// Global position that all tech relates to.
    /// For dragging mostly
    /// </summary>
    private Vector2 _position = DefaultPosition;

    /// <summary>
    /// Horizontal spacing between technologies on the same tree row (grid cells).
    /// </summary>
    private const float CompactCellStepX = 1.15f;

    /// <summary>
    /// Vertical spacing between prerequisite depth rows (grid cells).
    /// </summary>
    private const float CompactDepthStepY = 2f;

    /// <summary>
    /// Cached compact layout positions per discipline and technology.
    /// </summary>
    private readonly Dictionary<string, Dictionary<string, Vector2>> _compactLayouts = new();

    /// <summary>
    /// Currently selected research discipline tab.
    /// </summary>
    private string? _selectedDiscipline;

    /// <summary>
    /// Cached viewport offset for each discipline tab.
    /// </summary>
    private readonly Dictionary<string, Vector2> _disciplinePositions = new();

    /// <summary>
    /// Tracks visible technology controls for selection and navigation.
    /// </summary>
    private readonly Dictionary<string, FancyResearchConsoleItem> _visibleTechnologyItems = new();

    /// <summary>
    /// Temporary ghost shown when target research is on another tab.
    /// </summary>
    private FancyResearchConsoleItem? _crossDisciplinePreviewItem;

    /// <summary>
    /// Tech focused in the tree viewport.
    /// </summary>
    private string? _focusedTech;

    /// <summary>
    /// Breadcrumb stack of technologies navigated away from (root → parent).
    /// </summary>
    private readonly List<string> _navigationChain = new();

    /// <summary>
    /// Captures the initial position to use with recenter button
    /// </summary>
    private Vector2 _initialViewPosition;

    /// <summary>
    /// Recenters the tree once data is loaded and the viewport has a real size.
    /// </summary>
    private bool _pendingRecenter = true;

    /// <summary>
    /// Frontier: the distance between elements on the grid.
    /// </summary>
    private const int GridSize = 90;

    /// <summary>
    /// Frontier: technology cards size.
    /// </summary>
    private const int CardSize = 64;

    /// <summary>
    /// Frontier: the distance between elements on the grid.
    /// </summary>
    private static readonly Vector2i DefaultPosition = Vector2i.Zero; //Frontier: 45,250 < 0,0

    private ParallaxControl _parallaxControl; // Frontier: Parallax control for the background

    private float _verticalScrollSpeed = 50; // Frontier: Allow mouse scroll

    public FancyResearchConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _research = _entity.System<ResearchSystem>();
        _sprite = _entity.System<SpriteSystem>();
        _accessReader = _entity.System<AccessReaderSystem>();

        // Frontier: Initialize parallax background
        _parallaxControl = new ParallaxControl
        {
            ParallaxPrototype = "Default",
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        // Add the parallax control to the ResearchesContainer at the beginning (bottom layer)
        ResearchesContainer.AddChild(_parallaxControl);

        // Set the proper rendering order by adjusting positions in the parent's child list
        // Controls with a higher position value are drawn on top (foreground)
        // Make sure the parallax is at the bottom of the z-order (drawn first)
        _parallaxControl.SetPositionInParent(0);

        // The drag container should be in the middle
        DragContainer.SetPositionInParent(1);

        // The recenter button should be at the top of the z-order (drawn last)
        RecenterButton.SetPositionInParent(2);

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        DragContainer.OnKeyBindDown += OnKeybindDown;
        DragContainer.OnKeyBindUp += OnKeybindUp;
        RecenterButton.OnPressed += _ => Recenter();
        ResearchesContainer.OnResized += OnResearchViewportResized;
    }

    public void SetEntity(EntityUid entity)
        => Entity = entity;

    public void UpdatePanels(Dictionary<string, ResearchAvailability> dict, Dictionary<string, byte> progress)
    {
        List = dict;
        Progress = progress;
        var supportedDisciplines = GetSupportedDisciplineIds();

        if (dict.Count > 0)
            _pendingRecenter = true;

        EnsureSelectedDiscipline(supportedDisciplines);
        BuildDisciplineTabs(supportedDisciplines);
        RefreshTechnologyGrid();
        RefreshCurrentInfoPanel();
    }

    private void RefreshTechnologyGrid()
    {
        DragContainer.RemoveAllChildren();
        _visibleTechnologyItems.Clear();
        _crossDisciplinePreviewItem = null;

        var supportedDisciplines = GetSupportedDisciplineIds();
        RebuildCompactLayouts(supportedDisciplines);

        foreach (var tech in List)
        {
            var proto = _prototype.Index<TechnologyPrototype>(tech.Key);

            if (!IsTechnologyVisibleInCurrentTab(proto))
                continue;

            var unlockProgress = Progress.GetValueOrDefault(tech.Key, (byte) 0);
            var control = new FancyResearchConsoleItem(proto, _sprite, tech.Value, unlockProgress);
            DragContainer.AddChild(control);
            _visibleTechnologyItems[proto.ID] = control;

            // Set position for all tech, relating to _position
            var uiPosition = _position + GetTechnologyGridPosition(proto) * GridSize;
            LayoutContainer.SetPosition(control, uiPosition);
            control.SelectAction += SelectTech;
        }

        AddCrossDisciplinePreviewGhost();
        UpdateSelectedTechVisuals();

        if (_pendingRecenter
            && _visibleTechnologyItems.Count > 0
            && ResearchesContainer.Size.X > 1
            && ResearchesContainer.Size.Y > 1)
        {
            Recenter();
        }
    }

    public void UpdateInformationPanel(int points)
    {
        Points = points;

        var amountMsg = new FormattedMessage();
        amountMsg.AddMarkupOrThrow(Loc.GetString("research-console-menu-research-points-text",
            ("points", points)));
        ResearchAmountLabel.SetMessage(amountMsg);

        if (!_entity.TryGetComponent(Entity, out TechnologyDatabaseComponent? database))
            return;

        var previousDiscipline = _selectedDiscipline;
        var supportedDisciplines = GetSupportedDisciplineIds();
        EnsureSelectedDiscipline(supportedDisciplines);
        BuildDisciplineTabs(supportedDisciplines);

        if (previousDiscipline != _selectedDiscipline)
            RefreshTechnologyGrid();

        TierDisplayContainer.RemoveAllChildren();
        foreach (var disciplineId in database.SupportedDisciplines)
        {
            var discipline = _prototype.Index<TechDisciplinePrototype>(disciplineId);
            var tier = _research.GetTierCompletionPercentage(database, discipline, _prototype);

            // i'm building the small-ass control here to spare me some mild annoyance in making a new file
            var texture = new TextureRect
            {
                TextureScale = new Vector2(2, 2),
                VerticalAlignment = VAlignment.Center
            };
            var label = new RichTextLabel();
            texture.Texture = _sprite.Frame0(discipline.Icon);
            label.SetMessage(Loc.GetString("research-console-tier-percentage", ("perc", tier)));

            var control = new BoxContainer
            {
                Children =
                {
                    texture,
                    label,
                    new Control
                    {
                        MinWidth = 10
                    }
                }
            };
            TierDisplayContainer.AddChild(control);
        }
    }

    #region Drag handle
    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        if (!_draggin)
            return;

        // Frontier: bound motion to a box
        var originalPosition = _position;
        _position += args.Relative;
        CacheCurrentDisciplinePosition();

        var diff = _position - originalPosition;
        // End Frontier: bound motion to a box

        // Move all tech
        foreach (var child in DragContainer.Children)
        {
            LayoutContainer.SetPosition(child, child.Position + diff); // Frontier: args.Relative<diff
        }
    }

    /// <summary>
    /// Raised when LMB is pressed at <see cref="DragContainer"/>
    /// </summary>
    private void OnKeybindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _draggin = true;
    }

    /// <summary>
    /// Raised when LMB is unpressed at <see cref="DragContainer"/>
    /// </summary>
    private void OnKeybindUp(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _draggin = false;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        => _draggin ? DragMode.None : base.GetDragModeFor(relativeMousePos);
    #endregion

    /// <summary>
    /// Selects a tech prototype and opens info panel
    /// </summary>
    /// <param name="proto">Tech proto</param>
    /// <param name="availability">Tech availability</param>
    public void SelectTech(TechnologyPrototype proto, ResearchAvailability availability)
    {
        if (_navigationChain.Contains(proto.ID))
        {
            ReturnToNavigationPoint(proto.ID);
            return;
        }

        CurrentTech = proto.ID;
        _focusedTech = proto.ID;

        if (_navigationChain.Count > 0)
            _navigationChain.Clear();

        ShowTechnologyInfo(proto, availability);
        UpdateSelectedTechVisuals();
    }

    private void ShowTechnologyInfo(TechnologyPrototype proto, ResearchAvailability availability)
    {
        InfoContainer.RemoveAllChildren();
        if (!_player.LocalEntity.HasValue)
            return;

        TechnologyPrototype? returnToTech = null;
        if (TryGetImmediateNavigationParent(out var parentId)
            && _prototype.TryIndex(parentId, out TechnologyPrototype? parentProto)
            && parentProto.ID != proto.ID)
        {
            returnToTech = parentProto;
        }

        var control = new FancyTechnologyInfoPanel(
            proto,
            _accessReader.IsAllowed(_player.LocalEntity.Value, Entity),
            availability,
            _sprite,
            returnToTech,
            returnToTech != null ? ReturnToPreviewTarget : null,
            BuildNavigationBreadcrumb());
        control.BuyAction += args => OnTechnologyCardPressed?.Invoke(args.ID);
        control.NavigateToTechnologyAction += NavigateToTechnology;
        InfoContainer.AddChild(control);
    }

    /// <summary>
    /// Resets the view exactly to the initial position when the UI was first opened
    /// </summary>
    public void Recenter()
    {
        if (_selectedDiscipline == null)
            return;

        var defaultPosition = GetDefaultDisciplinePosition(_selectedDiscipline);
        var diff = defaultPosition - _position;

        _position = defaultPosition;
        _pendingRecenter = false;
        CacheCurrentDisciplinePosition();

        foreach (var child in DragContainer.Children)
            LayoutContainer.SetPosition(child, child.Position + diff);
    }

    public override void Close()
    {
        base.Close();

        DragContainer.RemoveAllChildren();
        DisciplineTabsContainer.RemoveAllChildren();
        InfoContainer.RemoveAllChildren();
        _visibleTechnologyItems.Clear();
        _crossDisciplinePreviewItem = null;
        _pendingRecenter = true;
        _selectedDiscipline = null;
        _disciplinePositions.Clear();
        _focusedTech = null;
        _navigationChain.Clear();
        Progress.Clear();
    }

    private List<string> GetSupportedDisciplineIds()
    {
        if (!_entity.TryGetComponent(Entity, out TechnologyDatabaseComponent? database))
            return new List<string>();

        return database.SupportedDisciplines
            .Where(disciplineId => _prototype.HasIndex<TechDisciplinePrototype>(disciplineId))
            .ToList();
    }

    private void EnsureSelectedDiscipline(IReadOnlyList<string> supportedDisciplines)
    {
        if (supportedDisciplines.Count == 0)
        {
            _selectedDiscipline = null;
            _position = DefaultPosition;
            return;
        }

        if (IsValidDisciplineTab(_selectedDiscipline, supportedDisciplines))
        {
            _position = GetDisciplinePosition(_selectedDiscipline!);
            return;
        }

        _selectedDiscipline = supportedDisciplines[0];
        _position = DefaultPosition;
    }

    private static bool IsValidDisciplineTab(string? tabId, IReadOnlyList<string> supportedDisciplines)
        => tabId != null && supportedDisciplines.Contains(tabId);

    private bool IsTechnologyVisibleInCurrentTab(TechnologyPrototype proto)
        => _selectedDiscipline != null && proto.Discipline == _selectedDiscipline;

    private void BuildDisciplineTabs(IReadOnlyList<string> supportedDisciplines)
    {
        DisciplineTabsContainer.RemoveAllChildren();

        if (supportedDisciplines.Count == 0)
            return;

        var group = new ButtonGroup();

        foreach (var disciplineId in supportedDisciplines)
        {
            var discipline = _prototype.Index<TechDisciplinePrototype>(disciplineId);
            var button = new DisciplineButton(discipline)
            {
                ToggleMode = true,
                Group = group,
                Pressed = disciplineId == _selectedDiscipline,
                Text = discipline.UiName,
                ToolTip = Loc.GetString(discipline.Name),
                MinHeight = 32,
                MinWidth = 80,
            };

            button.OnPressed += _ => SelectDiscipline(disciplineId);
            DisciplineTabsContainer.AddChild(button);
        }
    }

    private void SelectDiscipline(string disciplineId)
    {
        if (_selectedDiscipline == disciplineId)
            return;

        _selectedDiscipline = disciplineId;
        _navigationChain.Clear();
        _disciplinePositions.Remove(disciplineId);
        _pendingRecenter = true;
        RefreshTechnologyGrid();
    }

    private Vector2 GetDisciplinePosition(string disciplineId)
    {
        if (_disciplinePositions.TryGetValue(disciplineId, out var position))
            return position;

        var defaultPosition = GetDefaultDisciplinePosition(disciplineId);
        _disciplinePositions[disciplineId] = defaultPosition;
        return defaultPosition;
    }

    private void CacheCurrentDisciplinePosition()
    {
        if (_selectedDiscipline == null)
            return;

        _disciplinePositions[_selectedDiscipline] = _position;
    }

    private Vector2 GetDefaultDisciplinePosition(string disciplineId)
    {
        var supportedDisciplines = GetSupportedDisciplineIds();
        var technologies = List.Keys
            .Select(id => _prototype.Index<TechnologyPrototype>(id))
            .Where(proto => proto.Discipline == disciplineId)
            .ToList();

        if (technologies.Count == 0)
            return DefaultPosition;

        var min = new Vector2(float.MaxValue, float.MaxValue);
        var max = new Vector2(float.MinValue, float.MinValue);

        foreach (var technology in technologies)
        {
            var gridPosition = GetTechnologyGridPosition(technology);
            var topLeft = gridPosition * GridSize;
            var bottomRight = topLeft + new Vector2(CardSize, CardSize);
            min = Vector2.Min(min, topLeft);
            max = Vector2.Max(max, bottomRight);
        }

        var treeCenter = (min + max) / 2f;
        var viewportSize = GetViewportSize();
        var viewportCenter = viewportSize / 2f;

        return viewportCenter - treeCenter;
    }

    private void RebuildCompactLayouts(IReadOnlyList<string> supportedDisciplines)
    {
        _compactLayouts.Clear();

        foreach (var disciplineId in supportedDisciplines)
            _compactLayouts[disciplineId] = BuildCompactLayout(disciplineId);
    }

    /// <summary>
    /// Builds a tight grid from prerequisite depth instead of raw prototype coordinates.
    /// </summary>
    private Dictionary<string, Vector2> BuildCompactLayout(string disciplineId)
    {
        var technologies = List.Keys
            .Select(id => _prototype.Index<TechnologyPrototype>(id))
            .Where(proto => proto.Discipline == disciplineId && !proto.Hidden)
            .ToList();

        if (technologies.Count == 0)
            return new Dictionary<string, Vector2>();

        var techIds = technologies.Select(tech => tech.ID).ToHashSet();
        var depths = technologies.ToDictionary(tech => tech.ID, _ => 0);

        var changed = true;
        while (changed)
        {
            changed = false;

            foreach (var tech in technologies)
            {
                var prereqDepths = tech.TechnologyPrerequisites
                    .Where(prereq => techIds.Contains(prereq))
                    .Select(prereq => depths[prereq] + 1);

                var newDepth = prereqDepths.Any() ? prereqDepths.Max() : 0;
                if (newDepth <= depths[tech.ID])
                    continue;

                depths[tech.ID] = newDepth;
                changed = true;
            }
        }

        var layout = new Dictionary<string, Vector2>();

        foreach (var depthGroup in technologies.GroupBy(tech => depths[tech.ID]).OrderBy(group => group.Key))
        {
            var column = 0f;

            foreach (var tech in depthGroup
                         .OrderBy(tech => tech.Position.Y)
                         .ThenBy(tech => tech.Position.X)
                         .ThenBy(tech => tech.ID))
            {
                layout[tech.ID] = new Vector2(column, depthGroup.Key * CompactDepthStepY);
                column += CompactCellStepX;
            }
        }

        return layout;
    }

    private Vector2 GetTechnologyGridPosition(TechnologyPrototype proto)
    {
        if (_compactLayouts.TryGetValue(proto.Discipline, out var disciplineLayout)
            && disciplineLayout.TryGetValue(proto.ID, out var local))
        {
            return local;
        }

        return (Vector2) proto.Position;
    }

    private Vector2 GetViewportSize()
    {
        var width = MathF.Max(ResearchesContainer.Size.X, 700f);
        var height = MathF.Max(ResearchesContainer.Size.Y, 550f);
        return new Vector2(width, height);
    }

    private void NavigateToTechnology(TechnologyPrototype technology)
    {
        if (_navigationChain.Contains(technology.ID))
        {
            ReturnToNavigationPoint(technology.ID);
            return;
        }

        TechnologyPrototype? sourceTechnology = null;
        if (CurrentTech != null && _prototype.TryIndex(CurrentTech, out TechnologyPrototype? source))
            sourceTechnology = source;

        if (sourceTechnology != null
            && sourceTechnology.ID != technology.ID
            && (_navigationChain.Count == 0 || _navigationChain[^1] != sourceTechnology.ID))
        {
            _navigationChain.Add(sourceTechnology.ID);
        }

        _focusedTech = technology.ID;
        CurrentTech = technology.ID;

        _selectedDiscipline = technology.Discipline;

        _position = sourceTechnology != null && sourceTechnology.Discipline == technology.Discipline
            ? GetNavigationPosition(sourceTechnology, technology)
            : GetCenteredPositionForTechnology(technology);

        CacheCurrentDisciplinePosition();
        BuildDisciplineTabs(GetSupportedDisciplineIds());
        RefreshTechnologyGrid();

        if (!List.TryGetValue(technology.ID, out var availability))
            return;

        ShowTechnologyInfo(technology, availability);

        if (availability == ResearchAvailability.Researched)
            ReturnToPreviewTarget();
    }

    private Vector2 GetCenteredPositionForTechnology(TechnologyPrototype technology)
    {
        var viewportCenter = GetViewportSize() / 2f;
        var gridPosition = GetTechnologyGridPosition(technology);
        var technologyCenter = gridPosition * GridSize + new Vector2(CardSize / 2f, CardSize / 2f);
        return viewportCenter - technologyCenter;
    }

    private void OnResearchViewportResized()
    {
        if (_selectedDiscipline == null || _visibleTechnologyItems.Count == 0)
            return;

        _pendingRecenter = true;
        Recenter();
    }

    private void RefreshCurrentInfoPanel()
    {
        if (_navigationChain.Count > 0
            && _focusedTech != null
            && List.TryGetValue(_focusedTech, out var focusedAvailability)
            && _prototype.TryIndex(_focusedTech, out TechnologyPrototype? focusedProto))
        {
            ShowTechnologyInfo(focusedProto, focusedAvailability);

            if (focusedAvailability == ResearchAvailability.Researched)
                ReturnToPreviewTarget();

            return;
        }

        if (CurrentTech == null || !List.TryGetValue(CurrentTech, out var availability))
            return;

        if (!_prototype.TryIndex(CurrentTech, out TechnologyPrototype? proto))
            return;

        ShowTechnologyInfo(proto, availability);
    }

    private void AddCrossDisciplinePreviewGhost()
    {
        if (_navigationChain.Count == 0 || _focusedTech == null)
            return;

        if (!TryGetImmediateNavigationParent(out var immediateParentId))
            return;

        if (_visibleTechnologyItems.ContainsKey(immediateParentId))
            return;

        if (!_visibleTechnologyItems.TryGetValue(_focusedTech, out var focusedItem))
            return;

        if (!_prototype.TryIndex(immediateParentId, out TechnologyPrototype? previewProto))
            return;

        var availability = List.TryGetValue(previewProto.ID, out var previewAvailability)
            ? previewAvailability
            : ResearchAvailability.Unavailable;

        var previewProgress = List.TryGetValue(previewProto.ID, out _)
            ? Progress.GetValueOrDefault(previewProto.ID, (byte) 0)
            : (byte) 0;
        var previewItem = new FancyResearchConsoleItem(previewProto, _sprite, availability, previewProgress)
        {
            IsGhostPreview = true,
            IsPreviewTarget = true,
            OverrideAction = (_, _) => ReturnToNavigationPoint(immediateParentId),
        };
        DragContainer.AddChild(previewItem);
        _crossDisciplinePreviewItem = previewItem;

        var previewPosition = focusedItem.Position + new Vector2(0f, -GridSize);
        LayoutContainer.SetPosition(previewItem, previewPosition);
    }

    private bool TryGetImmediateNavigationParent(out string parentId)
    {
        if (_navigationChain.Count > 0)
        {
            parentId = _navigationChain[^1];
            return true;
        }

        parentId = string.Empty;
        return false;
    }

    private string? BuildNavigationBreadcrumb()
    {
        if (_navigationChain.Count == 0)
            return null;

        var parts = _navigationChain
            .Select(id => Loc.GetString(_prototype.Index<TechnologyPrototype>(id).Name))
            .ToList();

        if (parts.Count > 5)
        {
            return string.Join("\n→ ",
                parts.Take(2)
                    .Concat(new[] { "…" })
                    .Concat(parts.TakeLast(2)));
        }

        return string.Join("\n→ ", parts);
    }

    private void ReturnToPreviewTarget()
    {
        if (!TryGetImmediateNavigationParent(out var parentId))
            return;

        ReturnToNavigationPoint(parentId);
    }

    private void ReturnToNavigationPoint(string techId)
    {
        var index = _navigationChain.IndexOf(techId);
        if (index < 0)
            return;

        _navigationChain.RemoveRange(index, _navigationChain.Count - index);

        if (!_prototype.TryIndex(techId, out TechnologyPrototype? targetProto))
            return;

        if (!List.TryGetValue(targetProto.ID, out var availability))
            return;

        CurrentTech = targetProto.ID;
        _focusedTech = targetProto.ID;

        _selectedDiscipline = targetProto.Discipline;

        _position = GetCenteredPositionForTechnology(targetProto);
        CacheCurrentDisciplinePosition();
        BuildDisciplineTabs(GetSupportedDisciplineIds());
        RefreshTechnologyGrid();
        ShowTechnologyInfo(targetProto, availability);
    }

    private Vector2 GetNavigationPosition(TechnologyPrototype source, TechnologyPrototype prerequisite)
    {
        var viewportCenter = GetViewportSize() / 2f;
        var sourceCenter = GetTechnologyGridPosition(source) * GridSize
            + new Vector2(CardSize / 2f, CardSize / 2f);
        var prerequisiteCenter = GetTechnologyGridPosition(prerequisite) * GridSize
            + new Vector2(CardSize / 2f, CardSize / 2f);
        var navigationCenter = Vector2.Lerp(prerequisiteCenter, sourceCenter, 0.45f);
        return viewportCenter - navigationCenter;
    }

    private void UpdateSelectedTechVisuals()
    {
        foreach (var (techId, item) in _visibleTechnologyItems)
        {
            item.IsSelected = techId == _focusedTech;
            item.IsPreviewTarget = _navigationChain.Contains(techId);
            item.OverrideAction = null;
        }

        foreach (var chainId in _navigationChain)
        {
            if (!_visibleTechnologyItems.TryGetValue(chainId, out var chainItem))
                continue;

            var chainTechId = chainId;
            chainItem.OverrideAction = (_, _) => ReturnToNavigationPoint(chainTechId);
        }
    }

    private sealed partial class DisciplineButton(TechDisciplinePrototype proto) : Button
    {
        public TechDisciplinePrototype Proto = proto;
    }
}
