// SPDX-FileCopyrightText: 2025 starch
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Goobstation.Research;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Goobstation.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyResearchConsoleItem : LayoutContainer
{
    [Dependency] private IPrototypeManager _prototype = default!;

    public TechnologyPrototype Prototype;
    public Action<TechnologyPrototype, ResearchAvailability>? SelectAction;
    public Action<TechnologyPrototype, ResearchAvailability>? OverrideAction;
    public ResearchAvailability Availability;
    public byte UnlockProgress;

    public bool IsGhostPreview;

    private bool _isPreviewTarget;
    public bool IsPreviewTarget
    {
        get => _isPreviewTarget;
        set
        {
            if (_isPreviewTarget == value)
                return;

            _isPreviewTarget = value;
            UpdateVisuals();
        }
    }

    private bool _isSelected;
    public bool IsSelected
    {
        get => _isSelected;
        set
        {
            if (_isSelected == value)
                return;

            _isSelected = value;
            UpdateVisuals();
        }
    }

    private Color _backgroundColor;
    private Color _hoveredColor;
    private Color _selectedColor;
    private Color _previewColor;
    private Color _borderColor;
    private float _borderThickness = 2.5f;

    public FancyResearchConsoleItem(
        TechnologyPrototype proto,
        SpriteSystem sprite,
        ResearchAvailability availability,
        byte unlockProgress)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Availability = availability;
        UnlockProgress = unlockProgress;
        Prototype = proto;

        var discipline = _prototype.Index<TechDisciplinePrototype>(proto.Discipline);
        var disciplineColor = discipline.Color;
        var scheme = ResearchColorScheme.GetTechItemColors(availability);
        var blend = ResearchColorScheme.GetBackgroundInterpolationFactor(availability);

        _backgroundColor = Color.InterpolateBetween(disciplineColor, scheme.Background, blend);
        _hoveredColor = Color.InterpolateBetween(_backgroundColor, scheme.Hover, 0.35f);
        _selectedColor = Color.InterpolateBetween(_backgroundColor, scheme.Selected, 0.55f);
        _previewColor = new Color(_backgroundColor.R, _backgroundColor.G, _backgroundColor.B, 0.35f);
        _borderColor = scheme.Border;

        if (availability == ResearchAvailability.Unavailable)
        {
            _backgroundColor = Color.InterpolateBetween(_backgroundColor, Color.Black, 0.6f);
            _borderColor = Color.InterpolateBetween(_borderColor, Color.DarkGray, 0.5f);
        }
        else if (availability == ResearchAvailability.Available)
        {
            _borderThickness = 3.5f;
            _backgroundColor = Color.InterpolateBetween(_backgroundColor, scheme.Background, 0.15f);
        }

        if (proto.EntityIcon.HasValue)
            ResearchDisplay.SetPrototype(proto.EntityIcon.Value);
        else
            ResearchDisplay.SetPrototype(null);

        Button.OnPressed += Selected;
        Button.OnDrawModeChanged += UpdateVisuals;

        var roundedStyle = new RoundedStyleBoxFlat
        {
            BorderColor = _borderColor,
            BorderThickness = new Thickness(_borderThickness),
            CornerRadius = 8f,
        };

        Panel.PanelOverride = roundedStyle;

        LockOverlay.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(0f, 0f, 0f, availability == ResearchAvailability.Unavailable ? 0.55f : 0f),
        };

        StatusBar.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(0f, 0f, 0f, 0.72f),
        };

        ApplyProgressLabel();
        UpdateVisuals();
    }

    private void ApplyProgressLabel()
    {
        switch (Availability)
        {
            case ResearchAvailability.Researched:
                ProgressLabel.SetMessage(Loc.GetString("research-console-tech-researched"));
                StatusBar.Visible = true;
                break;

            case ResearchAvailability.Available:
                StatusBar.Visible = false;
                break;

            case ResearchAvailability.PrereqsMet:
                ProgressLabel.SetMessage(Loc.GetString(
                    "research-console-tech-progress-rp",
                    ("percent", UnlockProgress)));
                StatusBar.Visible = true;
                break;

            case ResearchAvailability.Unavailable:
                ProgressLabel.SetMessage(Loc.GetString(
                    "research-console-tech-progress-prereqs",
                    ("percent", UnlockProgress)));
                StatusBar.Visible = true;
                break;

            default:
                StatusBar.Visible = false;
                break;
        }
    }

    public void SetInteractive(bool interactive)
    {
        Button.Disabled = !interactive;
    }

    private void UpdateVisuals()
    {
        if (Panel.PanelOverride is not RoundedStyleBoxFlat panel)
            return;

        if (IsSelected)
            panel.BackgroundColor = _selectedColor;
        else if (IsPreviewTarget)
            panel.BackgroundColor = _previewColor;
        else if (Button.IsHovered)
            panel.BackgroundColor = _hoveredColor;
        else
            panel.BackgroundColor = _backgroundColor;

        panel.BorderColor = _borderColor;
        panel.BorderThickness = new Thickness(_borderThickness);

        var iconAlpha = Availability switch
        {
            ResearchAvailability.Researched => 1f,
            ResearchAvailability.Available => 1f,
            ResearchAvailability.PrereqsMet => 0.85f,
            ResearchAvailability.Unavailable => 0.4f,
            _ => 0.4f,
        };

        if (IsPreviewTarget)
            iconAlpha *= 0.45f;

        ResearchDisplay.ModulateSelfOverride = new Color(1f, 1f, 1f, iconAlpha);

        LockOverlay.Visible = Availability == ResearchAvailability.Unavailable && !IsPreviewTarget;

        if (IsGhostPreview)
            ModulateSelfOverride = new Color(1f, 1f, 1f, 0.7f);
        else
            ModulateSelfOverride = Color.White;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        Button.OnPressed -= Selected;
    }

    private void Selected(BaseButton.ButtonEventArgs args)
    {
        if (OverrideAction != null)
        {
            OverrideAction.Invoke(Prototype, Availability);
            return;
        }

        SelectAction?.Invoke(Prototype, Availability);
    }
}

public sealed class DrawButton : Button
{
    public event Action? OnDrawModeChanged;

    protected override void DrawModeChanged()
    {
        OnDrawModeChanged?.Invoke();
    }
}
