using Content.Client._Forge.Radio.Ui;
using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.StationRadio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Forge.StationRadio;

[GenerateTypedNameReferences]
public sealed partial class StationRadioFrequencyMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    public event Action<string>? OnFrequencyChanged;
    public event Action? OnReceiverToggled;

    private bool _updating;

    public StationRadioFrequencyMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        FrequencyLineEdit.OnTextEntered += args => OnFrequencyChanged?.Invoke(args.Text);
        FrequencyLineEdit.OnFocusExit += args => OnFrequencyChanged?.Invoke(args.Text);

        RadioFrequencyPresetUi.Populate(PopularFrequencyOptions, _prototypes);
        PopularFrequencyOptions.OnItemSelected += args =>
        {
            if (_updating)
                return;

            PopularFrequencyOptions.SelectId(args.Id);
            if (args.Id == RadioFrequencyPresetUi.CustomOptionId)
            {
                FrequencyLineEdit.GrabKeyboardFocus();
                return;
            }

            OnFrequencyChanged?.Invoke(args.Id.ToString());
        };

        ReceiverToggle.OnPressed += _ =>
        {
            if (!_updating)
                OnReceiverToggled?.Invoke();
        };
    }

    public void Update(StationRadioFrequencyBoundUIState state)
    {
        _updating = true;

        Title = Loc.GetString(state.Mode switch
        {
            StationRadioFrequencyMode.Music => "station-radio-frequency-music-title",
            StationRadioFrequencyMode.Voice => "station-radio-frequency-voice-title",
            _ => "station-radio-frequency-listen-title",
        });

        ModeLabel.Text = Loc.GetString(state.Mode switch
        {
            StationRadioFrequencyMode.Music => "station-radio-frequency-music-label",
            StationRadioFrequencyMode.Voice => "station-radio-frequency-voice-label",
            _ => "station-radio-frequency-listen-label",
        });

        FrequencyLineEdit.Text = state.Frequency.ToString();
        FrequencyLineEdit.PlaceHolder = Loc.GetString("handheld-radio-custom-placeholder",
            ("min", state.MinFrequency),
            ("max", state.MaxFrequency));
        RadioFrequencyPresetUi.Select(PopularFrequencyOptions, state.Frequency);

        ReceiverToggle.Visible = state.Mode == StationRadioFrequencyMode.Listen;
        ReceiverToggle.Pressed = state.ReceiverOn;
        ReceiverToggle.Text = Loc.GetString(state.ReceiverOn
            ? "station-radio-frequency-receiver-on"
            : "station-radio-frequency-receiver-off");

        _updating = false;
    }
}
