using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Forge.ShowRoleInformation;

[GenerateTypedNameReferences]
public sealed partial class ShowRoleInformationWindow : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPlayerManager _playerManager = default!;
    private string _currentKeyWindow = string.Empty;
    private float _remainingTime;

    public ShowRoleInformationWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        NewCloseButton.OnPressed += _ => Close();
        NewCloseButton.Disabled = true;
        CloseButton.Visible = false;
        Resizable = false;
        UpdateCloseButtonText();
    }

    public void SetRoleInfo(string? description,  string name)
    {
        if (string.IsNullOrWhiteSpace(description))
            return;

        RoleNameLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("show-role-information-job-name", ("name", Loc.GetString(name)))));
        RoleDescriptionLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString(description)));
        RoleAdditionalLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("show-role-information-additional")));
        DontShowWindowCButton.Text = $"{FormattedMessage.FromMarkupOrThrow(Loc.GetString("show-role-information-dont-show-window"))}";

        _currentKeyWindow = string.Concat(name, description);
    }

    public void SetDuration(float duration)
    {
        _remainingTime = duration;
    }

    public override void Close()
    {
        if (_remainingTime > 0f)
            return;

        if (DontShowWindowCButton.Pressed && _playerManager.LocalEntity != null)
            _entityManager.EventBus.RaiseLocalEvent(_playerManager.LocalEntity.Value, new ShowRoleInformationAddSkipWindowLocalEvent { KeyWindow = _currentKeyWindow}, true);

        base.Close();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_remainingTime <= 0)
            return;

        _remainingTime = MathF.Max(0f, _remainingTime - args.DeltaSeconds);
        UpdateCloseButtonText();
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.None;
    }

    private void UpdateCloseButtonText()
    {
        var isWaiting = _remainingTime > 0f;
        NewCloseButton.Text = isWaiting
            ? Loc.GetString("show-role-information-close-button-wait", ("time", (int)MathF.Ceiling(_remainingTime)))
            : Loc.GetString("show-role-information-close-button");
        NewCloseButton.Disabled = isWaiting;
    }
}
