using Content.Client.Message;
using Content.Shared._Forge.BlackMarket.BUI;
using Content.Shared._Forge.BlackMarket.Prototypes;
using Content.Shared._NF.Bank;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Forge.BlackMarket.UI;

[GenerateTypedNameReferences]
public sealed partial class BlackMarketSlotEntry : BoxContainer
{
    private const float ConfirmTimeoutSeconds = 3f;

    [Dependency] private readonly IPrototypeManager _proto = default!;

    public Action? OnPurchasePressed;

    private TimeSpan _untilRefresh;
    private bool _available;
    private int _price;
    private int _balance;
    private bool _awaitingConfirm;
    private float _confirmTimeRemaining;
    private string? _contractId;
    private bool _isStub;

    public int SlotIndex { get; private set; }

    public BlackMarketSlotEntry(BlackMarketSlotState slot, int balance)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SlotIndex = slot.SlotIndex;
        PurchaseButton.OnPressed += _ => OnPurchaseButtonPressed();

        UpdateFromState(slot, balance);
    }

    public void UpdateFromState(BlackMarketSlotState slot, int balance)
    {
        SlotIndex = slot.SlotIndex;
        _untilRefresh = slot.UntilRefresh;
        _available = slot.Available;
        _price = slot.Price;
        _balance = balance;

        if (_contractId != slot.ContractId)
            ResetConfirmState();

        _contractId = slot.ContractId;

        CategoryLabel.SetMarkup(Loc.GetString("black-market-console-category-label",
            ("category", Loc.GetString(GetCategoryName(slot.CategoryId)))));

        _isStub = false;

        if (slot.ContractId != null &&
            _proto.TryIndex<BlackMarketContractPrototype>(slot.ContractId, out var contract))
        {
            if (contract.Stub)
            {
                _isStub = true;
                NameLabel.SetMarkup(Loc.GetString(contract.Name));
                PriceLabel.SetMarkup(string.Empty);
                DescriptionLabel.SetMarkup(Loc.GetString(contract.Description));
                LimitLabel.Visible = false;

                if (!string.IsNullOrWhiteSpace(slot.IconPrototype))
                {
                    IconView.Visible = true;
                    IconView.SetPrototype(slot.IconPrototype);
                }
                else
                {
                    IconView.Visible = false;
                }
            }
            else if (slot.Available)
            {
                NameLabel.SetMarkup(Loc.GetString("black-market-console-name-label",
                    ("name", Loc.GetString(contract.Name))));
                PriceLabel.SetMarkup(Loc.GetString("black-market-console-price-label",
                    ("price", BankSystemExtensions.ToSpesoString(slot.Price))));
                DescriptionLabel.SetMarkup(Loc.GetString("black-market-console-description-label",
                    ("description", Loc.GetString(contract.Description))));

                if (!string.IsNullOrWhiteSpace(slot.IconPrototype))
                {
                    IconView.Visible = true;
                    IconView.SetPrototype(slot.IconPrototype);
                }
                else
                {
                    IconView.Visible = false;
                }

                if (slot.PurchasesRemaining >= 0)
                {
                    LimitLabel.Visible = true;
                    LimitLabel.SetMarkup(Loc.GetString("black-market-console-purchase-limit-label",
                        ("remaining", slot.PurchasesRemaining)));
                }
                else
                {
                    LimitLabel.Visible = false;
                }
            }
            else
            {
                NameLabel.SetMarkup(Loc.GetString("black-market-console-refreshing-label"));
                PriceLabel.SetMarkup(string.Empty);
                DescriptionLabel.SetMarkup(string.Empty);
                LimitLabel.Visible = false;
                IconView.Visible = false;
                ResetConfirmState();
            }
        }
        else
        {
            NameLabel.SetMarkup(Loc.GetString("black-market-console-refreshing-label"));
            PriceLabel.SetMarkup(string.Empty);
            DescriptionLabel.SetMarkup(string.Empty);
            LimitLabel.Visible = false;
            IconView.Visible = false;
            ResetConfirmState();
        }

        UpdatePurchaseButton();
        UpdateTimerLabel();
    }

    private void OnPurchaseButtonPressed()
    {
        if (!_available || _price <= 0 || _balance < _price)
            return;

        if (!_awaitingConfirm)
        {
            _awaitingConfirm = true;
            _confirmTimeRemaining = ConfirmTimeoutSeconds;
            UpdatePurchaseButton();
            return;
        }

        ResetConfirmState();
        OnPurchasePressed?.Invoke();
    }

    private void ResetConfirmState()
    {
        _awaitingConfirm = false;
        _confirmTimeRemaining = 0f;
        UpdatePurchaseButton();
    }

    private void ClearConfirmState()
    {
        _awaitingConfirm = false;
        _confirmTimeRemaining = 0f;
    }

    private LocId GetCategoryName(string categoryId)
    {
        if (_proto.TryIndex<BlackMarketCategoryPrototype>(categoryId, out var category))
            return category.Name;

        return categoryId;
    }

    private void UpdatePurchaseButton()
    {
        if (_isStub || !_available || _price <= 0)
        {
            PurchaseButton.Disabled = true;
            PurchaseButton.ModulateSelfOverride = null;
            PurchaseButton.Text = _isStub
                ? Loc.GetString("black-market-console-stub-button")
                : Loc.GetString("black-market-console-purchase-button");
            return;
        }

        if (_balance < _price)
        {
            ClearConfirmState();
            PurchaseButton.Disabled = true;
            PurchaseButton.ModulateSelfOverride = null;
            PurchaseButton.Text = Loc.GetString("black-market-console-insufficient-funds-button");
            return;
        }

        if (_awaitingConfirm)
        {
            PurchaseButton.Disabled = false;
            PurchaseButton.ModulateSelfOverride = Color.Red;
            PurchaseButton.Text = Loc.GetString("black-market-console-confirm-button");
            return;
        }

        PurchaseButton.Disabled = false;
        PurchaseButton.ModulateSelfOverride = null;
        PurchaseButton.Text = Loc.GetString("black-market-console-purchase-button");
    }

    private void UpdateTimerLabel()
    {
        if (_untilRefresh > TimeSpan.Zero)
        {
            TimerLabel.SetMarkup(Loc.GetString("black-market-console-timer-label",
                ("time", _untilRefresh.ToString(@"mm\:ss"))));
        }
        else if (_isStub || _available)
        {
            TimerLabel.SetMarkup(Loc.GetString("black-market-console-timer-soon-label"));
        }
        else
        {
            TimerLabel.SetMarkup(Loc.GetString("black-market-console-refreshing-label"));
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_untilRefresh > TimeSpan.Zero)
        {
            _untilRefresh -= TimeSpan.FromSeconds(args.DeltaSeconds);
            UpdateTimerLabel();
        }

        if (!_awaitingConfirm)
            return;

        _confirmTimeRemaining -= args.DeltaSeconds;
        if (_confirmTimeRemaining <= 0f)
            ResetConfirmState();
    }
}
