using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.BlackMarket.BUI;
using Content.Shared._NF.Bank;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.BlackMarket.UI;

[GenerateTypedNameReferences]
public sealed partial class BlackMarketMenu : FancyWindow
{
    public Action<int>? OnPurchasePressed;

    private readonly Dictionary<int, BlackMarketSlotEntry> _entries = new();

    public BlackMarketMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(BlackMarketConsoleState state)
    {
        BalanceLabel.Text = BankSystemExtensions.ToSpesoString(state.Balance);

        var seen = new HashSet<int>();
        foreach (var slot in state.Slots)
        {
            seen.Add(slot.SlotIndex);
            if (_entries.TryGetValue(slot.SlotIndex, out var existing))
            {
                existing.UpdateFromState(slot, state.Balance);
                continue;
            }

            var entry = new BlackMarketSlotEntry(slot, state.Balance);
            entry.OnPurchasePressed += () => OnPurchasePressed?.Invoke(slot.SlotIndex);
            _entries[slot.SlotIndex] = entry;
            SlotsContainer.AddChild(entry);
        }

        foreach (var key in _entries.Keys.Where(k => !seen.Contains(k)).ToList())
        {
            if (_entries.Remove(key, out var entry))
                entry.Orphan();
        }

        ReorderEntries(state.Slots);
    }

    private void ReorderEntries(List<BlackMarketSlotState> slots)
    {
        foreach (var child in _entries.Values.ToList())
            SlotsContainer.Children.Remove(child);

        foreach (var slot in slots)
        {
            if (_entries.TryGetValue(slot.SlotIndex, out var entry))
                SlotsContainer.AddChild(entry);
        }
    }
}
